### ISSUE TITLE
worktree.Add does not add a modified file correctly while git add works as expected

### ISSUE THREAD

**Issue by lambou123** [go-git/go-git#1003]
Development environment details:

- Ubuntu 23.10
- git 2.40.1
- go-git v5.11.0

cat ~/.gitconfig
```
[merge]
   ff = false
```

I have a modified file (echo "new line" >> readme.txt).

If I run this code, I got a modified file in worktree and index at the same time with the same content.
If I run git add file, this will be added correctly :
```
r,err := git.PlainOpen(dir)
w, err := r.Worktree()
w.Add(file)
```
  
`git diff` shows no changes:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   readme.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   readme.md

```

If I run `git add file`, the output is like that:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   readme.md

```

**Comment by nicholasSUSE** [comment]
I have the same problem, 
I thought it was because my file being modified was huge, but it seems it is not the case.  
I am working on a PR for this. 

@pjbgf

**Comment by nicholasSUSE** [comment]
@lambou123 

I have just made a test, please check what happens with yout. 

```
	if err := workTree.AddWithOptions(&git.AddOptions{Path: "."}); err != nil {
		return err
	}
```

This will work except for files that are huge. 
In a test with a .txt small file, it worked.

**Comment by pjbgf** [comment]
Similar issues (file changes not being added) can be related to what osfs abstraction being used. As some of the file modes are not passed through the file system abstraction when using [osfs.WithChroot()](https://github.com/go-git/go-billy/blob/master/osfs/os_chroot.go#L14-L23), which is the default when doing `Plain*` operations.

However, given that the issue at hand here is about changing the actual file, the proposed PR by @nicholasSUSE seems to be the way forward.
