### ISSUE TITLE
AlternateFS doesn't work with git's `clone --shared` when the origin is also a "shared" one

### ISSUE THREAD

**Issue by wxiaoguang** [go-git/go-git#1006]
(Updated according to the latest test code to make it easier to read)

It seems that AlternateFS doesn't work with git's `clone --shared` when the origin is also a "shared" one. For example:

* There is a repo `/tmp/repo-origin`
* Then "clone --shared" to `/tmp/repo-clone1`
* Then "clone --shared" from "clone1" to `/tmp/repo-clone2`
* Trying to set `altRepoPath` to `/tmp/repo-origin` or `/tmp/repo-clone1`

* If I use `osfs.New(altRepoPath, osfs.WithChrootOS())`
    * then `func (d *DotGit) Alternates()` changes the path to `../repo-clone1/objects` or `objects`, which doesn't exist, then `Alternates` returns error.

* If I use `osfs.New(altRepoPath, osfs.WithBoundOS())`
    * then `func (d *DotGit) Alternates()` tries to use path `/tmp/repo-clone1/objects`, which doesn't exist, then Alternates returns error.

----

The only working approach is: `AlternativeFS: osfs.New("/")`

**Comment by ghthor** [comment]
```
func gitRepos(rootpath string) (map[string]*git.Repository, error) {
	repo, err := git.PlainOpenWithOptions(rootpath, &git.PlainOpenOptions{
		DetectDotGit:          false, // We always give PlainOpen the correct directory
		EnableDotGitCommonDir: true,  // CI doesn't actually have .git/commondir set and  it isn't actually what we want/need; we need object alternates support
	})
	if err != nil {
		return nil, err
	}

	all := make(map[string]*git.Repository)
	all[rootpath] = repo

	var (
		gitfs = osfs.New(filepath.Join(rootpath, ".git")) // TODO: assumes this isn't in file form
		dot   = dotgit.NewWithOptions(gitfs, dotgit.Options{
			ExclusiveAccess: false,
			KeepDescriptors: false,
			AlternatesFS:    osfs.New("/"),
		})
	)
	alts, err := dot.Alternates()
	if err != nil {
		return nil, err
	}

	if len(alts) == 0 {
		return all, nil
	}

	for _, alt := range alts {
		altpath := alt.Fs().Root()
		fmt.Fprintln(os.Stderr, "alternate: ", altpath)

		repo, err := git.Open(filesystem.NewStorage(alt.Fs(), cache.NewObjectLRUDefault()), nil)
		if err != nil {
			return nil, err
		}

		all[altpath] = repo
	}

	return all, nil
}
```

This has been my strategy for a repo that was cloned with `git clone --reference <bare-repo-path>`.

All operations try each repo in the map too find objects during lookup. My usage has a single specific just need for object lookup, but I feel like either I'm missing the obvious way to do this without a `*git.Repository` for each `.git` directory, or there is an opportunity to support this and make this more straightforward.

Figuring out was `osfs` to pass for `AlternateFS` took a while, but finding this issue helped get over that hump. :heart:

**Comment by pjbgf** [comment]
@wxiaoguang note that `go-git` operates over fs abstractions provided by `go-billy`. It is important that the paths you use can be cross-referenced, and the way you do that will largely depend on whether you used [BoundOS](https://github.com/go-git/go-billy/blob/master/osfs/os_bound.go#L32-L42) or [ChrootOS](https://github.com/go-git/go-billy/blob/master/osfs/os_chroot.go#L14-L23). The former has the entire view of the host directory structure, the latter is generally used to represent a subset of it.

**Comment by wxiaoguang** [comment]
> @wxiaoguang note that `go-git` operates over fs abstractions provided by `go-billy`. It is important that the paths you use can be cross-referenced, and the way you do that will largely depend on whether you used [BoundOS](https://github.com/go-git/go-billy/blob/master/osfs/os_bound.go#L32-L42) or [ChrootOS](https://github.com/go-git/go-billy/blob/master/osfs/os_chroot.go#L14-L23). The former has the entire view of the host directory structure, the latter is generally used to represent a subset of it.

As I showed the example, the path handling logic is wrong.

**Comment by pjbgf** [comment]
@wxiaoguang unfortunately your example does not show the big picture. For example, what is the fs for the actual repository you are using? Would you be able to share a code snippet?

**Comment by wxiaoguang** [comment]
I am not using gogit now and I do not have time to setup a project to reproduce it again.

At that time I have a full reproducible environment, and I am pretty sure (>99%) that the logic in gogit is not right, but it seems that there is no response or interest for the issue for long time so I didn't push it then and just bypass it with `AlternativeFS: osfs.New("/")`.

**Comment by wxiaoguang** [comment]
Too long time to recall the contexts, will try to write a clear reproducible sample later if I encounter the problem again.

Thank you for your time!

**Comment by wxiaoguang** [comment]
Do the best to recall my memory:


```
package gogittest

import (
	"fmt"
	"github.com/go-git/go-billy/v5/osfs"
	gogit "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/cache"
	"github.com/go-git/go-git/v5/storage/filesystem"
	"github.com/stretchr/testify/assert"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

func execCmd(cmd string, args ...string) error {
	fmt.Printf("cmd: %s %s\n", cmd, strings.Join(args, " "))
	return exec.Command(cmd, args...).Run()
}

func TestGogitCloneShared(t *testing.T) {
	// use system temp dir to make debugging easier, developers could check the content of these directories
	tmpBaseDir := filepath.Join(os.TempDir(), "/repo-gogit-test")

	repoOrigin := filepath.Join(tmpBaseDir, "repo-origin")
	repoCloned1 := filepath.Join(tmpBaseDir, "repo-cloned1")
	repoCloned2 := filepath.Join(tmpBaseDir, "repo-cloned2")

	execCmd("rm", "-rf", tmpBaseDir)
	os.MkdirAll(repoOrigin, os.ModePerm)
	os.Chdir(repoOrigin)
	execCmd("git", "init")
	os.WriteFile(filepath.Join(repoOrigin, "README.md"), []byte("# Hello, World!"), os.ModePerm)
	execCmd("git", "add", ".")
	execCmd("git", "commit", "-m", "Initial commit")
	execCmd("git", "clone", "--bare", "--shared", repoOrigin, repoCloned1)
	execCmd("git", "clone", "--bare", "--shared", repoCloned1, repoCloned2)

	fs := osfs.New(repoCloned2)
	altFs := osfs.New(repoOrigin, osfs.WithChrootOS()) // HERE, only "osfs.New("/")" works
	storage := filesystem.NewStorageWithOptions(fs, cache.NewObjectLRUDefault(), filesystem.Options{AlternatesFS: altFs})
	gogitRepo, err := gogit.Open(storage, fs)
	assert.NoError(t, err)
	_, err = gogitRepo.Grep(&gogit.GrepOptions{Patterns: []*regexp.Regexp{regexp.MustCompile("Hello")}})
	assert.NoError(t, err)
}
```

**Comment by pjbgf** [comment]
@wxiaoguang thanks for sharing that code snippet and updating the issue title.

You are trying to open a repository, whose alternate has an alternate, which currently is not supported:

```
repo -> alternate1 -> alternate2
```

However, `go-git` supports multiple alternates, so in theory you could:

```
repo -> alternate1 -> alternate2
     -> alternate2
```

From your example, you mentioned that `altFs` had to be `/`. However, it could also be `/tmp`, `/tmp/repo-gogit-test` or `/tmp/repo-gogit-test/repo-origin` (the latter only when opening repoCloned1):
```golang
fs := osfs.New(repoCloned1)
altFs := osfs.New(tmpBaseDir, osfs.WithChrootOS())
```

All that works, because absolute paths are translated to relative when [ChrootOS](https://github.com/go-git/go-git/blob/4fd9979d5c2940e72bdd6946fec21e02d959f0f6/storage/filesystem/dotgit/dotgit.go#L1197) is beign used in the altFS.


Combining both information above, you should be able to get that initial code working with:
```golang
fs := osfs.New(repoCloned2)
altFs := osfs.New(tmpBaseDir, osfs.WithChrootOS())
storage := filesystem.NewStorageWithOptions(fs, cache.NewObjectLRUDefault(), filesystem.Options{AlternatesFS: altFs})
storage.AddAlternate(filepath.Join(repoOrigin,".git")) // this has the side effect of repoCloned2 now having an additional alternate even outside of `go-git`.
```

Note that a repository's alternates can be accessible via `storage.Alternates()`, so you could automatically add them only when needed.

**Comment by wxiaoguang** [comment]
Thank you.

I guess `AlternativeFS: osfs.New("/")` still wins because in many cases when it's impossible to figure out/add all alternates ahead.
