### ISSUE TITLE
Missing push options

### ISSUE THREAD

**Issue by eelco** [go-git/go-git#101]
I might be missing something, but there seem to be a lot of push options that are not available? In particular, I’m looking for the equivalents for:
- `--force-with-lease`
- `--follow-tags`
- `--atomic`

**Comment by shashwat-appdirect** [comment]
Hi @eelco,
I am also looking for the same options to be available so that I could push both local commits and tags in one Push operation. Could you please let me know if you find any solution?

Thanks.

**Comment by john-cai** [comment]
`--force-with-lease`: https://github.com/go-git/go-git/pull/404

**Comment by john-cai** [comment]
`--atomic`: https://github.com/go-git/go-git/pull/406

**Comment by john-cai** [comment]
@mcuadros I believe this issue can be closed, as we've added all of these push options

**Comment by pjbgf** [comment]
Closing as per @john-cai message.
