### ISSUE TITLE
storage example update to use go-git v5

### ISSUE THREAD

**Issue by grinish21** [go-git/go-git#1013]
The current [storage](https://github.com/go-git/go-git/tree/master/_examples/storage) example with aeropspike uses V4 and can use an update or a new version with v5.  Just as a suggestion  an storage example backed up by postgres with V5 might be more useable.

**Comment by iainjreid** [comment]
We're in the process of writing a storage backend that does exactly that, with full support for the generic `database/sql` interface. Currently it seems like quite a lot of work given the size of the `storage.Storer ` interface, so some direction would certainly be appriciated.

When the implementation is ready we'll open source it right away, and hopefully link back to this ticket 👍

**Comment by iainjreid** [comment]
Apologies for the silence, I've actually finished [barebones implementation](https://github.com/emphori/go-git-sql), but completely forgot to update this thread... 🤦‍♂️

I still need to push up some documentation and other bits, but this works against Postgres and _should_ work against any other SQL backend.
