### ISSUE TITLE
Shallow Clone, Checkout single file?

### ISSUE THREAD

**Issue by marc-ostrow** [go-git/go-git#102]
I'm trying to figure out how I could perform an in-memory, shallow (no-checkout, depth = 1) clone, followed by a checkout of a single file.

I've got the in-memory shallow clone done, using Checkout Options NoCheckout set to true and Depth set to 1, but cannot find a way to perform a Checkout on a pathspec, so as to specify a single file in the work tree.

**Comment by willstott101** [comment]
Looks like this is probably a duplicate of https://github.com/go-git/go-git/issues/90

**Comment by mcuadros** [comment]
Yup looks like duplicate closing in favor of the other issue.
