### ISSUE TITLE
Git restore - existing pull request

### ISSUE THREAD

**Issue by GraphR00t** [go-git/go-git#1033]
This [pull request](https://github.com/go-git/go-git/pull/493)  from 2022 adds support for operations like `git restore --staged <file>`.

It would be great if it could be merged. Thank you :)

**Comment by pjbgf** [comment]
@GraphR00t I reviewed the PR and the author is looking into it.

I am closing this issue as a duplicate of https://github.com/go-git/go-git/issues/342. Let's continue any additional discussions on the topic within the PR or the existing issue.
