### ISSUE TITLE
Getting object file Reader will load content of even large blobs into memory

### ISSUE THREAD

**Issue by lafriks** [go-git/go-git#104]
When calling `Reader` method of `object.File` it will read all content into memory that can easily drain memory. Would be nice if there was option that it would return wrapper to FS reader limited to specific object pos & length

Ref: https://github.com/go-git/go-git/blob/8019144b6534ff58ad234a355e5b143f1c99b45e/plumbing/format/packfile/packfile.go#L277

**Comment by rgalanakis** [comment]
Was coming here to report the same issue... The blob Reader is a stream so it was disappointing to see that it loads the entire blob into memory.

**Comment by zeripath** [comment]
in storage/filesystem/object.go I would guess it would be sensible to do a size check of the object that is being decoded and if it is greater than some reasonable limit the reader should not just read the object into memory but instead has a slightly more complex reader.

Now the question is how big should we reasonably be able to read in directly?

**Comment by rgalanakis** [comment]
My example use case was sniffing the first few hundred bytes to do content type sniffing, so anything more than that would be wasteful. If there needs to be a cutoff, it seems best to give callers some option to specify the limit. Why not always stream it/never load it into memory? (I can't remember the implementation of this code so I suspect I'm missing a reason)

**Comment by lafriks** [comment]
@zeripath it could just return custom reader for that is limited by specific positions, this way it would not need to read anything into memory and would not need any limitations

**Comment by zeripath** [comment]
My suspicion is that for very small blobs that actually could use more memory. 

The majority of items in a git repo are probably less than 4kb which will fit in most default buffers and probably be already read completely in to memory by the time you've found them in a pack file.

It's really a question of at what point is it worth switching to a more complex mechanism.

**Comment by lafriks** [comment]
depending on size it could fall back to different readers - memory or custom reader implementation from pack file

**Comment by rgalanakis** [comment]
This can be a significant memory and performance issue for users (and because we expect most things to be streams, is unexpected). If it's too cumbersome to fix then close this issue but it's still relevant and important.

**Comment by lafriks** [comment]
This is still an problem

**Comment by pjbgf** [comment]
We should be able to resolve this for seekable storage. Around similar lines to what #799 proposes.

**Comment by zeripath** [comment]
This should have mostly been ameliorated by #330

**Comment by pjbgf** [comment]
Closing due to both #799 and #330 being merged and for lack of activity in this issue.
