### ISSUE TITLE
Pushing a hash to a branch is not working?

### ISSUE THREAD

**Issue by eelco** [go-git/go-git#105]
I’m trying to push a commit hash to a branch, this is a fairly common pattern for us (to do deployments):

```
        refSpecs := []config.RefSpec{
		config.RefSpec(fmt.Sprintf("%s:refs/heads/release/%s", commit.Hash, env)),
	}
	err = r.Push(&git.PushOptions{
		RemoteName: "origin",
		RefSpecs:   refSpecs,
        }
```

However, this results in an `already up-to-date` error, which is definitely not true. The equivalent command on the CLI works without problem, so I’m assuming it’s not the RefSpec that’s wrong here.

**Comment by yurifrl** [comment]
I'm having the exact same issue

**Comment by polothy** [comment]
Had same problem, this worked for me:
```go
		headRef, err := repo.Head()
		if err != nil {
			return err
		}
		refSpec = fmt.Sprintf("%s:refs/heads/branch-name", headRef.Name())
		err = repo.Push(&git.PushOptions{
			RemoteName: "origin",
			RefSpecs: []config.RefSpec{config.RefSpec(refSpec)},
			Auth: &http.BasicAuth{...},
			Force: true,
		})
		if err != nil {
			return err
		}
```

The `refSpec` ends up having a value of just `HEAD:refs/heads/branch-name`

**Comment by martin-sucha** [comment]
The refspec is ignored here: https://github.com/go-git/go-git/blob/c66023ad305ee56a38781cc5d3ca96c7115bd2e5/remote.go#L476

**Comment by hermanbanken** [comment]
I also have this issue when I directly specify the refspec to be a commit hash:

```
	err = outputRepo.Push(&git.PushOptions{
		RefSpecs:          []config.RefSpec{config.RefSpec("38fed38fa8f8f4f9a5564a5727cd6778b97a2c75:refs/heads/somebranch")},
		Auth:              gitAuth,
		Progress:          prefixw.New(os.Stderr, "> "),
	})
```

I was trying to use the `RequireRemoteRefs` as an alternative to `Force`, but that doesn't work. If I set `Force`, somehow the push goes through. Seems that there is a bug deciding if a push needs to happen (internally `len(req.Commands) == 0` while refs need to be updated...)
