### ISSUE TITLE
CommitOptions.AllowEmptyCommits does nothing

### ISSUE THREAD

**Issue by akamensky** [go-git/go-git#1058]
My code sets

```go
	&git.CommitOptions{
		AllowEmptyCommits: false,
		Author: &object.Signature{
			Name:  author,
			Email: email,
			When:  time.Now(),
		},
	}
```

That however still allows completely empty commits through even if nothing was written. I am cloning to in-memory storage and modify files only if the contents is different (so I read files, on the same note, why is the billy.Filesystem does not implement fs.FS?).

I still have to do `state.IsClean()` check, which will actually check if there are any changes.

**Comment by durvalcarvalho** [comment]
Yep! Same thing here.

**Comment by onee-only** [comment]
I think this is the same problem as #723.

**Comment by onee-only** [comment]
It should be fixed by #1050. Would you check if the problem still exists with code on master @akamensky @durvalcarvalho?

**Comment by akamensky** [comment]
I cannot test this for awhile. Hopefully someone else would be able to test. Thanks for fixing it!

**Comment by mostcute** [comment]
yes ,fixed but the latest release didn't contain it

**Comment by pjbgf** [comment]
Closing as this is in `master` and will soon be part of `v5.13.0`. If the issue is reproduceable on `v5.13.0`, please create a new issue.
