### ISSUE TITLE
Personal access token : invalid auth method

### ISSUE THREAD

**Issue by PillowPillow** [go-git/go-git#1080]
Hello, I m trying to use a githubpersonal access token to fetch my git tag with the following code : 

```go
package utils

import (
	"fmt"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/config"
	"github.com/go-git/go-git/v5/plumbing/transport/http"
	"log"
)

func FetchAllTags() error {
	auth := &http.BasicAuth{
		Username: "username",
		Password: "PERSONAL_GITHUB_ACCESS_TOKEN",
	}

	err := GetRepository().Fetch(&git.FetchOptions{
		RefSpecs: []config.RefSpec{"refs/tags/*:refs/tags/*"},
		Auth:     auth,
	})

	log.Println(err)
	if err != nil && err != git.NoErrAlreadyUpToDate {
		return fmt.Errorf("failed to fetch tags: %w", err)
	}
	return nil
}
```
I m keep strugling with the error "invalid auth method".. Is there a way to debug this error ? I verified the token by trying it in a curl call and its ok..

Thanks for your help

**Comment by onee-only** [comment]
Can you provide information about the protocol you use to connect to the remote repository?
It seems like http.BasicAuth won't work if you use git or ssh protocol.

**Comment by PillowPillow** [comment]
Thanks for your reply ! 
You have a point ! I m using ssh..  so can t I use a GitHub token to fetch data if my repo has been clone through ssh ?

**Comment by onee-only** [comment]
If you are going to use ssh connection, please read the doc [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh) first.

I'm not quite familiar with this codebase, but I'm guessing you'll need `ssh.PublicKeys` to authenticate through ssh.

**Comment by pjbgf** [comment]
Please check out our [examples](https://github.com/go-git/go-git/tree/master/_examples/clone/auth) for both ssh and basic auth authentication. For SSH we have both [private key](https://github.com/go-git/go-git/tree/master/_examples/clone/auth/ssh/private_key) and [ssh agent](https://github.com/go-git/go-git/tree/master/_examples/clone/auth/ssh/ssh_agent) code examples that you can lean on.

**Comment by PillowPillow** [comment]
Thanks for your replies. I managed to fix the issue by implementing SSH or Basic Auth according the repository remoteURL.
