### ISSUE TITLE
 When executing worktree.Add("."), an error of "invalid checksum" is reported.

### ISSUE THREAD

**Issue by allanguys** [go-git/go-git#1081]
After some breakpoint debugging, I found that the error is returned from the line `err = d.Decode(idx)`.
The error occurred in Windows 10.

also get this error while using worktree.push: 
```
workTree.Pull(&git.PullOptions{
		RemoteName: "origin"
	})
```

**Comment by BeChris** [comment]
Hello @allanguys ,
You are surely trying to open a worktree whose .git/index is in version 4.
In Go-Git master branch, preliminary support to parse this version has been implemented.
And with pull request #1251, I added support to update a .git/index is in version 4 (like it is done after git.Worktree.Add has been called, like in your example).

You could try to update your Go-Git dependency pointing to the commit where my pull request has been merged:
At the root of your project, type:
```sh
go get github.com/go-git/go-git/v5@9973a38
```

I had the same problem and after issuing the go get command my problem was fixed.

Regards.

**Comment by pjbgf** [comment]
Closing this as per #1251 happy to reopen if the issue persists.
