### ISSUE TITLE
timeout option for slow git clone

### ISSUE THREAD

**Issue by chengtianfa** [go-git/go-git#1096]
has timeout CloneOption？
if no, how can i handle slow clone?

**Comment by onee-only** [comment]
You can use context to time out the operation.
```go
func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	r, err := git.PlainCloneContext(ctx, ".", false, &git.CloneOptions{
		URL: "your remote git repository url",
	})
}
```
There is an [example](https://github.com/go-git/go-git/blob/master/_examples/context/main.go) for clone with context. Although it is not about timeout, it should be helpful.

Alternatively, you can also use custom http client for operations. [custom http example](https://github.com/go-git/go-git/blob/master/_examples/custom_http/main.go)

**Comment by pjbgf** [comment]
Closing as per @onee-only's message.
