### ISSUE TITLE
Bug: worktree cannot be read if created with version 4

### ISSUE THREAD

**Issue by apodznoev** [go-git/go-git#1123]
Steps to reproduce:
- Setup git config file to contain a feature requiring `index.version = 4`, e.g.
```
[feature]
	manyFiles = true
```
- Checkout a branch, call `git status` which creates index according to settings
- Using `gitGo` create repository using the path above:
```
repo, _ := goGit.PlainOpen(repoPath)
````
- Get a worktree status:
```
worktree, _ := repo.Worktree()
worktreeStatus, err := worktree.Status()
```
`err` is `plumbing.format.index.ErrInvalidChecksum`

My clue is that the index file has `version 4` encoded in its header as of documentation https://git-scm.com/docs/gitformat-index 

Where the library hardcodes version 2 and uses it for decoding index:

```
from: storage.filesystem.index.decoder.go

func (s *IndexStorage) Index() (i *index.Index, err error) {
	idx := &index.Index{
		Version: 2,
	}

	f, err := s.dir.Index()
	if err != nil {
		if os.IsNotExist(err) {
			return idx, nil
		}

		return nil, err
	}

	defer ioutil.CheckClose(f, &err)

	d := index.NewDecoder(f)
	err = d.Decode(idx)
	return idx, err
}
```

**Comment by vtolstov** [comment]
any chance to fix this? now this library useless because all my repos created with never format.

**Comment by BeChris** [comment]
Hello @apodznoev,
You are surely trying to open a worktree whose .git/index is in version 4.
In Go-Git master branch, preliminary support to parse this version has been implemented.
And with pull request #1251, I added support to update a .git/index is in version 4 (like it is done after git.Worktree.Checkout has been called).

You could try to update your Go-Git dependency pointing to the commit where my pull request has been merged:
At the root of your project, type:
```sh
go get github.com/go-git/go-git/v5@9973a38
```

I had the same problem and after issuing the go get command my problem was fixed.

Regards.
