### ISSUE TITLE
worktree.Add(".") does not work as expected and CommitOptions{All: true} is too slow

### ISSUE THREAD

**Issue by StupidScience** [go-git/go-git#113]
Hello.

Thank you for your package.
I started to use it recently with version `v5.1.0` and found some strange things.
First of all `worktree.Add(".")` doesn't work same way as `git add .`. In my case it doesn't delete files from index.

Also if I try to use `worktree.Commit("message", &CommitOptions{All: true})` it takes a lot of time although my repo is relatively small.

So if I rename files and then run `worktree.Add(".")` and `worktree.Commit("message", &CommitOptions{})` it works relatively fast but there are old and new files persist in my repo.
With `worktree.Commit("message", &CommitOptions{All: true})` it works as expected but takes about 70 seconds on my repo with ~1500 files (~15 Mb overall), and about 30 seconds if I deleting biggest project's folder: ~650 files (~10 Mb)

Any suggestions here?

**Comment by mcuadros** [comment]
Currently, I don't have to take a look, any further information or a PR will be well come thanks

**Comment by StupidScience** [comment]
Hello @mcuadros

I've investigated a bit regarding to `worktree.Add(".")`.
Looks like it only go through files that exist in filesystem.

Moreover I tried to workaround it with consecutive `worktree.Remove(".")`, `worktree.Add(".")` actions, but `worktree.Remove(".")` also stage only files that exist on filesystem and `worktree.Add(".")` detected only  `.git` directory, so it did nothing.

So looks like root cause somewhere here in `worktree.Filesystem.ReadDir(directory)`
https://github.com/go-git/go-git/blob/641ee1dd69d3b8616127623e4b9341f4f4196d12/worktree_status.go#L273

It returns files that exist on filesystem excluding removed from index files.
However I believe it should return all existed on filesystem files + files that removed from it but is in worktree.

Any suggestions here?

I think would be better to fix `Hello @mcuadros
I've investigated a bit regarding to `worktree.Add(".")`.
Looks like it only go through files that exist in filesystem.

Moreover I tried to workaround it with consecutive `worktree.Remove(".")`, `worktree.Add(".")` actions, but `worktree.Remove(".")` also stage only files that exist on filesystem and `worktree.Add(".")` detected only  `.git` directory, so it did nothing.

So looks like root cause somewhere here in `worktree.Filesystem.ReadDir(directory)`
https://github.com/go-git/go-git/blob/641ee1dd69d3b8616127623e4b9341f4f4196d12/worktree_status.go#L273

It returns files that exist on filesystem excluding removed from index files.
However I believe it should return all existed on filesystem files + files that removed from it but is in worktree.

Any suggestions here?

Regarding `worktree.Commit("message", &CommitOptions{All: true})` I'll send a PR soon. It take so long because every time `worktree.Status()` is invoked.

**Comment by StupidScience** [comment]
@mcuadros thank you for quick reaction with PR.
Can we reopen this because it is just partially fixed?

**Comment by mcuadros** [comment]
Yep, was closed automatically because of the PR.

**Comment by gdsoumya** [comment]
Any update on how to stage deleted files with worktree.Add(".") ?

**Comment by gdsoumya** [comment]
> Any update on how to stage deleted files with worktree.Add(".") ?

In my program I am using os.RemoveAll() to delete a specific file and then using worktree.Add(".") to stage the changes. But this doesn't stage those changes. 

But when I do a manually delete a file from the repo and then try Add(".") it successfully stages the deleted file. I am not sure why this is happening. @mcuadros

**Comment by ThinkChaos** [comment]
I think this was resolved by 5dabd83e3712e2554745c736b55df405a0ba4f33 and can be closed.
