### ISSUE TITLE
Symlinks pointing outside repository are mangled with PlainOpen

### ISSUE THREAD

**Issue by nf-brentsaner** [go-git/go-git#1155]
See here for fix: https://github.com/go-git/go-git/issues/253#issuecomment-2043338952

I need to commit symlinks that are intentionally pointed outside the repository.

For example:

```
# git diff X11/fontpath.d/liberation-sans-fonts
diff --git a/X11/fontpath.d/liberation-sans-fonts b/X11/fontpath.d/liberation-sans-fonts
index 0e445f8..0a9a11f 120000
--- a/X11/fontpath.d/liberation-sans-fonts
+++ b/X11/fontpath.d/liberation-sans-fonts
@@ -1 +1 @@
-/../usr/share/fonts/liberation-sans
\ No newline at end of file
+/usr/share/fonts/liberation-sans
\ No newline at end of file
# ls -l X11/fontpath.d/liberation-sans-fonts
lrwxrwxrwx. 1 root root 32 Apr  1 20:59 X11/fontpath.d/liberation-sans-fonts -> /usr/share/fonts/liberation-sans
```

`git` properly commits this as-is, but go-git mangles it to an absolute path in the commit - THUS even after a commit, the worktree is always dirty *because the commit created by go-git does not contain the proper content that reflects the real 'contents'*.

This leads to broken status in *addition* to an inaccurate/incorrect commit's file contents.

**Comment by pjbgf** [comment]
@nf-brentsaner as per link you shared, the use of `osfs.BoundOS` resolves the problem. Usage would look like this:

```golang
	wt := osfs.New(dir, osfs.WithBoundOS())
	dotfs, err := wt.Chroot(git.GitDirName)
	if err != nil {
		return nil, err
	}
	store := filesystem.NewStorage(dotfs, cache.NewObjectLRUDefault())

	repository, err := git.Clone(store, wt, &git.CloneOptions{
		URL:      repositoryName,
		Progress: os.Stdout,
		Depth:    1,
	})
```

The [ChrootOS](https://github.com/go-git/go-billy/blob/b2bff47672df8506ac887f9b566769d2e1cd8282/osfs/os_chroot.go#L14-L23) is still the default in `go-git`, although that may change on V6.

**Comment by pjbgf** [comment]
@nf-brentsaner thanks for clarifying it. Due to the potential backwards-compatibility issues this will need to happen for the V6 release, together with other API and Behaviour changes tracked on #910.

**Comment by pjbgf** [comment]
Closing this as the PR is now merged on the `v6-exp` branch, which is the working branch for the changes targeting the next major release.
