### ISSUE TITLE
ignored files getting deleted on pull

### ISSUE THREAD

**Issue by j4k4** [go-git/go-git#1175]
On every pull, files getting deleted which are in my gitignore file.\
A `MergeReset` is performed. But on reset, the ignored files are not taken into consideration.\
You can see it here: https://github.com/go-git/go-git/blob/master/worktree.go#L436 \
`func (w *Worktree) diffStagingWithWorktree(reverse, excludeIgnoredChanges bool) (merkletrie.Changes, error) {`
`excludeIgnoredChanges` is always false. Is there a reason for this behaviour? 
I have quite some config files which don't belong into version control and go-git is just not usable, if they are disappearing on each pull.

**Comment by pjbgf** [comment]
Closing as it seems to be a duplicate of #53. Please provide steps to reproduce or further information on that other issue instead.
