### ISSUE TITLE
Does go-git support blobless clone?

### ISSUE THREAD

**Issue by wetcod** [go-git/go-git#1180]
Hello,

I would like to know if go-git supports the blobless clone. 
This feature can significantly reduce the amount of data transferred during cloning by skipping certain blobs and fetching them only when needed, which is particularly useful for large repositories.
https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/

Is the blobless clone feature currently supported?
or if not supported now, is there a support plan?

Thank you for your assistance!

**Comment by pjbgf** [comment]
TL;DR: this is currently not supported.

Closing as duplicated of https://github.com/go-git/go-git/issues/713.
