### ISSUE TITLE
cant checkout worktree

### ISSUE THREAD

**Issue by vtolstov** [go-git/go-git#1245]
```
heckout(w git.Worktree, ref plumbing.Reference) error {
	ctx := context.Background()
	g.logger.Debug(ctx, "checkout: "+ref.Name().String())

	if err := w.Checkout(&git.CheckoutOptions{
		Branch: ref.Name(),
		Create: false,
		Force:  true,
		Keep:   false,
	}); err != nil {
		g.logger.Error(ctx, "failed to reset", err)
		return err
	}
	return nil
```

return invalid checksum
but ref i'm get via repo.Head() after opening repo via repo, err := git.PlainOpenWithOptions(".", &git.PlainOpenOptions{DetectDotGit: true})

**Comment by vtolstov** [comment]
Also worktree status returns error "invalid checksum"

**Comment by BeChris** [comment]
Hello @vtolstov,
You are surely trying to open a worktree whose .git/index is in version 4.
In Go-Git master branch, preliminary support to parse this version has been implemented.
And with pull request #1251, I added support to update a .git/index is in version 4 (like it is done after git.Worktree.Checkout has been called, like in your example).

You could try to update your Go-Git dependency pointing to the commit where my pull request has been merged:
At the root of your project, type:
```sh
go get github.com/go-git/go-git/v5@9973a38
```

I had the same problem and after issuing the go get command my problem was fixed.

Regards.

**Comment by pjbgf** [comment]
Closing as per #1251. If the issue persists we can always reopen it.
