### ISSUE TITLE
Please release the latest version

### ISSUE THREAD

**Issue by kane8n** [go-git/go-git#1254]
Hi Maintainers.
I noticed that releases have not occurred since March, and I was wondering if it would be possible to release version v5.13.0 or v5.12.1 based on the latest master branch.

I am particularly in need of a version that includes the fixes introduced in PR #1101.

**Comment by BeChris** [comment]
I add my one cent on this request :)

**Comment by CrowleyRajapakse** [comment]
Yes, interested in the changes done in: https://github.com/go-git/go-git/commit/b55214ccee0b802ebaca9ec00848e65259a36629

**Comment by pjbgf** [comment]
Closing as per [release v5.13.0](https://github.com/go-git/go-git/releases/tag/v5.13.0).

**Comment by kane8n** [comment]
Thanks @pjbgf !
