### ISSUE TITLE
Checkout any of short-hash/hash/branch/tag

### ISSUE THREAD

**Issue by amitmahbubani** [go-git/go-git#132]
On git, we're able to checkout a short-hash, hash, branch ref, tag in the same command:
```sh
> git checkout master # branch
> git checkout a23e836 # short hash
> git checkout e626226dea1d1e843b5295519f40cecdaa21004c # full hash
> git checkout v1.0.0 # tag
```

The following are not possible with go-git's [CheckoutOptions](https://pkg.go.dev/github.com/go-git/go-git/v5?tab=doc#CheckoutOptions):
1. We are expected to explicitly set either a hash or ref. If this cannot be determined (such as in cases where the input is user-entered), there's no simple way of checkout. 
2.  The 7-character short SHA hash is not supported. For ex, the [plumbing.IsHash()](https://github.com/go-git/go-git/blob/8019144b6534ff58ad234a355e5b143f1c99b45e/plumbing/hash.go#L77) function checks for a 40-char length string.

IMO, keeping compatibility goals in mind, a shorthand option allowing checkout of short-hash/hash/branch/tag would be useful.

**Comment by nodece** [comment]
This is good idea, I'm looking forward the feature.

**Comment by dsymonds** [comment]
Repository.ResolveRevision supports resolving short hashes (since #136), so all those use cases should be able to go through that method before you do a checkout.

**Comment by nodece** [comment]
@dsymonds  thanks for your time, looks great! I think we should add example for checkout  short-hash/hash/branch/tag to document for make it easy for users to find it.

**Comment by nodece** [comment]
for example:
```golang
func main() {
	r, err := git.PlainClone("./casbin", false, &git.CloneOptions{
		URL: "https://github.com/casbin/casbin.git",
	})
	if err != nil {
		log.Println("PlainClone", err)
		return
	}

	w, err := r.Worktree()
	if err != nil {
		log.Println("Worktree", err)
		return
	}
        
        // I'm not sure there's an easier way to fetch branch. 
	err = r.Fetch(&git.FetchOptions{
		RefSpecs: []config.RefSpec{"refs/*:refs/*", "HEAD:refs/heads/HEAD"},
	})
	if err != nil {
		log.Println("Fetch", err)
		return
	}

	h, err := r.ResolveRevision("release-3.0.0") // It should be support branch, hash, tag
	if err != nil {
		log.Println("ResolveRevision", err)
		return
	}

	err = w.Checkout(&git.CheckoutOptions{Hash: plumbing.NewHash(h.String())})
	if err != nil {
		log.Println("Checkout", err)
		return
	}
}
```

**Comment by jimafisk** [comment]
Another example:

```go
import (
  "github.com/go-git/go-git/v5"
  "github.com/go-git/go-git/v5/plumbing"
)

func main() {

  r, _ := git.PlainClone("./repo", false, &git.CloneOptions{
    URL: "git@github.com:user/repo",
  })

  h, _ := r.ResolveRevision(plumbing.Revision("a23e836"))

  w, _ := r.Worktree()
  w.Checkout(&git.CheckoutOptions{
    Hash: *h,
  })

}
```

**Comment by ylmcr7** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100c91034]

goroutine 1 [running]:
github.com/go-git/go-git/v5.(*Repository).ResolveRevision(0x0, {0x100ca9a81?, 0x14000207e98?})
        /Users/yingliming/go/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/repository.go:1445 +0x624
main.main()
