### ISSUE TITLE
Count number of added lines per commit

### ISSUE THREAD

**Issue by kaihendry** [go-git/go-git#138]
Hi, I'm looking to quickly iterate through the objects and count the number of lines added. 

Like what I am doing here with numstat but faster: https://github.com/kaihendry/graphsloc/blob/master/collect-stats.sh#L32

Is that possible to do with this library? Many thanks,

**Comment by riyaz-ali** [comment]
You can use [`Commit.Stats()`][1] to get the stats of a commit.

For a single commit, you can use -

```golang
package main

import (
	"fmt"
	"github.com/go-git/go-git/v5"
)

func main() {
	repo, _ := git.PlainClone("/tmp/go-git", false, &git.CloneOptions{
		URL: "https://github.com/go-git/go-git",
	})
	head, _ := repo.Head()
	commit, _ := repo.CommitObject(head.Hash())
	stats, _ := commit.Stats()

	for _, stat := range stats {
		fmt.Printf("add: %d\tdel: %d\tfile: %s\n", stat.Addition, stat.Deletion, stat.Name)
	}
}
```

Or with a [`CommitIter`][2], you can do

```golang
iter, _ := repo.Log(&git.LogOptions{})
_ = iter.ForEach(func(commit *object.Commit) error {
    stats, _ := commit.Stats()
    // use stats here ...
})
```

[1]: https://pkg.go.dev/github.com/go-git/go-git/v5@v5.1.0/plumbing/object#Commit.Stats
[2]: https://pkg.go.dev/github.com/go-git/go-git/v5@v5.1.0/plumbing/object#CommitIter

**Comment by kaihendry** [comment]
Thank you! I'm doing that now in https://github.com/kaihendry/lesshero
