### ISSUE TITLE
possibility to authenticate(ssh/http) with git.NewRemote

### ISSUE THREAD

**Issue by richie-tt** [go-git/go-git#142]
I am using the following [example](https://github.com/go-git/go-git/blob/master/_examples/ls-remote/main.go) to get all branches from a remote repo, it works flawlessly, but now I would like to do the same on a repo where required is to make the authentication.

Can you please show how to do that, I checked a few methods from [here](https://github.com/src-d/go-git/issues/550), bo looks like the `config.RemoteConfig` doesn't support the AUTH

**Comment by riyaz-ali** [comment]
In the example you linked, you can provide [`ListOptions.Auth`][1]. For `http` you can use any implementation of [`http.AuthMethod`][2] or for `ssh` you can use implementations of [`ssh.AuthMethod`][3]

[1]: https://pkg.go.dev/github.com/go-git/go-git/v5#ListOptions
[2]: https://pkg.go.dev/github.com/go-git/go-git/v5@v5.1.0/plumbing/transport/http#AuthMethod
[3]: https://pkg.go.dev/github.com/go-git/go-git/v5@v5.1.0/plumbing/transport/ssh#AuthMethod

**Comment by 1ricardo** [comment]
Hi @riyaz-ali 

Thank you for your help, I really appreciate it, that is my first project in GO and sometimes it's very difficult for me to find an answer.
