### ISSUE TITLE
git clone gives error with SSH Agent

### ISSUE THREAD

**Issue by pgbytes** [go-git/go-git#143]
I am trying to clone a repository in my CI pipeline (Bitbucket pipeline). 

in the pipeline step: 

a normal `git clone git@bitbucket.org:company/repo-name.git` works fine.

git.Clone() from go-git gives an error: 

```
error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```

Although the normal git clone worked, but to test I started a new ssh agent with `eval $(ssh-agent) > /dev/null` as a step in the pipeline. 
Now I get an ssh handshake error.

This go-git code works perfectly on my local machine. 

I tried to provide an SSH Agent to the clone method: 

```
agent, _ := ssh.NewSSHAgentAuth("bitbucket-pipelines")
repo, err := git.Clone(store, fs, &git.CloneOptions{
		URL:      repoPath,
		Progress: os.Stdout,
		Auth:     agent,
	})
```
but I still get the error: 
```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

what am I missing here?
do I need to configure the public key for every repository it will be cloning?

*UPDATE*

I added the following to my pipeline steps:

```
   - eval $(ssh-agent) > /dev/null
   - ssh-add /opt/atlassian/pipelines/agent/ssh/id_rsa
```

This made things work fine. Is there a way I can do this with the git-clone options?

**Comment by newnoiseworks** [comment]
having the same issue w/ the same error message, but it's on a Windows 10 dev machine (works fine on OSX machine)

**Comment by stalkerg** [comment]
yes, what progress? Looks like go-git can't work without ssh-agent.

**Comment by liwenson** [comment]
The Go-Git clone repository is different from the Git client clone repository, so you can try using the Go-Git clone repository

**Comment by timestee** [comment]
> 

got same issues inside a docker container running on Kubernetes.

**Comment by bluebrown** [comment]
Is someone willing to say something in this regard? Requiring the ssh agent is problematic for various reasons.

**Comment by scallister** [comment]
Adding a comment so stalebot removes its label.

**Comment by pjbgf** [comment]
@scallister can you please share a code sample and go-git version where you are experiencing the issue? A lot has changed since this issue was originally created, so I am not sure the same issue is occurring.

**Comment by scallister** [comment]
@pjbgf I wish I still had a code sample to share but I no longer have access to the problematic code that caused me to follow this issue initially.

From what I remember, I think the issue I encountered had to do with the ssh agent being required even when using an ssh key directly. I believe this caused problems because having the ssh agent available was not something we could expect.

**Comment by pjbgf** [comment]
@scallister thank you for the quick reply. I completely agree with the expectations there - users must be able to use SSH keys without having an ssh agent present. And also be able to rely on the ssh agent if they so wish.
The former use case [is working](https://github.com/fluxcd/pkg/blob/5387cf37fc07eb1df204613dd255223d2af1bcce/git/gogit/transport.go#L53-L85) in projects I know that depend on `go-git` - so not sure if this issue still exists or there is a specific edge case that causes a failure.

**Comment by scallister** [comment]
Perhaps we let stalebot mark this as stale the next time it triggers? Might give another individual reading this thread a chance to find a broken example or confirm a broken example is now working?

I’m also fine with you closing this out in the meantime too. Thanks for your follow up as well.

**Comment by pjbgf** [comment]
Thank you for understanding and for the quick replies. :bow: 

Overall, there are a lot of stale or duplicate issues, so let's close it for the time being. If anyone is still experiencing the issue and provide us a detailed report we can always reopen it.

**Comment by kimdre** [comment]
Hi, I I also stumbled upon this issue and I could not get it working regardless of what I tried. My current approach looks like the code below, but I always get the same error: 
`error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"`

I run my go code inside a distroless container image so there is no ssh-agent available.

```go
const RemoteName = "origin"

func CloneRepository(path, url, ref string, skipTLSVerify bool, proxyOpts transport.ProxyOptions, sshPrivateKey string) (*git.Repository, error) {
	err := os.MkdirAll(path, filesystem.PermDir)
	if err != nil {
		return nil, fmt.Errorf("failed to create directory %s: %w", path, err)
	}

	opts := &git.CloneOptions{
		RemoteName:      RemoteName,
		URL:             url,
		SingleBranch:    true,
		ReferenceName:   plumbing.ReferenceName(ref),
		Tags:            git.NoTags,
		InsecureSkipTLS: skipTLSVerify,
	}

	// SSH auth when key is provided
	if isSSH(url) {
		if strings.TrimSpace(sshPrivateKey) != "" {
			return nil, ErrSSHKeyRequired
		}

		opts.Auth, err = gitssh.NewPublicKeys("git", []byte(sshPrivateKey), "")
		if err != nil {
			return nil, fmt.Errorf("failed to create SSH public keys: %w", err)
		}
	}

	if proxyOpts != (transport.ProxyOptions{}) {
		opts.ProxyOptions = proxyOpts
	}

	return git.PlainClone(path, false, opts)
}
```

## Update:

I was finally able to fix the error by implementing a custom ssh-agent and a handler for the known_hosts file.
You can find the code here:
- https://github.com/kimdre/doco-cd/pull/897/changes#diff-bb74a4c50d1cd8924fdbd53a678130327b3d6ac94178bcb81cb57c8065c6421c
- https://github.com/kimdre/doco-cd/pull/897/changes#diff-f2ccd658cc31c4174c4567023b79f153c67b12371716cff1c97cc54c6d115e24
- https://github.com/kimdre/doco-cd/pull/897/changes#diff-4916998d9832575e2e2bd8f23267ab0a3e229b3c0de0cc24761331c69e80abcd
