### ISSUE TITLE
Repository.Resolution with short hash fails with repository opened by PlainOpen

### ISSUE THREAD

**Issue by sinozu** [go-git/go-git#148]
I tried to use the short hash resolution feature merged in https://github.com/go-git/go-git/pull/136.

When I clone the repository using `PlainClone`, short hash revision resolution succeed.
But short hash revision resolution failed with the repository opened by `PlainOpen`.
```
func main() {
	r, err := git.PlainClone("/tmp/foo", false, &git.CloneOptions{
		URL:      "https://github.com/go-git/go-git",
		Progress: os.Stdout,
	})
	if err != nil {
		log.Println(err.Error())
		return
	}
	// SUCCESS
	h, err := r.ResolveRevision("cded5b6")
	if err != nil {
		log.Println("ResolveRevision", err)
		return
	}
	log.Println(h)
	r, err = git.PlainOpen("/tmp/foo")
	if err != nil {
		log.Println(err.Error())
		return
	}
	// FAILED：reference not found
	h, err = r.ResolveRevision("cded5b6")
	if err != nil {
		log.Println("ResolveRevision", err)
		return
	}
	log.Println(h)
}
```

**Comment by mcuadros** [comment]
Maybe @dsymonds can help

**Comment by dsymonds** [comment]
Not sure what's happening there. I can only think it is taking a different code path, such as not using the index or searching for loose objects.

**Comment by sinozu** [comment]
@dsymonds 
When using `PlainClone`,  `WritePackfileToObjectStorage` is Called.
https://github.com/go-git/go-git/blob/2637279338ca9736c22b5e15fca916121ae8d089/plumbing/format/packfile/common.go#L45

Packfile is written to object storage. So I think, short hash revision resolution succeed.


When using `PlainOpen`, it seems that Packfile is not written.

**Comment by liiri** [comment]
Any workaround to have `ResolveRevision` work with short sha and an existing clone?

**Comment by didn0t** [comment]
Also having this issue with PlainClone - works with tags but not short hashes.

**Comment by didn0t** [comment]
I've noticed that this only appears to be a problem with the first call using a short hash and subsequent calls work.

I have therefore worked around this by adding:

	phash, _:= repo.ResolveRevision(plumbing.Revision("HEAD"))
	commit, _:= repo.CommitObject(*phash)
	tree, _:= commit.Tree()
	_ = tree

Using tags doesn't have this issue.  Apologies if the above code isn't idiomatic golang but it's my first attempt.

**Comment by liiri** [comment]
Thanks @didn0t it worked for me too :)

**Comment by iamnoah** [comment]
Hit this as well. I noticed that the short sha that failed was a merge commit 🤷‍♂️

The create a commit an read tree workaround works for me.

**Comment by jeremy-ebler-vineti** [comment]
Simply this worked for me:
```go
repo, _ := git.PlainOpen(path)
repo.ResolveRevision(plumbing.Revision("HEAD"))
```
I didn't need to grab the commit, tree, etc. Just resolving `HEAD` or a full hash after opening allowed short hashes to resolve later on.

**Comment by adg** [comment]
Just an update to say that the workarounds shared here only work if `HEAD` is in a packfile. If `HEAD` is among the `objects/xx/xxxxxxx...` directory hierarchy then the packfile indexes won't be read, and the workaround won't work.

A more reliable way is to attempt to resolve the zero hash:
```
repo, _ := git.PlainOpen(path)
repo.ResolveRevision(plumbing.Revision(plumbing.ZeroHash.String()))
```
