### ISSUE TITLE
Allow updating submodules with a depth of 1

### ISSUE THREAD

**Issue by bufdev** [go-git/go-git#15]
Similar to `git submodule update --init --depth 1`.

This would add `Depth` option to `SubmoduleUpdateOptions`, and `SubmoduleDepth` to `CloneOptions`.

Is this easy to do?

**Comment by mcuadros** [comment]
Should be very hard, it's a matter of passing the arguments

**Comment by bufdev** [comment]
Can you explain? I can also go through the code though.

Just to make sure it’s clear so I can plan accordingly: this won’t be worked on by the maintainers, or anyone at the company formed to back this project, right? If not, it’s fine, just need to know or our own development.

**Comment by bufdev** [comment]
Can't you just pass depth through to https://github.com/go-git/go-git/blob/8fddd7abcc436d77e9f7449a7b7aa15ee13f7c60/remote.go#L262 ?

**Comment by mcuadros** [comment]
Without digging a lot in the code, yes. This is was I was thinking.
Sorry about the late response

**Comment by bufdev** [comment]
Just to make sure it’s clear so I can plan accordingly: this won’t be worked on by the maintainers, or anyone at the company formed to back this project, right? If not, it’s fine, just need to know or our own development.

**Comment by mcuadros** [comment]
Nope, this feature was marked as `help wanted` so means is secure be taken by non-maintainers.

**Comment by bufdev** [comment]
Ah, perhaps this was misfunferstood:

- I won’t be sending a PR for this - I’m not familiar with the code was, and we don’t have time to help maintain go-git.
- Id expect something like this would be done by the maintainers, however the “help wanted” tag inferred this won’t be done by the maintainers (and you just confirmed this) 
- Therefore, we cant count on this feature to be added, so we will have to go a different direction.

**Comment by mcuadros** [comment]
Ok, it's a simple change, but we don't have time for this right now. But since it is labeled as `help wanted` maybe someone random takes care of it.

**Comment by bufdev** [comment]
In my experience, help wanted tags don’t usually yield contributions, for the record

**Comment by mcuadros** [comment]
> Indicates that a maintainer wants help on an issue or pull request

https://help.github.com/en/github/managing-your-work-on-github/about-labels

**Comment by bufdev** [comment]
Yes - perhaps you have a difference experience, in my experience with OSS however, I’ve never seen that help wanted label yield a contribution.

**Comment by bufdev** [comment]
Yes - however, in my experience, this is not an effective strategy to help maintain an OSS repository - I have used the labels myself on large OSS projects, and have never seen contributions, and others I know have the same experience.

However, I do wish go-git to best here - perhaps you will have a different experience, which is great! I would argue though that this will just yield unfixed issues, but I could be wrong.

**Comment by AriehSchneier** [comment]
@pjbgf Fixed by #754
