### ISSUE TITLE
Git clone github gist fails

### ISSUE THREAD

**Issue by 030** [go-git/go-git#156]
While git clone works for github repositories, both public and private, using the ssh example in this repository, it fails for github gists:

```
repository not found
reference not found
```

**Steps to reproduce**
* https://github.com/go-git/go-git/blob/master/_examples/clone/auth/ssh/main.go
* verify that a clone of a private github repository succeeds
* change the url to a gist, e.g. `git@gist.github.com:295af749c3f61b3e420a2b164ec407c4.git`
* the log should indicate that the `repository` and `reference` cannot be found

**Comment by 030** [comment]
/home/ben/go/pkg/mod/github.com/go-git/go-git/v5@v5.1.0/repository.go

The `remoteRefs, err := remote.fetch(ctx, o)` in this file returns an error. It seems that the gist.github does not include any refs.

`repository not found`

`reference not found`

**Comment by pjbgf** [comment]
Using the [ssh-agent example](https://github.com/go-git/go-git/pull/998) I could only reproduce this error when the known hosts was not properly populated.

For future reference, `github.com` known hosts entries won't work for `gist.github.com`.
