### ISSUE TITLE
SSH cloning returning "empty git-upload-pack given"

### ISSUE THREAD

**Issue by bmiller2807** [go-git/go-git#157]
I am not sure if this is an issue, bug , or lack of understanding, but, when im trying to clone a repo using ssh , i am recieving this error "empty git-upload-pack given". Any ideas why ? A snippet :

                          sshPath := privateKeyFile
			sshKey, _ := ioutil.ReadFile(sshPath)
			publicKey, keyError := ssh.NewPublicKeys(user, []byte(sshKey), password)
			if keyError != nil {
				fmt.Println(keyError)
			}

			repo, err = git.PlainClone(cloneDir, false, &git.CloneOptions{
				URL:               scanRequest.RepoURL,
				Progress:          os.Stdout,
				Auth:              publicKey,
				ReferenceName:     plumbing.ReferenceName(fmt.Sprintf("refs/heads/%s", scanRequest.Branch)),
				SingleBranch:      true,
				RecurseSubmodules: git.DefaultSubmoduleRecursionDepth,
			})
			if err != nil {
				fmt.Sprintf("%s %s %s", "07", "Clone failed: %s\n", err.Error())
				return
			}

**Comment by ChandlerSwift** [comment]
You don't happen to be cloning from Azure Devops do you? There's a known issue (they only implement the git v2 protocol -- https://github.com/go-git/go-git/issues/64) that seems to give the "empty git-upload-pack" error you've been seeing.

**Comment by bmiller2807** [comment]
Thank you @ChandlerSwift for the reply, hopefully this will be added soon.
