### ISSUE TITLE
[Example] How to cat-file from remote repository?

### ISSUE THREAD

**Issue by parasit** [go-git/go-git#16]
Hey,
According to the compatibility list, it is possible to make a `cat-file` on a remote repository, but I have looked at the documentation and partly the source code and I do not see such a possibility. Would it be possible to add an example of how to do it?

In one of the projects I have to search a large repository and fetch each branch to check the content of one file is very slow, and sometimes we get strange errors (e.g. local branches become damaged), so the best method seems to be `cat-file` but I would like to done from within code instead of calling git externally.

P.S. It's great that you continue the project!

**Comment by gandarez** [comment]
I also want to `cat-file` from a commit hash. Would it be possible?
