### ISSUE TITLE
How to set upstream?

### ISSUE THREAD

**Issue by strowk** [go-git/go-git#166]
In git CLI there's a command `branch`, which have an option `--set-upstream-to` to set the upstream of the branch. Is there something similar in this library? Could it be supported? 
Documentation https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md  says that `branch` command is supported completely, but I don't understand how to set upstream using library.

**Comment by mcolburn** [comment]
I have the same question.

**Comment by shanestarcher-okta** [comment]
@riyaz-ali this looks to work for master, but how would I do this for non-master.  Like say track against an upstream of the same branch name as local?  I'm looking through the code, but I'm missing something.

**Comment by Charnnarong** [comment]
I also want to achieve the similar result to your question. After cloned a project from an existing repository, I want to create a new repository for it and push it to the newly create repo, but also keeping track of the upstream.

Here is what I did. It will goes and modified a project's `.git/config` file

```golang

        targetURL := fmt.Sprintf("https://github.com/< git user >/%s.git",website)
	r, err := git.PlainOpen(directory)
	CheckIfError(err)

	//git remote add upstream https://github.com/< git user >/< repo name >.git
	currentConfig ,err := r.Config()
	if err != nil {
		log.Fatalln(err)
	}

	// set upstream.
	currentConfig.Remotes["upstream"] = &config.RemoteConfig{
		Name:  "upstream",
		URLs:  []string{"https://github.com/< git user >/< repo name >.git"},
		Fetch: []config.RefSpec{"+refs/heads/*:refs/remotes/upstream/*"},
	}
	currentOrigin := currentConfig.Remotes["origin"]
	currentOrigin.URLs[0] = targetURL
	currentConfig.Remotes["origin"] = currentOrigin
	currentBranch := currentConfig.Branches["main"]
	currentBranch.Remote = "upstream"

	r.SetConfig(currentConfig)

	err = r.Fetch(&git.FetchOptions{
		RemoteName:      "upstream",
		Auth:            &gitHttp.BasicAuth{
			Username: user,
			Password: token,
		},
	})
	if err != nil && !errors.Is(err,git.NoErrAlreadyUpToDate) {
		log.Fatalln(err)
	}

```

**Comment by jiminychris** [comment]
This is what I did to set the upstream tracking reference for a feature branch:
```
repo, _ := git.PlainOpen(path)
repoConf, _ := repo.Config()
repoConf.Branches[branchName] = &config.Branch{
	Name: branchName,
	Remote: "origin",
	Merge: plumbing.ReferenceName("refs/heads/" + branchName),
}
repo.SetConfig(repoConf)
```
