### ISSUE TITLE
Push with Prune does not achieve the desired effect

### ISSUE THREAD

**Issue by petergardfjall** [go-git/go-git#172]
I'm unsure at this point if I've encountered a bug or not, but I'm seeing some inconsistencies between go-git's `PushContext` and command-line `git` and wanted to ask for some guidance.

I have a scenario where I have an `upstream` remote that I want to "mirror" to my `origin` remote.
That is, I want push every `<upstream>/<branch>` to `<origin>/<branch>` and remove any `origin` branches without an `<upstream>/<branch>` counterpart.

I belive I've achieved something to that effect using the following command with command-line `git`:

    git push --force --prune fork +refs/remotes/upstream/*:refs/heads/*

This works as intended.

Now, when I try to achieve the same thing using go-git

```
	err = repo.PushContext(ctx, &git.PushOptions{
		RemoteName: "origin",
		Auth:       auth,
		Prune:      true,
		Force: true,
		RefSpecs: []config.RefSpec{
			"+refs/remotes/upstream/*:refs/heads/*",
		},
	})
```

The operation fails with a response like `command error on refs/heads/master: pre-receive hook declined` (I use Gitea as backend). Judging by the logs it appears like the `PushContext` call tries to delete `origin/master` which is refused since it's the default branch. Now, the equivalent (?) `git` call above does not produce such an error but achieves the desired effect.

Am I doing some obvious mistake or is the behavior buggy in some sense?

**Comment by agherzan** [comment]
@petergardfjall have you ever managed to figure this one out? I face something very similar.

**Comment by petergardfjall** [comment]
> @petergardfjall have you ever managed to figure this one out? I face something very similar.

Sorry, no.

**Comment by agherzan** [comment]
Not great - and the lack of feedback is not encouraging either. I think that the issue I raised last week is very similar to this if not identical. https://github.com/go-git/go-git/issues/520

**Comment by pjbgf** [comment]
@coding-devops feel free to propose a PR a tag me for review.
