### ISSUE TITLE
File Status (Added, Deleted, Modified) Question

### ISSUE THREAD

**Issue by reaandrew** [go-git/go-git#176]
Is there a way to retrieve the status of each file for a commit i.e. whether it is Added, Deleted, Modified.  I can see the Status type in the code base but I cannot see this in the context of a file and commit.

**Comment by WKBae** [comment]
```go
commit, _ := repo.CommitObject(...)
parent, _ := commit.Parent(0)
t1, _ := parent.Tree()
t2, _ := commit.Tree()
changes, _ := t1.Diff(t2)
for _, change := range changes {
    action, _ := change.Action() // one of merkletrie.Insert, Delete, Modify
}
```
You can find the diff between two commits (parent commit in this context) this way.
