### ISSUE TITLE
[Ask] How to get latest commit log of a path

### ISSUE THREAD

**Issue by neel1996** [go-git/go-git#188]
I am trying to obtain the latest commit log for a folder in a target and it looks like the approach I am trying is working only for files and not for directories. 

The git command equivalent I am trying to achieve is `git log -- some_folder/`

```
// fileList has the list of files and directories from the repo
for _, file := range fileList {
	commitItr, _ := repo.Log(&git.LogOptions{
		From:     hash, // hash of the HEAD 
		FileName: file, // the file or dir name
		All:      false,
	})
	if commit, _ := commitItr.Next(); commit != nil {
                // just printing the file and the respective commit message 
		logger.Log(fmt.Sprintf("%s -- %s", *file, strings.Split(commit.Message, "\n")[0]), global.StatusInfo)
	}
	commitItr.Close()
}
```

The above code works fine for files but not for a directory from the repo. 

Is there a way to get the latest commit log info from both files and folders in a target repo ?

**Comment by robalvsan** [comment]
Git just track files, but no folders.

**Comment by neel1996** [comment]
Hi @robalvsan 

I have been using this with the native git commands `git log -- directory_name` which returns the expected result and I believe go-git also has a way of doing the same. The problem is that, I am not able to get the required results for directories even using the new `PathFilter` in the `LogOptions`

**Comment by yorchperaza** [comment]
@neel1996 can confirm if `git log -p <path to directory>` is what you want?

**Comment by neel1996** [comment]
@yorchperaza I was looking for something similar to `git log .. <path>`. I found a way using go-git itself. 

The code can be found here --> https://github.com/neel1996/gitconvex-go-server/blob/b11513aee29f2dd95219919ae0196d6af9a2fc04/git/git_ls_files.go#L34

Closing the issue
