### ISSUE TITLE
filesystem/dotgit, receive-pack: Unable to resolve refs in thin packs

### ISSUE THREAD

**Issue by WKBae** [go-git/go-git#190]
I see that the server implementation is currently incomplete. Leaving this for a note while experimenting server logics.

## What happened
`plumbing/transport/server.(*rpSession).ReceivePack()` fails with `reference delta not found` if packfile referencing external objects("thin pack") is received.
The referenced object exists on the target repository. Current `filesystem/dotgit.(*PackWriter)`  implementation blocks finding external references and parsing thin packs.

## Why did it happen
`ReceivePack()` writes packfile to storage, calling `packfile.UpdateObjectStorage()`.
https://github.com/go-git/go-git/blob/15aedd2ff43c25e0d54d6b488114725a266c79d0/plumbing/transport/server/server.go#L303

Then `filesystem/dotgit.(*packWriter)` is initiated and parses received packfile on separate goroutine, creating `packfile.Parser` with no reference to local storage. This causes packfiles with `ExternalRef` to raise `ErrReferenceDeltaNotFound`
https://github.com/go-git/go-git/blob/15aedd2ff43c25e0d54d6b488114725a266c79d0/storage/filesystem/dotgit/writers.go#L53-L61

## Temporary workaround
By commenting out following `storer.PackfileWriter` code path, the packfile is parsed successfully. The received packfile is unpacked on the fly using the storage *s*.
https://github.com/go-git/go-git/blob/15aedd2ff43c25e0d54d6b488114725a266c79d0/plumbing/format/packfile/common.go#L29-L34

**Comment by riyaz-ali** [comment]
Alternatively, as a workaround (if you don't want to modify the library source), you could also specify [`no-thin` capability](https://github.com/git/git/blob/f9b6481aedae587b1380736fb8f21785119aeb48/Documentation/technical/protocol-capabilities.txt#L111-L114) when advertising references from the server.

**Comment by prologic** [comment]
Anyone working on a fix for this? 🤔

**Comment by pjbgf** [comment]
Can you please try again? I think this was resolved by https://github.com/go-git/go-git/pull/485.
