### ISSUE TITLE
invalid tree object can be produced

### ISSUE THREAD

**Issue by MichaelMure** [go-git/go-git#193]
Found that out after running `git fsck` on a repo where I've been using go-git (through git-bug):
> $ git fsck 
> erreur dans l'objet tree ac67188617b481887f55414af55b02631deaf5b9 : treeNotSorted: not properly sorted

Turns out that tree entries need to be sorted when serialized. Beware thought, it's a slightly peculiar order: https://github.com/isomorphic-git/isomorphic-git/pull/937

I would assume that it would be go-git's reponsibility to ensure valid stored data.

**Comment by itsanpach** [comment]
Hey, it's Ann! I'm having problems keeping new emails now. Please
Note, I am prioritizing time the best I can on a phone. Thanks beyond words for the help.

**Comment by MichaelMure** [comment]
FYI, this is what I used as a workaround. It uses my own struct instead of `object.TreeEntry` but you should get the idea.
```go
sort.Slice(sorted, func(i, j int) bool {
	nameI := sorted[i].Name
	if sorted[i].ObjectType == Tree {
		nameI += "/"
	}
	nameJ := sorted[j].Name
	if sorted[j].ObjectType == Tree {
		nameJ += "/"
	}
	return nameI < nameJ
})
```

**Comment by pjbgf** [comment]
Fixed by https://github.com/go-git/go-git/pull/967.
