### ISSUE TITLE
Unable to run in Docker containers

### ISSUE THREAD

**Issue by akamensky** [go-git/go-git#194]
Using `v5.2.0` when trying to run binary inside Docker container it results in:

```
exec: "getent": executable file not found in $PATH
```

**Comment by stoney27** [comment]
@akamensky Did you ever figure out your issue with running a go-git program in a container?  I am running into an issue when I try pushing changes.  They are added, but the go-git code does not think there are any changes to push.  The code works when I add git to the container and set the "user.name" and "user.email," the code work.  I am setting those in the git.CommitOptions.

Thanks.
-S

**Comment by akamensky** [comment]
@stoney27 No, we ended up installing git cli inside image and running that as subprocess.
