### ISSUE TITLE
[ASK] Remove staged files 

### ISSUE THREAD

**Issue by neel1996** [go-git/go-git#206]
I have been trying to achieve a behavior similar to `git reset <file_name>` which removes a selected item from the staging. I tried using the `Remove()` function from `Worktree`, but it removes the file completely from the worktree and the index. In other words, instead of performing a reset, it deletes the file.

Is there any way to remove selective files from the staging area?

**Comment by gibchikafa** [comment]
Hi! Did you find a solution to this?

**Comment by neel1996** [comment]
@gibchikafa I basically removed the file and re-wrote the index. Then I picked the HEAD commit and reset the repo to that commit for the specific pathspec alone. 

Here's the code - https://github.com/neel1996/gitconvex-server/blob/main/git/git_reset_item.go
