### ISSUE TITLE
[help-wanted] Modifying a commit (amend)

### ISSUE THREAD

**Issue by b4nst** [go-git/go-git#209]
Hello there, 

I'm having a hard time trying to amend a commit with `go-git` plumbing. I lack xp on low-level operations. Right now I've tried to override the `EncodedObject` but with no success.

```go
// c is my commit object and r the repository
obj, _ := r.Storer.EncodedObject(plumbing.CommitObject, c.Hash)
c.Message = "amended"
c.Encode(obj)
r.Storer.SetEncodedObject(obj)
// Reading the object to debug
ro, _ := obj.Reader()
defer ro.Close()
fo, _ := ioutil.ReadAll(ro)
fmt.Println("START")
fmt.Println(string(fo))
fmt.Println("END")

// START
// tree 66aa0a0d6a85a45a8c56ffa3c115a8b83fba4ff8
// author banst <redacted> 1557822982 +0200
// committer banst <redacted> 1557822982 +0200

// first commit
// tree 66aa0a0d6a85a45a8c56ffa3c115a8b83fba4ff8
// author banst <redacted> 1557822982 +0200
// committer banst <redacted> 1557822982 +0200

// amended
// END
```

_please excuse the dirty error ignore, that's obviously not production code_

As you can see `c.Encode(obj)` seems to append the modification instead of overwriting it, so I suppose the issue lays somewhere nearby. Can somebody guides me on how to achieve this properly please?

**Comment by stoney27** [comment]
Hi b4nst,
Did you ever get this working?  I am looking to do something similar.  I am trying to amend a commit to a Gerrit instance.

Thanks,
-S

**Comment by b4nst** [comment]
Sadly not

**Comment by unkaktus** [comment]
I am also interested in having it working.
Did someone had any luck with it?

**Comment by pjbgf** [comment]
What changes were you trying to make? Just commit message or also change the files in commit?

**Comment by b4nst** [comment]
@pjbgf From what I recall, both

**Comment by pjbgf** [comment]
@b4nst you should be able to do that by creating a new commit, linking to the same parents, effectively replacing the previous commit.

Based on `_examples` style:

```go
	// Open the repository
	repo, err := git.PlainOpen("/path/to/repo")
	CheckIfError(err)

	// Get the HEAD reference
	ref, err := repo.Head()
	CheckIfError(err)

	// Get the commit to be amended
	commit, err := repo.CommitObject(ref.Hash())
	CheckIfError(err)

	// Print previous commit
	fmt.Println(commit)

	wt, err := repo.Worktree()
	CheckIfError(err)

	_, err = wt.Add("new_file")
	CheckIfError(err)

	_, err = wt.Commit("new commit message", &git.CommitOptions{
		Parents: commit.ParentHashes,
	})
	CheckIfError(err)

	ref, err = repo.Head()
	CheckIfError(err)

	commit, err = repo.CommitObject(ref.Hash())
	CheckIfError(err)

	// Print new commit
	fmt.Println(commit)
```
