### ISSUE TITLE
How to get current tag name?

### ISSUE THREAD

**Issue by glothriel** [go-git/go-git#211]
Hi. I can't obtain current tag name. For branch it's easy:
```
        head, headErr := repo.Head()
	if headErr != nil {
		return "", pkgErrors.Wrap(headErr, errWrapMsg)
	}
	if head.Name().IsBranch() {
		return strings.TrimPrefix(head.Name().String(), "refs/heads/"), nil
	}
```

But for a tag `head.Name()` returns just `HEAD`.

The only way I was able to do this was to get current HEAD's commit and compare it against a list of all tags, like:
```
       forEachErr := tags.ForEach(func(t *plumbing.Reference) error {
		if t.Hash() == head.Hash() {
			tagName = strings.TrimPrefix(t.Name().String(), "refs/tags/")
		}
		return nil
	})
	if forEachErr != nil {
		return "", forEachErr
	}
	var tagErr error
	if tagName == "" {
		tagErr = fmt.Errorf("Could not find tag name for %s", head.Hash().String())
	}
	return tagName, tagErr
```

but this will not work if I have two tags pointing at one commit. Anyone knows how to reliably get current repo's active tag?

**Comment by TheApeMachine** [comment]
I do something like below, seems to work for me.

```go
tagrefs, _ := repo.Tags()
var lasttag string

tagrefs.ForEach(func(t *plumbing.Reference) error {
    lasttag = string(t.Name())
    return nil
})
```

**Comment by magnusbaeck** [comment]
> Anyone knows how to reliably get current repo's active tag?

Git doesn't have the concept of an "active tag". If you check out a tag you end up with a detached head.

**Comment by pjbgf** [comment]
> I do something like below, seems to work for me.

```golang
tagrefs, _ := repo.Tags()
var lasttag string

tagrefs.ForEach(func(t *plumbing.Reference) error {
    lasttag = string(t.Name())
    return nil
})
```

On the example above, this will probably just return the last created tag. It does not confirm that the tag is pointing to the current branch's `HEAD` AFAIK. For that, users could either use the same example and use `t.Hash()` or `t.Target()` to compare against the `HEAD` (or its parent commits).
