### ISSUE TITLE
limit in memory store

### ISSUE THREAD

**Issue by aep** [go-git/go-git#215]
It would be useful if the in memory store could be limited to a maximum amount of bytes,
so that it can be safely run on untrusted user input (otherwise they can OOM your stuff by just giving it an oversized repo)

**Comment by maxless** [comment]
Well, two years have passed. Are there any options or maybe workarounds to limit max repo size when accessed by go-git currently? Maybe there's some way of getting the repo size in bytes beforehand?

**Comment by HarikrishnanBalagopal** [comment]
> Maybe there's some way of getting the repo size in bytes beforehand?

https://stackoverflow.com/a/8679592
The GitHub API does provide a `size`, but this may not apply to GitLab, BitBucket, GitHub enterprise, bare repos on personal servers, etc.
