### ISSUE TITLE
Invalid capabilities: Arguments not allowed

### ISSUE THREAD

**Issue by rofc** [go-git/go-git#220]
I started getting the following error on Dec 4 11am (EST):

> pkt-line 1: invalid capabilities: arguments not allowed (multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want symref=HEAD:refs/heads/master filter object-format=sha1 agent=git/github-g574413c1f267)

I found a github changes related [issue](https://github.com/src-d/go-git/issues/450), fix [here](https://github.com/src-d/go-git/pull/451). Can you confirm this? Thank you in advance!

**Comment by nnarh** [comment]
@rofc  I am also getting the same error with an older library + basic auth with a personal access token
