### ISSUE TITLE
cannot use memory.NewStorage() (value of type *memory.Storage) as storage.Storer value

### ISSUE THREAD

**Issue by ashtyn3** [go-git/go-git#236]
I was trying to use one of the examples in the README and it won't build because of this error ` ../../../pkg/mod/github.com/go-git/go-git@v4.7.0+incompatible/storage/memory/storage.go:304:3: cannot use m (type *Storage) as type storage.Storer in return argument:
        *Storage does not implement storage.Storer (missing EncodedObjectSize method)`. I don't really know how to fix it. I looked online and no one else seems to be having this issue so I thought I should come to the source. Here is my code:
```golang
r, err := git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
    URL: "https://github.com/go-git/go-billy",
})
```
If anyone knows how this can be fixed that would be greatly appreciated!
Thank you.

**Comment by supernova2468** [comment]
Had the same problem. The go dev tools often add this import after you have run go get.
```
"github.com/go-git/go-git/storage/memory"
```

but per the example it looks like you need to specify v5

```
"github.com/go-git/go-git/v5/storage/memory"
```

source: https://github.com/go-git/go-git/blob/master/_examples/log/main.go

**Comment by ashtyn3** [comment]
> Had the same problem. The go dev tools often add this import after you have run go get.
> 
> ```
> "github.com/go-git/go-git/storage/memory"
> ```
> 
> but per the example it looks like you need to specify v5
> 
> ```
> "github.com/go-git/go-git/v5/storage/memory"
> ```
> 
> The readme doesn't show that.
> 
> source: https://github.com/go-git/go-git/blob/master/_examples/log/main.go

Thank you so much!

**Comment by ashtyn3** [comment]
Thank you so much!

**Comment by kossmar** [comment]
our hero!
