### ISSUE TITLE
worktree.checkout of local available branch takes 10 seconds or more

### ISSUE THREAD

**Issue by EugenMayer** [go-git/go-git#238]
I have a local repository, which i load using `plainOpen` and then use 

```golang
	repository, err := gitlib.PlainOpen(path)
	if err != nil {
		return nil, err
	}

	return repository, nil
```

```golang
        branch, err := repository.Branch(branchName)
	if err != nil {
		return err
	}

	worktree, err := repository.Worktree()
	if err != nil {
		return err
	}

	err = worktree.Checkout(&gitlib.CheckoutOptions{Branch: branch.Merge})
	return err
```

This operations takes more then 10 seconds. Debugging the code it turns out the problematic code is

```golang
unstaged, err := w.containsUnstagedChanges()
```

Why is this so slow and can i force to skip it (since i know my worktree is clean).

For me, that is really critical and would make the library basically useless ;/

**Comment by moorara** [comment]
I'm not sure why you're using `branch.Merge` when checking out.
You should be able to checkout to a branch as follows:

```go
worktree, err := repo.Worktree()
if err != nil {
	return err
}

branchRef := plumbing. NewBranchReferenceName(branchName)
opts := &git.CheckoutOptions{Branch: branchRef}
if err := worktree.Checkout(branchRef); err != nil {
	return err
}
```

**Comment by EugenMayer** [comment]
How is that any different to what i have up there? This is the exact same logic IMHO.

I mean the way we get the reference does not really make any difference. I fetch it from the repository, you just construct it 'dry'.
The code you have up there will trigger the exact same strategy in `Checkout` and therefore the problematic/slow code, since the default of `resetOptions` is

```
ro := &ResetOptions{Commit: c, Mode: MergeReset}
```

In `Checkout`. It is nothing i have chosen (`ModeReset`), it is the default. And since you did not use `Force` or `Keep` in your code above, you will end up with the exact same default.

And that is what most of use will do, the code looks perfectly fine. The only reason this is slow is, because we check for an unclean working tree, and that is just very slow compared to whatever is done in the git binary. An entire tree is build, not sure how efficient, but i guess with the number of files, maybe also history resize, this will become an issue.

**Comment by EugenMayer** [comment]
Tried git2go with the same strategy, it completes instantly, so below 20ms.

I would still see this as an implementation issue in go-git which we might need to address? I think branch-checkout would be one of those basic operations, so maybe this is not to low of importance.

**Comment by EugenMayer** [comment]
Just in case somebody needs a workarround, just use `Keep: true`

```golang
err = worktree.Checkout(&gitlib.CheckoutOptions{Branch: branch.Merge, Keep: true})
```

To avoid the performance issue for now and be on the safe side ( soft reset )

**Comment by EugenMayer** [comment]
A final update, `Keep: true` does not really lead to anything useful here, i gave up using go-git for checking out the branch. I just use it to create a remote tracking branch, if needed, and the i use a shell based `git swtich` for the actual branch switch.

Not using git2go due it's OS dependencies and build dependencies overcomplicate transportability /crossplatform.

**Comment by SpangleLabs** [comment]
I'm also encountering this performance issue. I'm using `Force: True`, and it takes many many minutes to switch to an old branch (branches 1.5 years ago in a busy organisation, 60k commits between them).
Using `git switch` takes somewhere around 12 seconds, but after 10 minutes of waiting for `Worktree.Checkout()`, I gave up and killed the process.

This is not really usable in the current state.
