### ISSUE TITLE
'git.PlainOpenWithOptions' does not consider worktree option from .git/config

### ISSUE THREAD

**Issue by jsattler** [go-git/go-git#239]
When initializing an empty repository and changing the worktree option to some other directory, the function 'git.PlainOpenWithOptions' does not consider the specified worktree option under .git/config.

I expected that the worktree option under .git/config is considered when opening the Repository.
I could not find any option or configuration to open the repository with the configured worktree under .git/config.

**Comment by nscnd** [comment]
Hey there,
I'm facing the same issue using `git.PlainOpenWithOptions` on a worktree fails to open the repo.
In that case, no `.git` dir but a `.git` file with `gitdir: /x/y/z `.
I think that it is expected that when running on a worktree we could still open the repo without knowing in advance this is not a fully fledge git repo.
Shouldn't we add an option to handle this case as there is an option to find the 'parent' git repo ?
Or maybe there already is a way to do this I didn't see ?
