### ISSUE TITLE
Checkout remote branch to a local (tracked banch)

### ISSUE THREAD

**Issue by EugenMayer** [go-git/go-git#241]
Looked through the issues and seen some similar questions, but iam not sure i found the right one.

If found: 
 - https://github.com/go-git/go-git/issues/166#issuecomment-703671117
 - https://github.com/go-git/go-git/issues/100

What i want is, i want to checkout a branch i know exists, but it could be, that it is yet not a local branch. Checking out local branches is easy ( so basically rather `git switch` ) but checking out remote branches seems to not work:

```
branch not found
```

```golang
  func CheckoutBranch(repository *gitlib.Repository, branchName string) error {
	localBranchLookup, err := repository.Branch(branchName)
	var branchRef plumbing.ReferenceName
	if err != nil {
		fmt.Print("Branch is not yet local, trying to fetch from remote")
		branchRef = plumbing.NewBranchReferenceName(branchName)
	} else {
		branchRef = localBranchLookup.Merge
	}

	worktree, err := repository.Worktree()
	if err != nil {
		return err
	}

	// Keep: true is important for performance reasons, to avoid vendor/github.com/go-git/go-git/v5/worktree.go:409
	// being called by reset, taking 10 seconds and more
	return worktree.Checkout(&gitlib.CheckoutOptions{Branch: branchRef, Keep: true})
}
```

`worktree.Checkout` fails with 

```
reference not found
```

According to the issue i found i changed it to

```golang
func CheckoutBranch(repository *gitlib.Repository, branchName string) error {
	//
	//err = fetch(repository)
	//if err != nil {
	//	return err
	//}

	localBranchLookup, err := repository.Branch(branchName)
	if err != nil {
		fmt.Println("Branch is not yet local, trying to fetch from remoteName")
		remoteName := "origin"
		var remoteRef = plumbing.NewRemoteReferenceName(remoteName, branchName)
		var ref, err = repository.Reference(remoteRef, true)
		if err != nil {
			return err
		}

		var mergeRef = plumbing.ReferenceName(fmt.Sprintf("refs/heads/%s", branchName))
		err = repository.CreateBranch(&config.Branch{Name: branchName, Remote: remoteName, Merge: mergeRef})
		if err != nil {
			return err
		}
		var localRef = plumbing.ReferenceName(fmt.Sprintf("refs/heads/%s", branchName))
		return repository.Storer.SetReference(plumbing.NewHashReference(localRef, ref.Hash()))
	} else {
		localBranchRef := localBranchLookup.Merge
		worktree, err := repository.Worktree()
		if err != nil {
			return err
		}

		// Keep: true is important for performance reasons, to avoid vendor/github.com/go-git/go-git/v5/worktree.go:409
		// being called by reset, taking 10 seconds and more
		return worktree.Checkout(&gitlib.CheckoutOptions{Branch: localBranchRef, Keep: true})
	}
}
```

But got the same issue, just it happens at

```
var ref, err = repository.Reference(remoteRef, true)
if err != nil {
  return err
}
```

Wit again, `reference not found`.

What is the right way to do this? I cannot implement fetch due to #240, but if i do a manual `git fetch -a` on the repo beforehand, it should be the same result. Still it fails with `reference not found`

Thankful for any help

**Comment by dc-wc-2017** [comment]
my code is like this :


    repo, err := git.PlainClone(repoDir, false, &git.CloneOptions{
        Auth: &githttp.BasicAuth{
            Username: authenticateUser,
            Password: authenticateToken,
        },
        URL: repoUrl,
    })

    if err != nil {
        if err != git.ErrRepositoryAlreadyExists {
            mylog.LogFatalExitByCheckingError(err)
        }
        fmt.Printf("Checked error: %v\n", err)
        // open this repository instead
        repo, err = git.PlainOpen(repoDir)
        mylog.LogFatalExitByCheckingError(err)
    }

    // refs/heads/<localBranchName>
    localBranchReferenceName := plumbing.NewBranchReferenceName(branchName)
    // refs/remotes/origin/<remoteBranchName>
    remoteReferenceName := plumbing.NewRemoteReferenceName("origin", branchName)

    err := repo.CreateBranch(&config.Branch{Name: branchName, Remote: "origin", Merge: localBranchReferenceName })
    newReference := plumbing.NewSymbolicReference(localBranchReferenceName , remoteReferenceName)
    err = repo.Storer.SetReference(newReference)
    mylog.LogPanicByCheckingError(err)

**Comment by EugenMayer** [comment]
Thank you, this worked! Even though i fall back to checking out the branch on using the cli due to #238 creating a remote tracking branch this way works out fairly well.

**Comment by Ileriayo** [comment]
Tried this, and it moves folders from one branch to the other, howbeit empty.
