### ISSUE TITLE
Error with single branch clone with non-master default branch

### ISSUE THREAD

**Issue by hairyhenderson** [go-git/go-git#249]
[All new GitHub repos][1] are created with a default branch of `main`, instead of the older `master`.

If I try to clone such a repo with the `SingleBranch` option enabled, I see an error like `couldn't find remote ref "refs/heads/master"`.

This code demonstrates the issue (the repo https://github.com/hairyhenderson/hitron_coda.git has a default branch of `main`):

```go
package main

import (
	"fmt"

	"github.com/go-git/go-billy/v5/memfs"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/storage/memory"
)

func main() {
	fs := memfs.New()
	storer := memory.NewStorage()

	opts := &git.CloneOptions{
		URL:          "https://github.com/hairyhenderson/hitron_coda.git",
		SingleBranch: true,
	}

	_, err := git.Clone(storer, fs, opts)
	if err != nil {
		fmt.Println(err)
	}
}
```

```console
$ go run main.go
couldn't find remote ref "refs/heads/master"
```

If I set `SingleBranch` to `false` it succeeds, but this isn't desirable for my use-case since I want to minimize what I'm pulling down.

The issue seems rooted in [this code](https://github.com/go-git/go-git/blob/v5.2.0/repository.go#L923), which defaults to the [`plumbing.Master`](https://github.com/go-git/go-git/blob/v5.2.0/plumbing/reference.go#L128) constant when `SingleBranch` is `true` and `ReferenceName` defaults to `HEAD`.

[1]: https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

**Comment by sauravhaloi** [comment]
With GitHub making the default branch as `main`, the library errors out during cloning a GitHub repositories where default branch is not `master`. Even BitBucket has also come up with an option to have the default branch other than `master`.  This is mostly due to the constant definition https://github.com/go-git/go-git/blob/024d62b96ac19b40473f04931f9c12c8e24e0f7a/plumbing/reference.go#L128 which is used during a repository and submodule init.

A way to fix this might require changing the signature of the Init() function in repository.go, where it should be possible to pass the default branch name during repository initialization. A reference implementation diff is shown below:

```
$ git diff
diff --git a/options.go b/options.go
index 507fc07..4b08933 100644
--- a/options.go
+++ b/options.go
@@ -33,6 +33,22 @@ var (
        ErrMissingURL = errors.New("URL field is required")
 )
 
+// InitOptions describes how a bare repository should be initialized
+type InitOptions struct {
+       // Remote reference name to use during repo initialization
+       ReferenceName plumbing.ReferenceName
+}
+
+// Validate validates the fields and sets the default values.
+func (o *InitOptions) Validate() error {
+
+       if o.ReferenceName == "" {
+               o.ReferenceName = plumbing.Master
+       }
+
+       return nil
+}
+
 // CloneOptions describes how a clone should be performed.
 type CloneOptions struct {
        // The (possibly remote) repository URL to clone from.
diff --git a/repository.go b/repository.go
index cc487d4..378d345 100644
--- a/repository.go
+++ b/repository.go
@@ -72,7 +72,7 @@ type Repository struct {
 // Init creates an empty git repository, based on the given Storer and worktree.
 // The worktree Filesystem is optional, if nil a bare repository is created. If
 // the given storer is not empty ErrRepositoryAlreadyExists is returned
-func Init(s storage.Storer, worktree billy.Filesystem) (*Repository, error) {
+func Init(s storage.Storer, worktree billy.Filesystem, o *InitOptions) (*Repository, error) {
        if err := initStorer(s); err != nil {
diff --git a/options.go b/options.go
index 507fc07..4b08933 100644
--- a/options.go
+++ b/options.go
@@ -33,6 +33,22 @@ var (
        ErrMissingURL = errors.New("URL field is required")
 )
 
+// InitOptions describes how a bare repository should be initialized
+type InitOptions struct {
+       // Remote reference name to use during repo initialization
+       ReferenceName plumbing.ReferenceName
+}
+
+// Validate validates the fields and sets the default values.
+func (o *InitOptions) Validate() error {
+
+       if o.ReferenceName == "" {
+               o.ReferenceName = plumbing.Master
+       }
+
+       return nil
+}
+
 // CloneOptions describes how a clone should be performed.
 type CloneOptions struct {
        // The (possibly remote) repository URL to clone from.
diff --git a/repository.go b/repository.go
index cc487d4..378d345 100644
--- a/repository.go
+++ b/repository.go
@@ -72,7 +72,7 @@ type Repository struct {
 // Init creates an empty git repository, based on the given Storer and worktree.
 // The worktree Filesystem is optional, if nil a bare repository is created. If
 // the given storer is not empty ErrRepositoryAlreadyExists is returned
-func Init(s storage.Storer, worktree billy.Filesystem) (*Repository, error) {
+func Init(s storage.Storer, worktree billy.Filesystem, o *InitOptions) (*Repository, error) {
        if err := initStorer(s); err != nil {
                return nil, err
        }
@@ -87,7 +87,11 @@ func Init(s storage.Storer, worktree billy.Filesystem) (*Repository, error) {
                return nil, err
        }
 
-       h := plumbing.NewSymbolicReference(plumbing.HEAD, plumbing.Master)
+       if o.ReferenceName == "" {
+               o.ReferenceName = plumbing.Master
+       }
+
+       h := plumbing.NewSymbolicReference(plumbing.HEAD, o.ReferenceName)
        if err := s.SetReference(h); err != nil {
                return nil, err
        }
```
@mcuadros @jfontan Can you please pour in your thoughts on this?

**Comment by jfontan** [comment]
I have to think which is the best way to solve the problem but meanwhile you can query the `HEAD` reference of the repository and download the target. Here's the example modified to do that:

```go
package main

import (
	"fmt"
	"os"

	"github.com/go-git/go-billy/v5/memfs"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/transport"
	"github.com/go-git/go-git/v5/plumbing/transport/client"
	"github.com/go-git/go-git/v5/storage/memory"
)

func main() {
	url := "https://github.com/hairyhenderson/hitron_coda.git"
	e, err := transport.NewEndpoint(url)
	checkErr(err)

	cli, err := client.NewClient(e)
	checkErr(err)

	s, err := cli.NewUploadPackSession(e, nil)
	checkErr(err)

	info, err := s.AdvertisedReferences()
	checkErr(err)

	refs, err := info.AllReferences()
	checkErr(err)

	headReference := refs["HEAD"].Target()

	fs := memfs.New()
	storer := memory.NewStorage()

	opts := &git.CloneOptions{
		URL:           "https://github.com/hairyhenderson/hitron_coda.git",
		SingleBranch:  true,
		ReferenceName: headReference,
	}

	_, err = git.Clone(storer, fs, opts)
	if err != nil {
		fmt.Println(err)
	}
}

func checkErr(err error) {
	if err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
}
```

**Comment by sauravhaloi** [comment]
Thanks @jfontan. To get away with the default `master` branch initialization by the `storer`, we would somehow need to pass this info about the remote `HEAD` of the repository to the `Init` method in `repository.go`. Since auth is not available inside `Init`, which if available would help us in determining the remote `HEAD` using the solution you mentioned. So the only way we could do this is to pass the info as an argument. We could change the signature of the `Init` method to accommodate this. Do you think this will be acceptable?  If so, I can open a PR for this. The spread of the `Init` method is not big. Its called by repository clone and from submodule's method.

**Comment by hairyhenderson** [comment]
Also worth noting #269, which seems related...

@jfontan have you been able to determine a good way to handle this?

I ran into this again working on [go-fsimpl](https://github.com/hairyhenderson/go-fsimpl), after having forgotten about it... I may be able to work around it with the method above.

**Comment by mkungla** [comment]
`plumbing.Master` should be configurable like `git config --global init.defaultBranch main`

**Comment by umbellate** [comment]
This is really a pain in the ass.
