### ISSUE TITLE
plumbing/object: add a chronological commit iterator

### ISSUE THREAD

**Issue by mvdan** [go-git/go-git#25]
I upstreamed a "post order" iterator a while ago, under the assumption that it was what `git log` does by default. That's wrong :) In particular, I mistakenly assumed that post-order would equal chronological order, but that's not the case.

From `man git-log`:

> By default, the commits are shown in reverse chronological order.

That is, if a merge commit is merging a very old commit onto a recent base, `git log` will show:

* merge commit
* recent base
* (some less recent commits here)
* very old commit

Our post-order iterator would do what it's designed to do, which is not chronological:

* merge commit
* very old commit
* recent base
* (some less recent commits here)

We should add an iterator that does what `git log` does. I have an implementation that I'm happy to upstream, if that sounds like a good idea.

My implementation only does chronological sorting of the commits in the "stack" while walking, it doesn't sort the entire commit history at once. It's very likely that `git log` does the same, as otherwise it would have to load the entire commit history into memory.

I'm not sure if the post-order iterator is really useful for anything, to be honest, but I guess we can leave it there.

**Comment by mcuadros** [comment]
We have implemented `LogOrderCommitterTime` how is it different to your logic?

> set Order=LogOrderCommitterTime for ordering by committer time (more compatible with `git log`)
https://github.com/go-git/go-git/blame/2637279338ca9736c22b5e15fca916121ae8d089/options.go#L340

 About the post order, just leave it there, just in case someones need it.

**Comment by mvdan** [comment]
Thanks, https://pkg.go.dev/github.com/go-git/go-git/v5@v5.0.0/plumbing/object?tab=doc#NewCommitIterCTime is exactly what I was looking for.
