### ISSUE TITLE
worktree.Status does not handle a broken symlink correctly

### ISSUE THREAD

**Issue by alexey-igrychev** [go-git/go-git#253]
I expect the `diffStagingWithWorktree` function will work as `git status`, and a symlink pointing to a non-existent file will be handled correctly.

### Check
```shell
$ ln -s /nowhere broken_symlink

$ git add broken_symlink

$ git commit -m "Add symlink"
[master a30a58d] Add symlink
 1 file changed, 1 insertion(+)
 create mode 120000 broken_symlink

$ git status
On branch master
nothing to commit, working tree clean

$ ./main
broken_symlink: [worktree: Modified, staging: Unmodified]
```

### main.go
```go
package main

import (
	"fmt"

	"github.com/go-git/go-git/v5"
)

var fileStatusMapping = map[git.StatusCode]string{
	git.Unmodified:         "Unmodified",
	git.Untracked:          "Untracked",
	git.Modified:           "Modified",
	git.Added:              "Added",
	git.Deleted:            "Deleted",
	git.Renamed:            "Renamed",
	git.Copied:             "Copied",
	git.UpdatedButUnmerged: "Updated",
}

func main() {
	repo, err := git.PlainOpen(".")
	if err != nil {
		panic(err)
	}

	tree, err := repo.Worktree()
	if err != nil {
		panic(err)
	}

	status, err := tree.Status()
	if err != nil {
		panic(err)
	}

	filePath := "broken_symlink"
	fileStatus := status.File(filePath)
	fmt.Printf("%s: [worktree: %s, staging: %s]\n", filePath, fileStatusMapping[fileStatus.Worktree], fileStatusMapping[fileStatus.Staging])
}
```

**Comment by joelanford** [comment]
I traced this to the go-billy chroot filesystem that is used by go-git. When calculating the hash for filesystem symlinks, go-git [uses the underlying filesystem](https://github.com/go-git/go-git/blob/c66023ad305ee56a38781cc5d3ca96c7115bd2e5/utils/merkletrie/filesystem/node.go#L180). If the symlink target is an absolute path, the chroot filesystem [mangles it](https://github.com/go-git/go-billy/blob/d7a8afccaed297c30f8dff5724dbe422b491dd0d/helper/chroot/chroot.go#L191-L200) to make it appear "above" the root when read by `Readlink()`. This causes the hash computation to be incorrect. 

Just to test what would happen, I changed the call in `doCalculateHashForSymlink()` from `n.fs.Readlink(path)` to `os.Readlink(path)` and that resolved the issue for me. However I'm not sure that's safe for all cases.

**Comment by joelanford** [comment]
The same bug is listed in the old repo as well: https://github.com/src-d/go-git/issues/1017

**Comment by pjbgf** [comment]
For future reference, this is fixed with go-billy `BoundOS`:

```
// BoundOS is a fs implementation based on the OS filesystem which is bound to
// a base dir.
// Prefer this fs implementation over ChrootOS.
//
// Behaviours of note:
//  1. Read and write operations can only be directed to files which descends
//     from the base dir.
//  2. Symlinks don't have their targets modified, and therefore can point
//     to locations outside the base dir or to non-existent paths.
//  3. Readlink and Lstat ensures that the link file is located within the base
//     dir, evaluating any symlinks that file or base dir may contain.
```

https://github.com/go-git/go-billy/blob/4d0d7f0db7ba18ff382965e634bf7bc0e0fe9f19/osfs/os_bound.go#L32-L42

Code usage looks like: `osfs.New("/", WithBoundOS())`.
