### ISSUE TITLE
Diffing large files results in a panic

### ISSUE THREAD

**Issue by atrakh** [go-git/go-git#254]
The underlying issue appears to be due to a bug in v1.1.0 of `go-diff`. See details including error & stack trace here: https://github.com/sergi/go-diff/issues/117

The latest version of `go-diff` appears to resolve this issue, but is not yet released with a new tag. Would it be possible to pin `go-diff` to the latest commit on the master branch to resolve this issue?

**Comment by sroemen** [comment]
I have encountered this bug as well.

Tag v1.2.0 has the fix in it.

**Comment by louiemiranda** [comment]
How do we use go-diff on go-git?

**Comment by jazanne** [comment]
this bug has been any issue for me for awhile - any updates on trying to update the version of go-diff?
