### ISSUE TITLE
Git status "Your branch is up to date"

### ISSUE THREAD

**Issue by HLerman** [go-git/go-git#262]
Is there a way to know if a branch is up to date with remote ?
A git fetch is easily done, but what about the status of the current repository ?

Like git fetch && git status
"Your branch is up to date with 'origin/master'"

**Comment by bpmct** [comment]
@HLerman did you end up figuring this out?

**Comment by HLerman** [comment]
@bpmct Unfortunately you can't do that directly.
The solution seems to fetch and then compare the commits to determine if your local repository is up to date or not.
