### ISSUE TITLE
Cannot download v5

### ISSUE THREAD

**Issue by mminklet** [go-git/go-git#267]
Hi, pardon my ignorance as this is no doubt something wrong with my environment or what I'm doing...however I can't for the life of me seem to download the v5 branch of this package. We're not using git modules, just dep, and if I run `dep ensure -add github.com/go-git/go-git/v5`, or import and run dep ensure, I get heaps of compatibility issues, see

https://pastebin.com/03K393BK

I can dep ensure without the v5 sub directory, as described in the readme, but then of course that doesn't give me all the interesting stuff like v5/plumbing that I'd like to use. And also it seems to be the old version in general, as the _downloaded_ readme points at the old repo address (src-d). Similarly, go get for the v5 version fails to run.

Is this only available to go modules enabled repos?

**Comment by xiujuan95** [comment]
I have the same issue. Does have any updates about it?
