### ISSUE TITLE
push-option support

### ISSUE THREAD

**Issue by searsaw** [go-git/go-git#268]
I'm looking for a way to add push options to a push request. Specifically, I'm wanting to use them with Gitlab as designated [in their documentation](https://docs.gitlab.com/ee/user/project/push_options.html). I don't see the ability to do so anywhere in the `PushOptions` struct. In fact, I found [this issue](https://github.com/src-d/go-git/issues/1281) in what I believe used to be the area this project used to live in.

**Comment by lavrxxx** [comment]
Very good feature! And looks like someone added PR.
