### ISSUE TITLE
Supported auth method for github.com

### ISSUE THREAD

**Issue by ryanmcnamara** [go-git/go-git#271]
As per https://docs.github.com/en/rest/overview/other-authentication-methods#via-username-and-password
Basic auth (via Authorization header) is no longer supported as of 11/13/2020
![image](https://user-images.githubusercontent.com/3452559/112206700-da35f500-8bdb-11eb-9282-67e308e2943a.png)
A 401 with message `Authorization required` is returned

Additionally, the token auth provider does not work, as warned here: https://github.com/go-git/go-git/blob/2bdfd91f04068220a72feeade31defc09f2a601e/plumbing/transport/http/common.go#L217
When I tried this to simply `PlainClone` a repository, I received an error similar to 
```
unexpected client error: unexpected requesting \"https://github.com/org/repo.git/info/refs?service=git-upload-pack\" status code: 400
```

A workaround I found was to implement my own Auth as follows, providing the token via the *url*:
```
type TokenAuth struct {
	Token string
}

func (a *TokenAuth) SetAuth(r *nethttp.Request) {
	if a == nil {
		return
	}
	// hack to add user and password to the url
	r.URL.User = url.UserPassword("na", a.Token)
}

// Name is name of the auth
func (a *TokenAuth) Name() string {
	return "http-token-auth-url"
}

func (a *TokenAuth) String() string {
	masked := "*******"
	if a.Token == "" {
		masked = "<empty>"
	}
	return fmt.Sprintf("%s - %s", a.Name(), masked)
}
```

This appears to still be supported.

The ask is to have a supported way to use auth with github provided, thanks!

**Comment by jeffwidman** [comment]
Why can't you use `httpBasicAuth`? Github didn't say they stopped supporting basic auth, just that they stopped supporting passwords in basic auth. My reading of that announcement is you can still use API tokens as passwords via basic auth:
```
auth = &http.BasicAuth{Username: username, Password: token}
```
