### ISSUE TITLE
Dependency missing causing go-git to no longer work

### ISSUE THREAD

**Issue by sanjP10** [go-git/go-git#273]
Hi,

I use your git library in my code base https://github.com/sanjP10/release.

When I attempt to install my binary with 
`GO111MODULE=on go get -u github.com/sanjP10/release` I seem to be hitting an error with the kevinburke ssh config dependency. Looking at the repository the tag v0.0.0-20201106050909-4977a11b4351 is no longer available. Looking at the repository there has been some recent activity. 

I also tried installing in a docker container, and I get the following.

```
go get -u github.com/go-git/go-git/v5
go: github.com/go-git/go-billy/v5 upgrade => v5.1.0
go: github.com/kevinburke/ssh_config upgrade => v1.0.2
go: golang.org/x/crypto upgrade => v0.0.0-20210322153248-0c34fe9e7dc2
go: github.com/Microsoft/go-winio upgrade => v0.4.16
go: golang.org/x/net upgrade => v0.0.0-20210326220855-61e056675ecf
go: golang.org/x/sys upgrade => v0.0.0-20210326220804-49726bf1d181
go get: github.com/kevinburke/ssh_config@v0.0.0-20201106050909-4977a11b4351 updating to
        github.com/kevinburke/ssh_config@v1.0.2: parsing go.mod:
        module declares its path as: github.com/virtuald/ssh_config
                but was required as: github.com/kevinburke/ssh_config
```

If you could take a look at this that would be appreciated.

sanjP10

**Comment by sanjP10** [comment]
It seems that someone has already raised an issue. https://github.com/kevinburke/ssh_config/issues/29 and there may be a solution being worked on

**Comment by kevinburke** [comment]
This should be fixed now. Can you try again?

**Comment by sanjP10** [comment]
This is resolved for me @kevinburke
