### ISSUE TITLE
Does go-git supports Credential-Helper scripts?

### ISSUE THREAD

**Issue by Rajeskumar** [go-git/go-git#28]
Does go-git supports authentication other than basicAuth? I am looking to connect to a private repository using git credentials helper script so that I dont need to pass username and password.

Is it feasible with go-git library?

**Comment by mcuadros** [comment]
Currently, credential helper scripts are not supported, could be a good addition.

**Comment by Rajeskumar** [comment]
thanks for response @mcuadros . We made custom workaround in our go project.
