### ISSUE TITLE
Bulid errors

### ISSUE THREAD

**Issue by dikkini** [go-git/go-git#280]
build for aix/ppc64
error: 
```
# github.com/go-git/go-billy/v5/osfs
/Users/dikkini/go/pkg/mod/github.com/go-git/go-billy/v5@v5.0.0/osfs/os_posix.go:15:9: undefined: unix.Flock
/Users/dikkini/go/pkg/mod/github.com/go-git/go-billy/v5@v5.0.0/osfs/os_posix.go:22:9: undefined: unix.Flock
```

**Comment by pjbgf** [comment]
@dikkini this is due to [go-git/go-billy](https://github.com/go-git/go-billy) not having support for `ppc64`. If this is important to you, please create a feature request on that repository.
