### ISSUE TITLE
Is it possible to clone with the mirror option

### ISSUE THREAD

**Issue by natemarks** [go-git/go-git#293]
I searched for 'mirror' and couldn't find anything, but maybe I'm overthinking it?  Something like:
git clone --mirror

**Comment by gdetrez** [comment]
I was looking for this too.  I found that I could achieve the same as `git clone --mirror` with `Clone` followed by `Fetch`:

```go
repo, err := git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
	URL:          url,
	...
})
err = repo.Fetch(&git.FetchOptions{
	RefSpecs: []config.RefSpec{"+refs/*:refs/*"},
	...
})
```

But it would be nice to be able to pass `RefSpecs` to `Clone` directly.
