### ISSUE TITLE
Get files affected by a commit

### ISSUE THREAD

**Issue by ValentinTrinque** [go-git/go-git#307]
I am trying to find a way to get the files that have been changed by a commit.

I tried `Commit.Files()` but it returns all the files tracked by the repository.

Is this possible ?

**Version**
`v5.3.0`

**Comment by briemarie** [comment]
@ValentinTrinque I had to get the patch of the commit and its parent commit. This gives you all the files changed in the patch as FilePatches(). Here is a generalized flow of the methods I called:

        (currCommit is the commit and r is the clone of the repo)
	parentHash := currCommit.ParentHashes[0]
	parent, err := r.GetCommit(ctx, parentHash)
	patch, err := parent.Patch(currCommit)
        for _, p := range patch.FilePatches()

**Comment by abiosoft** [comment]
> @ValentinTrinque I had to get the patch of the commit and its parent commit. This gives you all the files changed in the patch as FilePatches(). Here is a generalized flow of the methods I called:

The limitation with this approach is that it is impossible to get the patch of a repo with a single commit, as there is no parent to compare with.
