### ISSUE TITLE
List local and remote branches

### ISSUE THREAD

**Issue by Narven** [go-git/go-git#308]
```
// repo *git.Repository

branchs, err := repo.Branches()
```

If I do this, I get a list of branches, but they are all local branches. In git if you do `git branch --all` we get both local and remote.

Is there any way to do this?

PS: apologise for this not being an error

**Comment by dacturne** [comment]
I've found out that you can iterate over the references
```go
refIter, _ := repo.References()
refIter.ForEach(func(r *plumbing.Reference) error {
	if r.Name().IsRemote() {
		fmt.Println("branch: ", r.Name().Short())
	}
	return nil
})
```
