### ISSUE TITLE
plumbing/transport/http is dependant on internal package

### ISSUE THREAD

**Issue by torlangballe** [go-git/go-git#313]
When simply trying to import `github.com/go-git/go-git/v5`, or go getting the sub-package ...plumbing/transport/http, I get error about use of an internal package: 

`go get github.com/go-git/go-git/plumbing/transport/http
`
`package github.com/go-git/go-git/plumbing/transport/http
	../../../pkg/mod/github.com/go-git/go-git@v4.7.0+incompatible/plumbing/transport/http/upload_pack.go:14:2: use of internal package gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common not allowed
`

Am on go 1.16 darwin, have tried cleaning caches, and a friend has tried as well.

Perhaps something to do with changes needed to handle src-d?

**Comment by mcuadros** [comment]
We don't have any dependency to src-d version, this errors are from a `go get` command?

**Comment by torlangballe** [comment]
Hi,

Yes, It happened when I compiled a test with 
import "github.com/go-git/go-git/v5"

But I can get it just by doing

go get github.com/go-git/go-git/plumbing/transport/http <http://github.com/go-git/go-git/plumbing/transport/http>

from within my module.

The full program is:
package main

import (
    "os"

    "github.com/go-git/go-git/v5"
)

func main() {
    r, err := git.Cone(memory.NewStorage(), nil, &git.CloneOptions{
        Auth: &http.BasicAuth{
            Username: "torlangballe",
            Password: "xxxx",
        },
        URL:      "git.dev.btech:/git/qtt.git",
        Progress: os.Stdout,
    })
    zlog.OnError(err)
}



Get the same error message when compiling.

tor

**Comment by mcuadros** [comment]
You should execute `go get github.com/go-git/go-git/v5 `.

**Comment by sinarra-tibco** [comment]
Hello @mcuadros 
I am still having the same issue. I did execute "go get github.com/go-git/go-git/v5". Nothing was downloaded and it did not solve the issue for me.

**Comment by ChrisJBurns** [comment]
I also get this error, even after doing the execute above.
`found github.com/go-git/go-git/plumbing/transport/http in github.com/go-git/go-git v4.7.0+incompatible`

**Comment by brucealthompson** [comment]
I have exactly the same issue as stanhughes-nov. 

This answer: "You should execute go get github.com/go-git/go-git/v5 ." does not work as stanhughes-nov stated. 

I have upgraded to the latest version of github.com/go-git/go-git/v5. Same issue.

**Comment by dattnguyen1991** [comment]
@brucealthompson You can try with import `"github.com/go-git/go-git/v5/plumbing/transport/http"` when using `http.BasicAuth`
