### ISSUE TITLE
Support prune option in Fetch method

### ISSUE THREAD

**Issue by kevinpollet** [go-git/go-git#316]
## Feature

Currently, it is not possible to `fetch` from a remote and to remove the deleted remote branches at the same time. This is currently possible with the `git fetch` command by using the `--prune` option as described here https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---prune.

As suggested in https://github.com/src-d/go-git/issues/624 a `bool` could be added to the `FetchOptions` struct.

As a side note, the above issue has been closed without a proper fix because the linked PR only adds the `Prune` option to the `PushOptions` struct which is not the same.

## Workaround

There is currently no workaround or at least none of I'm aware of.

**Comment by ydcool** [comment]
It's been a year,  what's the progress now
