### ISSUE TITLE
Usage of deprecated IsEncryptedPEMBlock in v5.3.0 function leads to broken encryption detection for private keys

### ISSUE THREAD

**Issue by domano** [go-git/go-git#318]
I am trying to use a private key to generate public keys to use as a transport.Authmethod for my CloneOptions.

This does not work with v5.3.0 and the fix is in the main branch since this commit:
https://github.com/go-git/go-git/commit/77e7ef99c8cadc8ba769c1971a3acc8d7844adb0

(Basically `x509.IsEncryptedPEMBlock(block)` is replaced due to depraction and support for more formats.)

Will there be a bugfix release / version bump? This currently breaks my application for modern SSH Keys and i would rather not depend on the main branch.

Thank you for all the great work!

**Comment by mcuadros** [comment]
https://github.com/go-git/go-git/releases/tag/v5.4.0

Thanks!
