### ISSUE TITLE
Feature request: colored diff output

### ISSUE THREAD

**Issue by twpayne** [go-git/go-git#33]
I'm using go-git to generate [git format diffs](https://git-scm.com/docs/diff-format) in [my project](https://github.com/twpayne/chezmoi). I'd like to be able to generate colored diffs, like git does.

go-git's diff generation is in the [`github.com/go-git/go-git/v5/plumbing/format/diff`](https://pkg.go.dev/github.com/go-git/go-git/v5/plumbing/format/diff?tab=doc) package.

Would you accept a PR that adds color support to go-git's diff generation?

Refs https://github.com/twpayne/chezmoi/issues/680.

**Comment by mcuadros** [comment]
Sure! Thanks for asking
