### ISSUE TITLE
Unable to switch to new local branch

### ISSUE THREAD

**Issue by herzrasen** [go-git/go-git#334]
Hi,

I'm trying to checkout a new local branch like `git checkout -b my-branch` is doing. 

I was reading through a lot of material I found but have been unable to achieve what I wanted. 

```
path, err := ioutil.TempDir("", "git-repo-*")
	if err != nil {
		t.Fail()
	}
	repo, err := git.PlainInit(path, false)
	if err != nil {
		t.Errorf("Error creating repo: %s", err)
	}
	err = repo.CreateBranch(&config.Branch{
		Name:   "main",
		Merge:  plumbing.NewBranchReferenceName("main"),
	})
	if err != nil {
		t.Errorf("Unable to create branch: %s", err)
	}
	worktree, err := repo.Worktree()
	if err != nil {
		t.Errorf("Unable to get worktree: %s", err)
	}
	err = worktree.Checkout(&git.CheckoutOptions{
		Branch: plumbing.NewBranchReferenceName("main"),
		Create: true,
	})
	if err != nil {
		t.Errorf("Unable to checkout branch: %s", err)
	}
```
When trying to Checkout the new branch I get the error:
```
Unable to checkout branch: reference not found
```
Clearly I am doing something wrong. Any advice would be greatly appreciated.

**Comment by herzrasen** [comment]
I found out that I am able to checkout a new branch after committing to the initial branch. I don't really understand why, but this seems to be the way to achieve what I want.

**Comment by jplimack** [comment]
same here, its kinda annoying since im trying to create a `main` branch, and this ends up creating both `main` and `master`. so thats 1 extra call at the end to clean that up.
