### ISSUE TITLE
How to get all references when in a detached HEAD?

### ISSUE THREAD

**Issue by paymog** [go-git/go-git#337]
Let's say a git repo is in a detached head state with `git checkout 51eea0e50e945ba7a9a327c4271f86c6279bf92d`. Let's also say that this commit has several references (is that the right word?) like so:

```
 ❮❮❮ git log -n 1
commit 51eea0e50e945ba7a9a327c4271f86c6279bf92d (HEAD, origin/main, origin/HEAD, master, main)
Author: Paymahn Moghadasian <paymahn1@gmail.com>
Date:   Wed Jun 16 10:56:30 2021 -0500

    better docker caching
```

Note that this commit is `HEAD` but also `origin/main`, `origin/HEAD`, etc.

If I run the following code at this commit:

```golang
func main() {
	repo, err := git.PlainOpen(".")
	if err != nil {
		log.WithError(err).Fatal("not a git repo")
	}
	head, err := repo.Head()
	if err != nil {
		log.WithError(err).Fatal("could not get head")
	}
	log.Info(head.Name())
}
```

I get the following output: `INFO[0000] HEAD`

What's the canonical way to get the _other_ references at this commit?

**Comment by WKBae** [comment]
https://github.com/git/git/blob/670b81a890388c60b7032a4f5b879f2ece8c4558/log-tree.c#L211-L213
You should iterate `repo.References()` and compare whether `ref.Hash()` matches the commit hash. If you need symbolic refs, you should resolve `ref.Target()` depending on the ref type.

**Comment by paymog** [comment]
Ah, great idea! Thanks for the tip 😄
