### ISSUE TITLE
Checkout to tag hash is not working

### ISSUE THREAD

**Issue by FlorianJDF** [go-git/go-git#34]
Hello,

Checking out from a tag hash is not working.

Example:
``` Go
gitTag, err := repo.Tag(ref)
if err != nil {
	return nil, err
}

workTree, err := repo.Worktree()
if err != nil {
	return nil, err
}


err = workTree.Checkout(&git.CheckoutOptions{
		Hash:   gitTag.Hash(),
})
```
An Error will occur because the Tag Hash is not in the working tree.
I don't know why but the hash returned by gitTag.Hash() is not the commit Hash.

Tag Hash: d98ac2f9fa70e6bba8bd17f23be96b52608792f2
Commit: ebee1b73ea6315e0c7b27f6bb3a88df27d6fec62

So an error "Object not found" occurs.

But taking this Hash, and doing a checkout with git CLI is working:
``` bash
$ git checkout d98ac2f9fa70e6bba8bd17f23be96b52608792f2
HEAD is now at ebee1b7... release
$ git log
commit ebee1b73ea6315e0c7b27f6bb3a88df27d6fec62
```

Regards,

**Comment by mcuadros** [comment]
As described on the documentation `Tag` returns a lightweight and annotated tags, if you have an annotated tag will be pointing to the `Tag` object and not the `Commit` object.

You have an example in the documentation about how to solve this specific case:
https://pkg.go.dev/github.com/go-git/go-git/v5?tab=doc#Repository.Tag
