### ISSUE TITLE
Bitbucket http.BasicAuth requires username when using personal tokens

### ISSUE THREAD

**Issue by leodamasceno** [go-git/go-git#348]
Hello,

I have been using go-git to clone repositories from Github (Private and public) with no issues (Thanks for that BTW).

I started a project recently and I need to clone a private repository from Bitbucket Server, I was getting the following error:
```
error: authentication required
```

I checked the examples and documentation but I could not find anything related to that so I started doing some tests and I found out that Bitbucket *requires* the right username in the **http.BasicAuth** parameters (Which is not the case when using Github). Here's my code:

```
package main

import (
    "fmt"
    "github.com/go-git/go-git/v5"
    . "github.com/go-git/go-git/v5/_examples"
    git_http "github.com/go-git/go-git/v5/plumbing/transport/http"
)


func main() {

    r, err := git.PlainClone("repo", false, &git.CloneOptions{
        Auth: &git_http.BasicAuth{
            Username: "git", // yes, this can be anything except an empty string
            Password: "MY_TOKEN",
        },
        URL:           "MY_REPO_HTTPS_URL",
    })
    CheckIfError(err)

    // Retrieving the branch being pointed by HEAD
    ref, err := r.Head()
    CheckIfError(err)
    // ... retrieving the commit object
    commit, err := r.CommitObject(ref.Hash())
    CheckIfError(err)
    commit_id := commit.ID().String()
    fmt.Println(commit_id)
}
```

So, this code works fine when cloning repositories from Github, but in order to make it work with my Bitbucket server repositories, I had to update the **Username** parameter and set the real user there.

Just wanted to post it here in case someone else is having the same issue.

Cheers

**Comment by chenzhanjia-idcos** [comment]
met the same issue on gitee.com

**Comment by egenchen** [comment]
met the same issue on gitee.com
