### ISSUE TITLE
Commit --amend and --no-edit

### ISSUE THREAD

**Issue by gabrielseibel1** [go-git/go-git#35]
Hi. I'm trying to implement a simple `git commit --amend --no-edit` using go-git. I noticed the compatibility table states `commit` is supported, without any notes on specific flags. Are the flags `--amend` and `--no-edit` implemented and I'm missing something? If this is not currently possible with this module, maybe the documentation could state it upfront.

**Comment by mcuadros** [comment]
git has two levels of abstraction, you can perfectly do this task with the plumbing part, that's why this `commit` is mark as supported. 

What is not supported is a `CommiOption` with the Amend flag, we `go-git` can not aim to support all the porcelain features, socially this kind that is very user-oriented.

Anyway, PRs are welcome.

**Comment by pmoody-** [comment]
Hi,

I find myself wanting to do something similar. Are there any examples of using the low-level plumbing interface(s) for doing sort of commit re-writing?

Cheers

**Comment by john-cai** [comment]
https://github.com/go-git/go-git/pull/438

**Comment by sosheskaz** [comment]
This is probably an ugly solution, but you can approximate the effect of amend by:

1. Set `toAmend` to the commit you would like to amend.
2. Set `parent` to the parent hash of `toAmend` 
3. Checkout `toAmend`
4. Perform a soft reset to `toAmend`'s parent.
5. Make any modifications to the tree.
6. Perform a commit.
7. Reset any additional `plumbing.Reference`s.

Worked well for my purposes, but I'm also not really dealing with branches, so YMMV with references.

**Comment by gabrielseibel1** [comment]
Hi. OP here. I've no more interest in this effort, I've left the company where I was trying to work that out. Should I close this issue?

**Comment by pjbgf** [comment]
Closing as done - https://github.com/go-git/go-git/pull/438.
