### ISSUE TITLE
empty git-upload-pack given

### ISSUE THREAD

**Issue by sherlockEix** [go-git/go-git#355]
when i use `fetch` to update repo. it's throw error `empty git-upload-pack given` .but i can success clone remote repo with `CloneOptions`.
What should I do to resolve this error. Thanks~
go-git version: `v5.4.2`
os: `mac`

* git clone code.it's work
```
	cloneOptions := git.CloneOptions{
		URL:             url,
		Depth:           1,
		Progress:        os.Stdout,
		Auth:            &http.BasicAuth{Username: "test", Password: "*******"},
		RemoteName:      "origin",
		Tags:            git.NoTags,
		InsecureSkipTLS: false,
	}
```

* git fetch code, it's not work
```
	fetchOptions := git.FetchOptions{
		Auth: cloneOptions.Auth,
		//Tags:            cloneOptions.Tags,
		Progress:        os.Stdout,
		InsecureSkipTLS: true,
		RemoteName:      RemoteRepoName,
		Depth:           1,
		Force:           true,
	}
	logger.LOGGER.Info("start fetch remote repo")
	err = repository.Fetch(&fetchOptions)
```

**Comment by sherlockEix** [comment]
when `cloneOptions` use depth =1  or command `git clone github.com --depth=1`
happen error `empty git-upload-pack given` when use go-git `fetch` .
Do I need other `FetchOptions` configuration?

**Comment by sherlockEix** [comment]
resolve it~

**Comment by scottpettyjohn** [comment]
> resolve it~

@sherlockEix  - did you find a solution?

**Comment by nicholasSUSE** [comment]
I am also having a problem with this, and I need to use Depth=1, did someone resolve this?

**Comment by AriehSchneier** [comment]
@nicholasSUSE / @scottpettyjohn : Have you tried using latest master which has the fix? ie try running this command:
```
go get github.com/go-git/go-git/v5@master
```
which currently should result in this version:
```
github.com/go-git/go-git/v5 v5.7.1-0.20230711075303-56c4bf4ca978
```
