### ISSUE TITLE
Rare cases where Tree.Files() breaks gracefully early

### ISSUE THREAD

**Issue by liiri** [go-git/go-git#376]
I detected a rare cases in which my code, which iterates files for given commit shas, is getting an early break, although many more files should have been iterated.

My code, minus some error handling:

```go
commitish:="...sha..."
repository, err = git.PlainOpen("...path...")
hash, err := repository.ResolveRevision(plumbing.Revision(commitish))
commit := repository.CommitObject(*hash)
tree, err := commit.Tree()
count := 0
err = tree.Files().ForEach(func(file *object.File) error {
	count++
	return doStuffWithFiles(file)
})
```

I couldn't reproduce in debugger, so can't tell when this might happen, but I suspect it occurs when multiple instances of my program are running on same clone with same sha (which occurs quite often in my architecture).

Am I missing something on checking if an unexpected error had occurred? Is the concurrent access not supported in some way? I'm guessing any relevant code would be under https://github.com/go-git/go-git/blob/master/plumbing/object/tree.go

**Comment by pjbgf** [comment]
Probably related to #773, as unfortunately there are quite a few use cases where `go-git` fails to support concurrency.
