### ISSUE TITLE
Cloning and pushing only tags

### ISSUE THREAD

**Issue by martencassel** [go-git/go-git#380]
Is it possible to clone and push tags only using go-git ? 

```bash
git clone --branch v5.4.2 https://github.com/go-git/go-git.git;
git remote add dst-repo https://github.com/my-account/my-repo.git
git push dst-repo v5.4.2;
```

I can fix this by shelling out to > git push instead of using the Push function.

**Comment by pjbgf** [comment]
For future reference, this can be achieved through `PushOptions.RefSpecs` and `FetchOptions.RefSpecs`:

https://github.com/go-git/go-git/blob/cd6633c3c665ba37f766e96c59c57c58051d0e58/remote_test.go#L593

When cloning you can also impact tag fetching behaviour with its [own option](https://github.com/go-git/go-git/blob/cd6633c3c665ba37f766e96c59c57c58051d0e58/options.go#L74).
