### ISSUE TITLE
Conditional configurations are not loaded properly

### ISSUE THREAD

**Issue by moorara** [go-git/go-git#388]
It seems the following syntax is not supported by the library:

```
[includeIf "gitdir:~/src/github.com/octocat/"]
  path = .gitconfig-octocat
```

This is an issue when you are creating a commit or tag and not specifying the author and committer. This leads to the new commit or tag being created with wrong email address.

**Comment by reegnz** [comment]
I'm also having the same issue.

**Comment by reegnz** [comment]
I think this one is probably a duplicate of #110

**Comment by pjbgf** [comment]
Nice shout @reegnz. Closing this in favour of #110.
