### ISSUE TITLE
Does go-git have a code branch diff  git diff branch1 branch2

### ISSUE THREAD

**Issue by chenpfeisoo** [go-git/go-git#389]
Does go-git have a code branch diff  git diff branch1 branch2 ?
I only saw this
```go
func Do(src, dst string) (diffs []diffmatchpatch.Diff) {
	// the default timeout is time.Second which may be too small under heavy load
	return DoWithTimeout(src, dst, time.Hour)
}
```

**Comment by louiemiranda** [comment]
I am also looking for a similar diff, would be very useful on my current project.

**Comment by chenpfeisoo** [comment]
I found a tool that can parse git diff before. You can refer to it
https://github.com/waigani/diffparser

**Comment by louiemiranda** [comment]
Will check it out @chenpfeisoo thanks

**Comment by chng** [comment]
> Does go-git have a code branch diff git diff branch1 branch2 ? I only saw this
> 
> ```go
> func Do(src, dst string) (diffs []diffmatchpatch.Diff) {
> 	// the default timeout is time.Second which may be too small under heavy load
> 	return DoWithTimeout(src, dst, time.Hour)
> }
> ```

Hey, so have you finally found the solution of branch oriented git diff please?
