### ISSUE TITLE
How to disable `--allow-empty` with go-git?

### ISSUE THREAD

**Issue by byte-bucket** [go-git/go-git#390]
As per this issue https://github.com/go-git/go-git/issues/189 , no options is provided.

But what's the workaround? Like comparing commit hash? Or any quickie way?

**Comment by dtelaroli** [comment]
I solved this issue using git status.

```Golang
worktree, err = repo.Worktree()
if err != nil {
	return err
}

status, err := worktree.Status()
if err != nil {
	return err
}

if status.IsClean() {
	log.Info("Nothing to commit")
	return nil
}
```
