### ISSUE TITLE
Failure to resolve deltas when PlainClone or Fetching from a new AWS CodeCommit repository

### ISSUE THREAD

**Issue by ga-paul-t** [go-git/go-git#391]
When attempting to clone a newly created repository in AWS CodeCommit, that for example only contains a single commit, the following error is encountered:

```sh
reference delta not found
```

The following code is used to perform the clone:

```go
repo, err := git.PlainClone(dir, false, &git.CloneOptions{
    URL:           url,
    ReferenceName: plumbing.NewBranchReferenceName("main"),
    Tags:          git.AllTags,
    SingleBranch:  true,
    Depth:         1,
})
```

I never encounter this issue when cloning from another source control system like Github

**Comment by pjbgf** [comment]
Closing as this was closed as part of #392 / #484.
