### ISSUE TITLE
Remove git binary dependency from the file:// protocol 

### ISSUE THREAD

**Issue by lacarvalho91** [go-git/go-git#398]
This was originally raised on the old repo: https://github.com/src-d/go-git/issues/847 but I couldn't find it raised here.

My situation is that I am using a distroless base image when building my application image. The file protocol is very useful for testing, but I'm having problems now because go-git is trying to delegate to the git executable.

**Comment by tomqwpl** [comment]
Yes, I've got the same issue. I'm confused because I thought this was a pure Go implementation if git, yet appears to require a git installation. So this is only in the case of file: protocol?

**Comment by lacarvalho91** [comment]
Keeping this issue alive
