### ISSUE TITLE
How do you push a Git tag to a branch using a refspec?

### ISSUE THREAD

**Issue by twgcode** [go-git/go-git#423]
How to implement the following commands:
 `git push origin  tagName1^{}:master`

tagName1 is the name of a tag

**Comment by tjamet** [comment]
Hi!
If I may, I had a similar case that I happen to have open-sourced recently.
In my case, I am pushing a given sha, but the logic would probably be similar if the syntax is supported in the current implementation.

The implementation is here: https://github.com/adevinta/maiao/blob/9e7f216e631f5d1ca171d472792510cc18bd34fe/pkg/maiao/review.go#L218

More specifically, I used:
```go
	refToPush := "tagName1^{}"
	refspecs := []config.RefSpec{config.RefSpec(refToPush+":refs/heads/master")}

	err = repo.Push(&git.PushOptions{
		RemoteName: "origin",
		RefSpecs:   refspecs,
	})
```

To support pushing with a given sha, I had to add support for it: https://github.com/go-git/go-git/pull/325

Hope this helps
