### ISSUE TITLE
git.Clone() with depth 1 and a hash as reference?

### ISSUE THREAD

**Issue by shibumi** [go-git/go-git#441]
Hi,

Is it possible to git clone a repository with depth 1 and just a hash? What I am looking for is something like:

```go
		repo, err := gitv5.Clone(metadata, origin, &gitv5.CloneOptions{
			URL: entry.URL,
			Depth: 1,
                        ReferenceHash: plumbing.Hash("deaddeaddead")
		})
```

**Comment by rickyzhang82** [comment]
No, I don' think Git protocol support clone by commit hash. Branch and tag are the only references used in Git clone. See [Git clone doc](https://www.git-scm.com/docs/git-clone)

**Comment by pjbgf** [comment]
This is possible by setting the `RefSpec` of the reference you want from the remote - but for that you will need to [create a remote and fetch a specific refspec](https://github.com/go-git/go-git/blob/9cc340a7fc5ce1de70eb794e1864b1a51e9a0a07/repository_test.go#L3336-L3346) that includes the given hash.

If you are trying via clone, you are bound by the [existing heuristics](https://github.com/go-git/go-git/blob/9cc340a7fc5ce1de70eb794e1864b1a51e9a0a07/repository.go#L1007-L1028), which I don't think would help your case. After that you would checkout to the given commit.
