### ISSUE TITLE
Compiled binaries

### ISSUE THREAD

**Issue by Jazcash** [go-git/go-git#444]
Are there compiled binaries of this somewhere? I need a Windows x64 .exe build and have no idea how to build it myself

**Comment by magnusbaeck** [comment]
The contents of this repository is mainly intended to be used as a library for other Go programs. It is possible to build an executable with an extremely limited feature set (see [cli/go-git/main.go](https://github.com/go-git/go-git/blob/master/cli/go-git/main.go)), but is that _really_ what you're looking for?

**Comment by Jazcash** [comment]
Was looking for a lightweight git binary I can use for clone + checkout only, the official "portable" git build for windows is 280MB so was hoping to find something like this that would be a bit smaller.

**Comment by pjbgf** [comment]
For future reference: https://github.com/fhs/gig.
