### ISSUE TITLE
Communication channel for contributors/users

### ISSUE THREAD

**Issue by nikochiko** [go-git/go-git#455]
I feel it will be helpful to have a communication channel for contributors and users such as Telegram, Discord, Slack, etc. to discuss development and use of go-git more synchronously than GitHub allows for.

It will lead to support issues of new adopters being solved by old adopters rather than coming to the maintainers.

**Comment by pjbgf** [comment]
@nikochiko feel free to reach out here: https://join.slack.com/t/go-git/shared_invite/zt-1tk7vwrsw-ywCUKRCo_uS_QbKMQ2ukpA.
