### ISSUE TITLE
git log --follow - option to follow renames

### ISSUE THREAD

**Issue by sanderdekoning** [go-git/go-git#459]
I'm looking into adding the `--follow` option to `git log`. I've come to https://github.com/go-git/go-git/blob/935af59cf64fbe49eb8baba9fe80e6b236daf593/plumbing/object/commit_walker_path.go#L59 where https://github.com/go-git/go-git/blob/935af59cf64fbe49eb8baba9fe80e6b236daf593/plumbing/object/commit_walker_path.go#L112 seems to be one possibility to add such an option. Looking into this further I noticed a few comments regarding v6 - is there any plans already in place to add the `--follow` renames option for `git log`, and/or are there any failed attempts?

**Comment by kubaracek** [comment]
:+1:

**Comment by skroczek** [comment]
Are there any news? I am looking for exactly this. Is there a timeline for when we can expect this to be implemented? Or is there any help needed?

**Comment by marcosQuesada** [comment]
I'm reaching the same stone here, so +1, happy to help if required :)
