### ISSUE TITLE
Is `Add()` Safe-Thread, Or Rather Routine Safe?

### ISSUE THREAD

**Issue by ModelAdvisor** [go-git/go-git#466]
I tried to call `Add()` with `go`, it always to return errors like `unexpected EOF`, but I didn't get any clue in docs. Can you please let me know?

**Comment by ModelAdvisor** [comment]
Use `Add` Concurrently, I mean

**Comment by pjbgf** [comment]
Closing this in favour of #773 that highlights other concurrency issues.
