### ISSUE TITLE
example to init a new repo and commit to new branch

### ISSUE THREAD

**Issue by capsci** [go-git/go-git#481]
I want to create a new repo and commit to new branch.
Can someone please point out what am I missing?

```go
func main() {
	InitNewRepo("git@github.com:xyz/uvw.git", // make sure repo is empty with no branches
		&http.BasicAuth{
			Username: "abc", // yes, this can be anything except an empty string
			Password: "ghp_xxxxx",
		})
}

func InitNewRepo(url string, auth *http.BasicAuth) {
	repo, err := git.Init(memory.NewStorage(), memfs.New())
	checkErr(err)

	_, err = repo.CreateRemote(&config.RemoteConfig{
		Name: "origin",
		URLs: []string{url}})
	checkErr(err)

	worktree, err := repo.Worktree()
	checkErr(err)

	fmt.Println("checking out new branch")
	err = worktree.Checkout(&git.CheckoutOptions{
		Branch: plumbing.NewBranchReferenceName("main"),
		Create: true,
	})
	checkErr(err)
}

func checkErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
```

When executing above, I get error:
```console
checking out new branch
2022/03/02 15:26:34 reference not found
exit status 1
```

**Comment by anlsergio** [comment]
I'm getting the same. I even tried to create a new reference to `main` but I got no success so far (getting `nil` pointer at `r.Head()`):

```go
	r, err := git.Init(client.Storage, client.FS)

	// Create a new branch to the current HEAD
	headRef, err := r.Head()

	// Create a new plumbing.HashReference object with the name of the branch
	// and the hash from the HEAD. The reference name should be a full reference
	// name and not an abbreviated one, as is used on the git cli.
	//
	// For tags we should use `refs/tags/%s` instead of `refs/heads/%s` used
	// for branches.
	ref := plumbing.NewHashReference("refs/heads/main", headRef.Hash())

	// The created reference is saved in the storage.
	err = r.Storer.SetReference(ref)
```

**Comment by thomscoder** [comment]
I have the same problem with git.Init

**Comment by pjbgf** [comment]
> git init
> git checkout -b "foo"

@Diaphteiros as per `git` CLI, this is not a valid state:

![image](https://github.com/go-git/go-git/assets/5452977/b72c88b9-257b-4d76-b820-e958b43584ac)

**Comment by pjbgf** [comment]
@capsci You are trying to checkout which in this case won't really work as you don't have a commit in the repository.
If you just want to create an "unborn branch", you should just change the HEAD symbolic link:

```go
func InitNewRepo(url string, auth *http.BasicAuth) {
	repo, err := git.Init(memory.NewStorage(), memfs.New())
	checkErr(err)

	_, err = repo.CreateRemote(&config.RemoteConfig{
		Name: "origin",
		URLs: []string{url}})
	checkErr(err)

	fmt.Println("checking out new branch")
	ref := plumbing.NewSymbolicReference("HEAD", "refs/heads/foo")
	err = repo.Storer.SetReference(ref)
	checkErr(err)
}
```

Please note that the branch will remain "unborn" until a commit is created:
![image](https://github.com/go-git/go-git/assets/5452977/f1cabb50-c3ff-448d-86bf-3c0b1ff74d0d)

**Comment by julien-michaud** [comment]
> ```go
> 	_, err = repo.CreateRemote(&config.RemoteConfig{
> 		Name: "origin",
> 		URLs: []string{url}})
> 	checkErr(err)
> 
> 	fmt.Println("checking out new branch")
> 	ref := plumbing.NewSymbolicReference("HEAD", "refs/heads/foo")
> 	err = repo.Storer.SetReference(ref)
> ```

do you know how to id but with a `PlainInit` instead ?

thanks
