### ISSUE TITLE
Error on commit_walker_limit.go when trying to iterate git logs. 

### ISSUE THREAD

**Issue by barats** [go-git/go-git#482]
I have a bunch of repos want to do some analysis work. When I try to retrieve  commits from repo, program crashes and get error below. 

```
panic: runtime error: index out of range [65533] with length 57711
goroutine 1988 [running]:
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc000669618, 0xc01cf89980, 0x1, 0x2, 0xc0856ec000, 0xe16f, 0xec00, 0x0, 0xc01cf89980, 0x1)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/sergi/go-diff@v1.1.0/diffmatchpatch/diff.go:452 +0x328
github.com/go-git/go-git/v5/utils/diff.DoWithTimeout(0x0, 0x0, 0xc0c1d7e000, 0x1e515c, 0x34630b8a000, 0x0, 0x0, 0x1)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/utils/diff/diff.go:37 +0x1b8
github.com/go-git/go-git/v5/utils/diff.Do(...)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/utils/diff/diff.go:22
github.com/go-git/go-git/v5/plumbing/object.filePatchWithContext(0x15d5650, 0xc00002a0f8, 0xc1bec6c180, 0x15d3e00, 0xc06f9737c0, 0x0, 0x0)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/patch.go:68 +0x234
github.com/go-git/go-git/v5/plumbing/object.getPatchContext(0x15d5650, 0xc00002a0f8, 0x0, 0x0, 0xc066842000, 0x271, 0x271, 0x271, 0x0, 0x0)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/patch.go:38 +0xce
github.com/go-git/go-git/v5/plumbing/object.Changes.PatchContext(...)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/change.go:158
github.com/go-git/go-git/v5/plumbing/object.(*Tree).PatchContext(0xc20c64d8b0, 0x15d5650, 0xc00002a0f8, 0xc209660e10, 0xc020c9a13d, 0xc20c64d8b0, 0x0)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/tree.go:339 +0xd0
github.com/go-git/go-git/v5/plumbing/object.(*Commit).StatsContext(0xc03d419590, 0x15d5650, 0xc00002a0f8, 0xc02da78c30, 0x28, 0xc02da78bd0, 0xc00cfb74a0, 0xc1d1253968)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/commit.go:339 +0x10d
github.com/go-git/go-git/v5/plumbing/object.(*Commit).Stats(...)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/commit.go:315
codestats/network.GitCommits.func1(0xc03d419590, 0xc03d419590, 0x0)
	/Users/barat/Codes/GoCodes/codestats/network/git_operation.go:80 +0x19d
github.com/go-git/go-git/v5/plumbing/object.(*commitLimitIter).ForEach(0xc1925b09e0, 0xc1def356d0, 0x15d3d10, 0xc1925b09e0)
	/Users/barat/.gvm/pkgsets/go1.16/global/pkg/mod/github.com/go-git/go-git/v5@v5.4.2/plumbing/object/commit_walker_limit.go:53 +0x84
codestats/network.GitCommits(0x15da918, 0xc00cfb74a0, 0xc00d0e1b90, 0x15da1c8, 0xc0f1190b80, 0x0, 0x0, 0x0, 0x0, 0x0)
```

It seems occurred when I try to call `Stats()` on certain commit, and what I did is pretty simple like: 

```
var allCommits []core.Commit
...
err = logs.ForEach(func(c *object.Commit) error {
		var commit core.Commit
		commit.Message = c.Message
		commit.Sha = c.Hash.String()
		commit.AuthorName = c.Author.Name
		commit.AuthorEmail = c.Author.Email
		commit.AuthorDate = c.Author.When
		commit.CommitterName = c.Committer.Name
		commit.ComitterDate = c.Committer.When
		commit.CommitterEmail = c.Committer.Email
		s, err := c.Stats()
		if err != nil {
			log.Printf("[GitCommits] error when trying to stats logs. ")
		} else {
			for _, v := range s {
				commit.Addition += v.Addition
				commit.Deletion += v.Deletion
			}
		}
		allCommits = append(allCommits, commit)
		return nil
	})
```

I'be noticed there's something going on with `index out of range` but could not able to locate it. 

Is there any solution for this? Or just a direction to point to ?

**Comment by dixler** [comment]
This issue seems to be in an underlying library go-diff.

The following commit fixes this and is in releases >1.2.0

https://github.com/sergi/go-diff/commit/f9beae76ac64a6f92ee8b73e1c96c71ef01a8d49

Regression tests break though when bumping the version.

Had this issue when counting lines changed in a very large file.

**Comment by barats** [comment]
> 

Have you tired it? What is the result?

**Comment by dixler** [comment]
> > 
> 
> 
> 
> Have you tired it? What is the result? 

It seems to fix it. Tests just don't like that the diff output is slightly different than expected. 

You can see the branch I experimented on linked on this issue and test it out.

**Comment by barats** [comment]
> 

Thanks for this feedback.

**Comment by TheSpiritXIII** [comment]
Ran into this same issue:

```
panic: runtime error: index out of range [65533] with length 64796
```

Looks like go-git is still on v1.1.0: https://github.com/go-git/go-git/blob/master/go.mod#L23

Are there any blockers that prevent upgrading to 1.2.0 or 1.3.x?: https://github.com/sergi/go-diff/tags

**Comment by AriehSchneier** [comment]
@TheSpiritXIII yes, 1.2 and 1.3 are broken worse than 1.1: https://github.com/sergi/go-diff/issues/123

**Comment by pjbgf** [comment]
We started a discussion on next steps on replacing `sergi/go-diff`: https://github.com/go-git/go-git/discussions/747.
But haven't got to a decision on it as of yet.

**Comment by AriehSchneier** [comment]
go-git has merged a fix, I tested with this version and all our tests still pass:
```
github.com/sergi/go-diff v1.3.2-0.20230802210424-5b0b94c5c0d3
```
do we have a test that can reproduce the current issue?

**Comment by TheSpiritXIII** [comment]
I discovered the issue by calling `commit.Stats()` on this commit https://github.com/GoogleCloudPlatform/prometheus/commit/0ba3f92c952ae15aaa9901344137c694562324d7 if that helps!

**Comment by barats** [comment]
> sergi/go-diff has merged a fix, I tested with this version and all our tests still pass:
> 
> ```
> github.com/sergi/go-diff v1.3.2-0.20230802210424-5b0b94c5c0d3
> ```
> 
> do we have a test that can reproduce the current issue?

I will find some time to test this issue, probably this weekend or next Monday.

**Comment by FlacoJones** [comment]
Upgrading to `github.com/sergi/go-diff v1.3.2-0.20230802210424-5b0b94c5c0d3` solved the issue for me as well when running `commit.Stats()` across the CommitIterator of this repo: `https://github.com/andi-uni/gain`

Any success on seeing where this upgrade from `go-diff 1.1.0` to `go-diff 1.3.2` might cause regressions elsewhere?

Will continue using and report any errors. Thanks!

**Comment by pjbgf** [comment]
Feel free to propose a bump PR for `github.com/sergi/go-diff` and tag me for a review.
