### ISSUE TITLE
Head() on a worktree returns error "reference not found"

### ISSUE THREAD

**Issue by jameslan** [go-git/go-git#483]
Because the `.git` is a file of content `path/to/source/.git/worktrees/foo`. So It looks for the `packed-refs` file in `path/to/source/.git/worktrees/foo` instead of actual directory `path/to/source/.git`

**Comment by jameslan** [comment]
It seems that it should try the base dir with the content of `commondir`.

For example, in `.git/worktrees/foo`, there's a file `commondir`, whose content is `../..`, pointing to `.git` directory where go-git could find the requested information.

**Comment by mark2185** [comment]
Should be solved by #396

**Comment by jameslan** [comment]
Right. The #396 is to parse the worktree information stored in .git directory. While this issue is reporting that the worktree's attributes(e.g. HEAD) are stored differently

**Comment by aymericbeaumet** [comment]
We are also interested into having worktree support added to go-git. I'd be happy to contribute. I'm not aware of the codebase but this seems non-trivial, any guidance on this from the core maintainers?
