### ISSUE TITLE
Git credentials support

### ISSUE THREAD

**Issue by kassio** [go-git/go-git#490]
## What are credentials?

A git credential is the data required to access a git repository:

- url, which can be split in
    - protocol, like "https"
    - host, like "github.com"
    - path, like "go-git/go-git"
- username
- password

This data can be fetched/saved using configurations in the `gitconfig`.

## What can be configured?

git permits the user to configure some credentials data to be used by default on every repository or some repositores (based on url). The following options are available:

- `username` A default username, if one is not provided in the URL.
- `useHttpPath` By default, Git does not consider the "path" component of an http URL to be worth matching via external helpers. This means that a credential stored for `https://example.com/foo.git` will also be used for `https://example.com/bar.git`. If you do want to distinguish these cases, set this option to `true`.
- `helper` The name of an external credential helper, and any associated options. If there are multiple instances of the `credential.helper` configuration variable, each helper will be tried in turn, and may provide a username, password, or nothing. Once Git has acquired both a username and a password, no more helpers will be tried.
If `credential.helper` is configured to the empty string, this resets the helper list to empty (so you may override a helper set by a lower-priority config file by configuring the empty-string helper, followed by whatever set of helpers you would like). The helper can be:
    - a shell snippet, when it starts with `!`
    
    ```
    # shell snippet
    [credential "https://example.com"]
    	username = your_user
    	helper = "!f() { test \"$1\" = get && echo \"password=$(cat $HOME/.secret)\"; }; f"
    ```
    
    - an absolute path
    
    ```
    # you can also use an absolute path, which will not use the git wrapper
    [credential]
    	helper = "/path/to/my/helper --with-arguments"
    ```
    
    - otherwise, the string `git credential-` is prepended to the string to be executed.
    
    ```
    # run "git credential-foo"
    [credential]
    	helper = foo
    
    # same as above, but pass an argument to the helper
    [credential]
    	helper = "foo --bar=baz"
    
    # the arguments are parsed by the shell, so use shell
    # quoting if necessary
    [credential]
    	helper = "foo --bar='whitespace arg'"
    ```
    
    When a helper is executed, it will have one "operation" argument appended to its command line, which is one of:
    
    - `get` Return a matching credential, if any exists.
    - `store` ****Store the credential, if applicable to the helper.
    - `erase` ****Remove a matching credential, if any, from the helper’s storage.
    
    The details of the credential will be provided on the helper’s stdin stream. The input follows the `git credential` command format which is split into a set of named attributes, with one attribute per line. Each attribute is specified by a key-value pair, separated by an `=` (equals) sign, followed by a newline.
    
    The key may contain any bytes except `=`, newline, or NUL. The value may contain any bytes except newline or NUL.
    
    In both cases, all bytes are treated as-is (i.e., there is no quoting, and one cannot transmit a value with newline or NUL in it). The list of attributes is terminated by a blank line or end-of-file.
    
    Git understands the following attributes:
    
    - `protocol` The protocol over which the credential will be used (e.g., https).
    - `host` The remote hostname for a network credential. This includes the port number if one was specified (e.g., "[[example.com:8088](http://example.com:8088/)](http://example.com:8088/)").
    - `path` The path with which the credential will be used. E.g., for accessing a remote https repository, this will be the repository’s path on the server.
    - `username` The credential’s username, if we already have one (e.g., from a URL, the configuration, the user, or from a previously run helper).
    - `password` The credential’s password, if we are asking it to be stored.
    - `url` When this special attribute is read by git credential, the value is parsed as a URL and treated as if its constituent parts were read (e.g., url=https://example.com would behave as if protocol=https and [[host=example.com](http://host=example.com/)](http://host/%[3Dexample.com/](http://3dexample.com/)[](https://github.com/go-git/go-git/issues/28)) had been provided). This can help callers avoid parsing URLs themselves.

## Steps to be implemented

- [ ]  #491 
- [ ]  Use the credential helper to fetch credentials
- [ ]  Use the credential helper to store credentials

## References

- Related issue requesting the feature: https://github.com/go-git/go-git/issues/28
- `git credential` https://git-scm.com/docs/git-credential
- git credential configuration [https://git-scm.com/docs/gitcredentials](https://git-scm.com/docs/gitcredentials)

**Comment by zong-zhe** [comment]
Hi @kassio ! 😊

I would like to know the current status of this issue. Is it available for use? I am developing a package management tool using go-git that manages third-party libraries through git. I hope to leverage `git credential.helper` to complete the related work of user authority authentication. However, I have not found any content related to `git credential.helper` in go-git

**Comment by kassio** [comment]
Unfortunately, I don't have capacity to continue working that.

**Comment by ahenshaw-work** [comment]
Hi @kassio - I see this has been closed as `completed`, but from what I can see this hasn't been implemented.
Are there plans to implement credential helpers?

**Comment by pjbgf** [comment]
@ahenshaw-work this can be implemented completely out of tree given how the go-git is built. Here's an [example](https://github.com/entireio/git-sync/blob/main/internal/auth/auth.go#L100). I know that there are discussions on that specific implementation being upstreamed into [go-git/x](https://github.com/go-git/x), but not sure when that will happen.
