### ISSUE TITLE
Is it possible to commit in an empty repo?

### ISSUE THREAD

**Issue by Cryspia** [go-git/go-git#499]
Making a new commit requires the repo to have a HEAD or a parent hash provided. However, in a newly inited repo, neither is available thus the commit function call will error. Is it possible to commit in an empty given the current API functions?

**Comment by octothomas** [comment]
Anyone can reply this? The same question as me.

**Comment by pjbgf** [comment]
This is supported since [v5.5.1](https://github.com/go-git/go-git/releases/tag/v5.5.1) by using `&CommitOptions{ AllowEmptyCommits: true }` as per [existing tests](https://github.com/pjbgf/go-git/blob/a513415283c4628259c016587858fe56d7b0fa13/worktree_commit_test.go#L87-L89).

**Comment by AriehSchneier** [comment]
@pjbgf there is a bug in those tests, see my comment here: https://github.com/go-git/go-git/issues/723#issuecomment-1605826825

**Comment by pjbgf** [comment]
@Cryspia example of this working:

```go
package main

import (
	"log"

	"github.com/go-git/go-billy/v5/memfs"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/storage/memory"
)

func main() {
	fs := memfs.New()
	repo, err := git.Init(memory.NewStorage(), fs)
	if err != nil {
		log.Fatal(err)
	}
	workTree, err := repo.Worktree()
	if err != nil {
		log.Fatal(err)
	}

	_, err = workTree.Commit("First commit", &git.CommitOptions{AllowEmptyCommits: true})
	if err != nil {
		log.Fatal(err)
	}
}

```

@AriehSchneier that specific bug does not affect this specific use-case.

**Comment by pjbgf** [comment]
Closing as the functionality work and the bug is being dealt with as part of #723.

Happy to reopen if needed - just drop a message here.

**Comment by Darylddd** [comment]
I'm afraid there is a misunderstanding between "commit in an empty repo" and "allow an empty commit in an repo".

**Comment by pjbgf** [comment]
> I'm afraid there is a misunderstanding between "commit in an empty repo" and "allow an empty commit in an repo".

@Darylddd the example above creates an empty commit on an empty repository. Which is equivalent to:

```bash
$ mkdir /tmp/new-repo
$ cd /tmp/new-repo
$ git init
$ git commit --allow-empty "First commit"
```

Do you mind elaborating what you are trying to achieve please?
