### ISSUE TITLE
Getting line number in commit

### ISSUE THREAD

**Issue by steeve85** [go-git/go-git#50]
Is it possible to get line numbers of commits into go-git?
If not, is it something that is planned to be added in the future?

**Comment by sang-d** [comment]
similar  question, can we get info as
`git log  --oneline --shortstat`

**Comment by sang-d** [comment]
found it, using file stats
https://pkg.go.dev/github.com/go-git/go-git/v5/plumbing/object?tab=doc#FileStats
just in case you use similar thing @steeve85

**Comment by mattetti** [comment]
Note that a similar question was posted in 2018 and AFAIK there isn't a way yet.
