### ISSUE TITLE
Doubt how to do a $ git pull origin master

### ISSUE THREAD

**Issue by jeffotoni** [go-git/go-git#504]
I didn't see how to pass the TOKEN so I can connect to my repository, is there this possibility?
Where does he get the configs to do a pull origin master for example?

the path would be
https://github.com/<user>/<repo> ?
or
ssh://git@github.com/<user>/<repo>

What would be the logic using API to make the command:
$ git pull origin master

Example Go - pull

CheckArgs("<path>")
path := os.Args[1]

// We instantiate a new repository targeting the given path (the .git folder)
r, err := git.PlainOpen(path)
CheckIfError(err)

**Comment by pjbgf** [comment]
For future reference, there are examples for both tokens and username/password:
https://github.com/go-git/go-git/tree/master/_examples/clone/auth/basic
