### ISSUE TITLE
ConfigScoped lose Raw section during merge

### ISSUE THREAD

**Issue by b4nst** [go-git/go-git#508]
When using `repo.ConfigScoped(config.GlobalScope)` or `repo.ConfigScoped(config.SystemScope)` any Raw sections will be lost during the merge.

E.g:

```txtar
> git config --global custom.foo bar
> go run main.go
-- main.go --
package main

import (
	"fmt"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/config"
)

func main() {
	r, _ := git.PlainOpen(".")
	c, _ := r.ConfigScoped(config.GlobalScope)
	c2, _ := config.LoadConfig(config.GlobalScope)

	fmt.Println("merged:", c.Raw.Section("custom").Option("foo"))
	fmt.Println("direct:", c2.Raw.Section("custom").Option("foo"))
}
```

gives:
```shell
merged:
direct: bar
```

**Comment by wlynch** [comment]
Also ran into this - it looks like it's because mergo doesn't know to merge the values Raw section because its only merging things if the dst value is the zero-value - https://go.dev/play/p/ru9OxXgUh2K

**Comment by adityasaky** [comment]
@wlynch in your example, passing in `mergo.WithOverride` seems to solve this issue. https://go.dev/play/p/XgyYmDsgKL7

Documented in the second example here: https://pkg.go.dev/github.com/imdario/mergo#hdr-Usage
