### ISSUE TITLE
CI tests look flaky

### ISSUE THREAD

**Issue by twpayne** [go-git/go-git#51]
`go-git`'s CI often fails with errors like:

```
----------------------------------------------------------------------
##[error]FAIL: <autogenerated>:1: ReceivePackSuite.TestAdvertisedReferencesEmpty

/Users/runner/runners/2.169.1/work/go-git/go-git/plumbing/transport/test/receive_pack.go:35:
    c.Assert(err, IsNil)
... value *net.OpError = &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc0000f6c90), Err:(*os.SyscallError)(0xc00015a000)} ("dial tcp [::1]:49628: connect: connection refused")

OOPS: 28 passed, 1 FAILED
--- FAIL: Test (9.96s)
FAIL
coverage: 10.6% of statements in ./...
FAIL	github.com/go-git/go-git/v5/plumbing/transport/git	11.449s
```

Example: https://github.com/go-git/go-git/pull/47/checks?check_run_id=634865225

This looks like a race between a test server starting up and a client trying to connect to it.

Presumably this is already known (although I could not find any existing open issue for it either here or at https://github.com/src-d/go-git).

Questions:

* Is there any existing effort to fix these tests or any background information about them?
* Would you appreciate help fixing them? I can't promise any solutions, but might be able to have a poke around.

**Comment by mcuadros** [comment]
Sorry about the late response, this was falling since a long time, a no one was able to fix it :/

**Comment by twpayne** [comment]
Closing due to age.
