### ISSUE TITLE
SSH link cannot be pulled

### ISSUE THREAD

**Issue by xun-mi-git** [go-git/go-git#526]
I use windows 11. The system comes with SSH, but an error will be reported when I use SSH to pull the library
`error creating SSH agent:  "SSH agent requested, but could not detect Pageant or Windows native SSH agent"`
I found that it is quoted in this project https://github.com/xanzy/ssh-agent/blob/master/sshagent_windows.go Is there any solution to the problem caused by this library?

**Comment by attolee** [comment]
check this https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro
