### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by psmoros** [go-git/go-git#543]
Hi everyone!

We might have found a security vulnerability.
How can we responsibly disclose it?

Thanks!

**Comment by mvdan** [comment]
cc @mcuadros

**Comment by mvdan** [comment]
Previously https://github.com/go-git/go-git/issues/527 as well.

**Comment by psmoros** [comment]
Thank you @mvdan :))

**Comment by 6543** [comment]
well I think at this point make a pull to fix and hope it get merged ?!?

**Comment by eze-kiel** [comment]
Hello there,
Any update on this ? Has the patch been merged yet ?

**Comment by pjbgf** [comment]
Closing this as we now have a security policy that details contact information in https://github.com/go-git/go-git/security/policy.
