### ISSUE TITLE
Cloning with empty pass on an ECDSA ssh key yields a no password error

### ISSUE THREAD

**Issue by alecholmez** [go-git/go-git#544]
Given this code block:
```go
auth, err := ssh.NewPublicKeysFromFile("git", "path-to-my-key", "")
if err != nil {
    return fmt.Errorf("failed to find private key from file: %w ", err)
}
opts.Auth = auth
opts.InsecureSkipTLS = true
```
We receive this error:
```
failed to find private key from file: bcrypt_pbkdf: empty password
```

The SSH key we are providing does not have a password. The expected behavior would be to allow an empty password with a valid ssh private key file. Are we potentially doing something wrong?

The key provided is valid as we can use it externally with `git`.

**Comment by kcowgill** [comment]
@alecholmez What was the issue, if you happen to remember?

**Comment by alecholmez** [comment]
@kcowgill Sorry! I don't remember but it was along the lines of the ssh key was getting overridden or the perms were incorrect
