### ISSUE TITLE
Inefficient shallow clone

### ISSUE THREAD

**Issue by rickyzhang82** [go-git/go-git#545]
I did a clone performance comparison between `git binary version 2.30.1` and `go git v5.4.2`.

| Metrics                                     | git binary |       go git |
|:--------------------------------------------|-----------:|-------------:|
| Full Cloning time                           |     3.509s | 7.224109872s |
 | Shallow Cloning by Branch                   |     1.375s | 6.808752359s |
| Shallow Cloning by Tag                      |     1.364s | 6.709193530s |
| .git directory size full clone              |   63.85 MB |     67.24 MB |
| .git directory size shallow clone by Branch |    4.57 MB |     63.51 MB |
| .git directory size shallow clone by Tag    |    4.56 MB |     63.50 MB |

All shallow copy is with 1 commit depth. 

In go git shallow test, the size of `.git` folder is still large. It is almost the same size as full clone.

 The go git performance is `4x` slower than git command line. What went wrong?

Here are the options I used in git binary:
```
git clone --depth=1 -b dev-git-repo-db ...
```
Sample benchmark:
```go
func cloneMe(reference plumbing.ReferenceName, url, directory string, t *testing.T) {
	os.RemoveAll(directory)

	testlog.Infof("Cloning repo %v into local directory %v with reference %v ...", url, directory, reference)
	start := time.Now()
	_, err := git.PlainClone(directory, false, &git.CloneOptions{
		URL:           url,
		ReferenceName: reference,
		SingleBranch:  true,
		Depth:         1,
	})
	elapseTime := time.Since(start)
	testutil.AssertTruef(t, nil == err, testlog, "Expect err is nil. But got: %v", err)
	testlog.Infof("Cloning by %v is done! It took %v", reference, elapseTime)
}

func BenchmarkGoGitShallowCloneByBranch(b *testing.B) {
	refByBranch := plumbing.NewBranchReferenceName(branch)
	var t *testing.T = nil
	b.Run("Go Git shallow clone by branch", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			cloneMe(refByBranch, url, directoryByBranch, t)
		}
	})
}
```

**Comment by rickyzhang82** [comment]
I shared [the test script and go code here](https://github.com/rickyzhang82/demo-shallow-clone).

The cloned Git repo is the public FreeBSD source repo -- `https://github.com/freebsd/freebsd-src.git`. The shallow clone sets depth as `1`. Use either the branch `releng/10.0` or the tag `release/10.0.0`.

I saw 3x time reduction in shallow clone by go git. But it is still 6x slower than git binary and has a larger disk consumption in `.git` folder.

| Metrics                                     |                              git binary |           go git |
|:--------------------------------------------|----------------------------------------:|-----------------:|
| Full Cloning time                           |                                2m5.153s | 10m38.560722612s |
| Shallow Cloning by Branch                   |                               0m42.007s |  3m52.281577264s |
| Shallow Cloning by Tag                      |                               0m41.349s |  3m52.043277082s |
| .git directory size full clone              |                                 2.58 GB |          2.58 GB |
| .git directory size shallow clone by Branch |                               198.57 MB |          1.01 GB |
| .git directory size shallow clone by Tag    |                               198.54 MB |          1.01 GB |


Below is the output from `run-time-me.sh`

```azure
***************************************************************************************
 
 
Full clone by git binary
 
 
***************************************************************************************
Cloning into '/tmp/repo-git-full'...
remote: Enumerating objects: 4689957, done.
remote: Counting objects: 100% (875/875), done.
remote: Compressing objects: 100% (581/581), done.
remote: Total 4689957 (delta 349), reused 689 (delta 286), pack-reused 4689082
Receiving objects: 100% (4689957/4689957), 2.26 GiB | 31.71 MiB/s, done.
Resolving deltas: 100% (3241391/3241391), done.
Updating files: 100% (88650/88650), done.

real	2m5.153s
user	6m25.011s
sys	0m48.245s
***************************************************************************************
 
 
Shallow clone by branch by git binary
 
 
***************************************************************************************
Cloning into '/tmp/repo-git-branch'...
remote: Enumerating objects: 60954, done.
remote: Counting objects: 100% (60954/60954), done.
remote: Compressing objects: 100% (51621/51621), done.
Receiving objects: 100% (60954/60954), 181.85 MiB | 11.98 MiB/s, done.
remote: Total 60954 (delta 12594), reused 32727 (delta 6409), pack-reused 0
Resolving deltas: 100% (12594/12594), done.
Updating files: 100% (57174/57174), done.

real	0m42.007s
user	0m13.148s
sys	0m4.617s
***************************************************************************************
 
 
Shallow clone by tag by git binary
 
 
***************************************************************************************
Cloning into '/tmp/repo-git-tag'...
remote: Enumerating objects: 60979, done.
remote: Counting objects: 100% (60979/60979), done.
remote: Compressing objects: 100% (51645/51645), done.
Receiving objects: 100% (60979/60979), 181.83 MiB | 12.07 MiB/s, done.
remote: Total 60979 (delta 12594), reused 32819 (delta 6410), pack-reused 0
Resolving deltas: 100% (12594/12594), done.
Note: switching to 'e3ff8788aa4381f45f5c39efd99c9cbf1b174b5a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (57197/57197), done.

real	0m41.349s
user	0m13.584s
sys	0m5.087s
***************************************************************************************
 
 
Clone by go git
 
 
***************************************************************************************
2022/06/10 11:18:13.153555 demo-shallow-clone/main.go:60: Go Git shallow clone by branch
2022/06/10 11:18:13.153736 demo-shallow-clone/main.go:31: Cloning repo https://github.com/freebsd/freebsd-src.git into local directory /tmp/repo-go-git-branch with reference refs/heads/releng/10.0 ...
2022/06/10 11:22:05.435351 demo-shallow-clone/main.go:49: Cloning by refs/heads/releng/10.0 is done! It took 3m52.281577264s
2022/06/10 11:22:05.435383 demo-shallow-clone/main.go:66: Go Git shallow clone by tag
2022/06/10 11:22:05.435395 demo-shallow-clone/main.go:31: Cloning repo https://github.com/freebsd/freebsd-src.git into local directory /tmp/repo-go-git-tag with reference refs/tags/release/10.0.0 ...
2022/06/10 11:25:57.478685 demo-shallow-clone/main.go:49: Cloning by refs/tags/release/10.0.0 is done! It took 3m52.043277082s
2022/06/10 11:25:57.478712 demo-shallow-clone/main.go:71: Go Git shallow clone by tag
2022/06/10 11:25:57.478723 demo-shallow-clone/main.go:31: Cloning repo https://github.com/freebsd/freebsd-src.git into local directory /tmp/repo-go-git-full with reference  ...
2022/06/10 11:36:36.039461 demo-shallow-clone/main.go:49: Cloning by  is done! It took 10m38.560722612s
```

**Comment by mausch** [comment]
I got confirmation from AWS support that CodeBuild uses go-git and therefore their service is affected by this issue.
We have a repo with 20K commits that takes 100-150 seconds to shallow clone in CodeBuild. It takes 8s on my local machine.
If anyone using AWS sees this please open a support ticket asking for AWS to spend some resources to help fix this.

**Comment by pjbgf** [comment]
@rickyzhang82 you are not comparing apples with apples. By default go-git will download all tags, and so will their objects. In order to avoid that, you need to add `Tags: git.NoTags` to your `CloneOptions`.

Once that is done, you will notice that the amount of files will be fairly close to one another:
![image](https://user-images.githubusercontent.com/5452977/207961635-a3ec7db2-f6ea-49aa-bf54-c5d496243ee2.png)

And so will the size in bytes:
```
$du -s -b freebsd-src-gogit/.git
198295967       freebsd-src-gogit/.git
$ du -s -b freebsd-src-cli/.git
198544276       freebsd-src-cli/.git
```

**Comment by rickyzhang82** [comment]
@pjbgf 

My work requires me to do shallow clone a Git project by tag or branch name. I doubt using no tag or saving it to memfs could meet my need. In the end, I have to ditch go-git and rely on Git C implementation, instead.

I bet most of the use case of shallow clone is for DevOps build process which disregards all Git history objects and spend the least resources (time and space) to download the project. 

In [my benchmark test](https://github.com/rickyzhang82/demo-shallow-clone/blob/master/main.go#L39-L44), I explicitly specify `depth = 1`. So it should imply a shallow clone without downloading all tags as Git C implementation does. It is counterintuitive to add NoTags options.

```
		_, cloneErr = git.PlainClone(directory, false, &git.CloneOptions{
			URL:           url,
			ReferenceName: reference,
			SingleBranch:  true,
			Depth:         1,
		})
```

**Comment by maxless** [comment]
@pjbgf So if you use NoTags, will go-git respect the ReferenceName parameter when cloning or not?

**Comment by pjbgf** [comment]
@maxless yes, it will. The example above clones a single branch when `ReferenceName` is a remote target branch, however that could be a tag for example.

**Comment by maxless** [comment]
@pjbgf Thanks!
