### ISSUE TITLE
Can't use authentication with HTTP package

### ISSUE THREAD

**Issue by slashtechno** [go-git/go-git#546]
I am using the Go package `net/http` and I am also using `go-git`
The following code does not work as `http` is already declared as a package.
```go
Auth: &http.BasicAuth{
			Username: "abc123", // anything except an empty string
			Password: "github_access_token",
		},
```

Any solutions?

**Comment by ishanjain28** [comment]
@slashtechno Use aliases. 

Try changing `net/http` import to `nhttp "net/http"` 

See, https://golangbyexample.com/import-same-package-name-golang/

**Comment by slashtechno** [comment]
I ended up importing `github.com/go-git/go-git/v5/plumbing/transport/http` as `githttp`. I think importing `net/http` as `nhttp` may have been slightly better.
