### ISSUE TITLE
memory out and system ban process

### ISSUE THREAD

**Issue by drtechco** [go-git/go-git#547]
hello guys!
i am try gitlab sync gitlab,pull and push repo,but not worked now, system killed my process when  push 
``` 
go tool  pprof -alloc_space  http://127.0.0.1:8080/debug/pprof/heap
```
Showing top 10 nodes out of 19
      flat  flat%   sum%        cum   cum%
10912.14MB 77.99% 77.99% 10912.14MB 77.99%  bytes.makeSlice
 3030.78MB 21.66% 99.65% 10060.58MB 71.90%  github.com/go-git/go-git/v5/plumbing/format/packfile.(*Parser).get
       1MB 0.0071% 99.66%  7801.01MB 55.75%  github.com/go-git/go-git/v5/plumbing/format/packfile.(*Scanner).copyObject
         0     0% 99.66%  2879.04MB 20.58%  bytes.(*Buffer).Grow (inline)
         0     0% 99.66%  7800.01MB 55.75%  bytes.(*Buffer).ReadFrom
         0     0% 99.66%   242.09MB  1.73%  bytes.(*Buffer).Write
         0     0% 99.66% 10912.14MB 77.99%  bytes.(*Buffer).grow
         0     0% 99.66% 13955.61MB 99.74%  github.com/go-git/go-git/v5/plumbing/format/packfile.(*Parser).Parse
         0     0% 99.66%  2053.99MB 14.68%  github.com/go-git/go-git/v5/plumbing/format/packfile.(*Parser).indexObjects
         0     0% 99.66%  5747.52MB 41.08%  github.com/go-git/go-git/v5/plumbing/format/packfile.(*Parser).readData

```
	workTree, err := repo.Worktree()
	if err != nil {
		return err
	}
	err = workTree.Pull(&git.PullOptions{
		RemoteName:    "from",
		ReferenceName: plumbing.ReferenceName(fmt.Sprintf("refs/heads/%s", fromBranch.Name)),
		SingleBranch:  true,
		Auth: &http.BasicAuth{
			Username: "gl2gl_sync", // yes, this can be anything except an empty string
			Password: p.FromAccessToken,
		},
	})
	if err != nil {
		return err
	}
	refSpecs := []config.RefSpec{
		config.RefSpec(fmt.Sprintf("+refs/heads/master:refs/heads/%s", fromBranch.Name)),
	}
	err = repo.Push(&git.PushOptions{
		RefSpecs:   refSpecs,
		RemoteName: "to",
		Auth: &http.BasicAuth{
			Username: "gl2gl_sync", // yes, this can be anything except an empty string
			Password: p.ToAccessToken,
		},
	})
```

**Comment by drtechco** [comment]
fine! i find solution,
old code 
```
	repo, err := git.Init(memory.NewStorage(), memfs.New())
```
new code 
```
	storageDir := path.Join(configs.TempDir, "storage")
	err := p.ensureDir(storageDir)
	if err != nil {
		return err
	}
	workTreeDir := path.Join(configs.TempDir, "worktree")
	err = p.ensureDir(workTreeDir)
	if err != nil {
		return err
	}
	p.logger.
		WithField("FromProject", p.ShortProject(from)).
		WithField("ToProject", p.ShortProject(to)).
		WithField("FromBranch", p.ShortBranch(fromBranch)).
		Debug("开始推送分支")

	storage := filesystem.NewStorage(osfs.New(storageDir), cache.NewObjectLRUDefault())
	repo, err := git.Init(storage, osfs.New(workTreeDir))
```

**Comment by Dong1999heo** [comment]
?
