### ISSUE TITLE
does go-git support ProxyCommand or ProxyJump?

### ISSUE THREAD

**Issue by rafiqkattangere** [go-git/go-git#566]
I see the host name and port over rides are picked by the go-git client. But I dont think ProxyCommand or ProxyJump are considered.
Does anyone have alternatives how we can use ssh over 443 and bypass the proxy behind the firewall using ProxyCommand or ProxyJump.

**Comment by Nomango** [comment]
The latest version seems to have added support for SSH proxy, allowing you to specify a proxy when cloning.

e.g.

```go
git.CloneContext(ctx, memory.NewStorage(), nil, &git.CloneOptions{
    // ...
    ProxyOptions: transport.ProxyOptions{ URL: "socks5://127.0.0.1:1234" },
})
```

However, it is not possible to specify a custom proxy dialer. The proxy must be a URL.

**Comment by hegde-prashant** [comment]
SSH connection to GitHub happening via port 443. Is there a way to specify 'http' proxy?
