### ISSUE TITLE
how can use git merge for go-git

### ISSUE THREAD

**Issue by ruanlianjun** [go-git/go-git#570]
how can use git merge for go-git

**Comment by zhaopengme** [comment]
go-git  merge 很弱,仅能支持不冲突的 merge.

**Comment by ruanlianjun** [comment]
@zhaopengme can you give me a  example,thk

**Comment by zhaopengme** [comment]
https://github.com/go-git/go-git/blob/master/_examples/pull/main.go   这个就可以
