### ISSUE TITLE
Where is 'git show' implemented?

### ISSUE THREAD

**Issue by Marakai** [go-git/go-git#577]
The compatibility table has a tickmark next to "(git) show", yet I see no code, methods or funcs that actually implement this, never mind with all its myriad options. Am I missing something and its equivalent is actually "spread out" over various other methods that return object/blob/tag/commit info?

**Comment by eze-kiel** [comment]
It looks like you can use `r.CommitObject` to mimic `git show`

https://github.com/go-git/go-git/blob/master/_examples/commit/main.go#L64

**Comment by Marakai** [comment]
Yeah, that's the simplest case (`-s`), but doesn't cover the rest of the options.

**Comment by Marakai** [comment]
I have a case where I need to do something like 

`git log --date-order --reverse --format=oneline --merges <somehash>..HEAD` 

(no, seriously, I do!) The current implementation only offers a fraction of those and from looking at the results, they're incomplete such that I can't easily plugin those filters post-facto.

**Comment by Shaked** [comment]
@eze-kiel @Marakai it's pretty old but do you know how to achieve `git show --name-only` to show only the actual changed files and ignore the rest?
