### ISSUE TITLE
Log in reverse order

### ISSUE THREAD

**Issue by wayneashleyberry** [go-git/go-git#60]
I'm looking for the equivalent of `git log --reverse`, or another way to get _all_ commits _starting with the first_. `LogOptions` doesn't seem to have anything like this.

**Comment by mcuadros** [comment]
The only way to traverse a history is from HEAD to root, so without knowing exactly what makes `--reverse`, I guess just returns the log in reverse other after computing normally.

**Comment by wayneashleyberry** [comment]
Do you think I should continue gathering all of the commits and reversing them myself @mcuadros?

**Comment by mcuadros** [comment]
Just use `Log`(https://github.com/go-git/go-git/blob/master/_examples/log/main.go#L37), save to a slice and read it in reverse order.

**Comment by Naatan** [comment]
Ran into this same issue. Of course you can save it to a slice and revert it, but that feels like unnecessary busywork. Would be great if this lib supported it natively.
