### ISSUE TITLE
git blame panic: contents and commits have different length

### ISSUE THREAD

**Issue by williamfzc** [go-git/go-git#603]
```go
func TestAA(t *testing.T) {
	abs, _ := filepath.Abs("F:\\workspace\\github\\go-git")
	repo, err := git.PlainOpen(abs)
	if err != nil {
		panic(err)
	}
	head, err := repo.Head()
	if err != nil {
		panic(err)
	}
	targetCommit, err := repo.CommitObject(head.Hash())
	if err != nil {
		panic(err)
	}

	_, err = git.Blame(targetCommit, "remote.go")
	if err != nil {
                // PANIC!!!
		panic(err)
	}
}
```

panic happened when calling `git.Blame`

```text
panic: contents and commits have different length [recovered]
	panic: contents and commits have different length
```

It will happened also in `work_tree_test.go`.
Looks like it can not handle extra empty line at the end of file.

In git blame:

![image](https://user-images.githubusercontent.com/13421694/198298366-2e5a72dc-5cb7-4f6a-8acc-c2f4efab9967.png)

But actually:

![image](https://user-images.githubusercontent.com/13421694/198298475-cc7e1919-ea1b-4505-b26d-9e4f96066d4f.png)

Tested on Windows and WSL.

## guess

```go
func newLines(contents []string, commits []*object.Commit) ([]*Line, error) {
	lcontents := len(contents)
	lcommits := len(commits)

	if lcontents != lcommits {
		fmt.Printf("c vs c: %d, %d", lcontents, lcommits)
...
```

Output:

```go
=== RUN   TestAA
c vs c: 1430, 1397--- FAIL: TestAA (1.97s)
```

lcommits seems not correct.

**Comment by williamfzc** [comment]
ok it causes by: 
https://github.com/go-git/go-git/blob/08cffa1efade914020497a73907763e8d3707a77/references.go#L105

**Comment by tarimoe** [comment]
I also meet this issue too, any official fix for this ?

**Comment by tarimoe** [comment]
> ok it causes by:
> 
> https://github.com/go-git/go-git/blob/08cffa1efade914020497a73907763e8d3707a77/references.go#L105
> 
> When it has multi parents, itself will not be added to result list, which causes some commits lost.
> 
> [williamfzc@188480d](https://github.com/williamfzc/go-git/commit/188480dfdd4e88057d4493e6c85d5ce4f0e65d23)
> 
> This fix looks fine.

This fix me too~
Thanks

**Comment by pjbgf** [comment]
@williamfzc would you be keen to propose your changes as a PR? If so, tag me and I will review it for you.

**Comment by williamfzc** [comment]
@pjbgf 

Cool I have submitted one: 
https://github.com/go-git/go-git/pull/751
