### ISSUE TITLE
object.Commit.Patch{,Context} causes nil dereference

### ISSUE THREAD

**Issue by ddevault** [go-git/go-git#61]
If you use `object.Commit.Patch(nil)`, a nil dereference is raised. Obvious though this may seem, there doesn't seem to be a more obvious way of obtaining a diff for an initial commit.

**Comment by ddevault** [comment]
Tangentally related: this function would be better off if it were called Diff, and Patch would be reserved for something which generated `git format-patch`-like output.

**Comment by mcuadros** [comment]
As a workaround, you can make `Tree.Patch(new(object.Tree))` over the tree of the initial commit.

**Comment by mcuadros** [comment]
The reason because `Commit.Patch` is called like this it returns the actual patch. It's a shortener to `Commit.Tree().Diff().Patch()` if you want a diff you have `Tree.Diff()` what returns a slice of the changes of the commit.

**Comment by ddevault** [comment]
Thanks!
