### ISSUE TITLE
How i to get add multiplies Files in go-git

### ISSUE THREAD

**Issue by nnowaf** [go-git/go-git#610]
I'm wondering how to use syntax git add file-1 file-2 file-3 and I'm trying to use ` _, err = w.Add(".gitlab src")`. And give an error like this `entry not found`

**Comment by pjbgf** [comment]
@nnowaf you need to pass a file at a time to `Add`, here's an example:

```
	wt, err := g.repository.Worktree()
	if err != nil {
		return "", err
	}

	status, err := wt.Status()
	if err != nil {
		return "", err
	}

	for file := range status {
		_, _ = wt.Add(file)
	}
```

**Comment by yfwz100** [comment]
> @nnowaf you need to pass a file at a time to `Add`, here's an example:
> 
> ```
> 	wt, err := g.repository.Worktree()
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	status, err := wt.Status()
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	for file := range status {
> 		_, _ = wt.Add(file)
> 	}
> ```

It does work. However, calling `wt.Add()` will call `wt.Status()`, which is a costly operation. It'd better expose a method that can add multiple paths.

**Comment by yfwz100** [comment]
It seems that #993 may help adding files efficiently in a large repo.

**Comment by pjbgf** [comment]
@yfwz100 thanks for that, so I will be closing this for the time being. We can always open a new issue in the future if needed.
