### ISSUE TITLE
CreateBranch does not work correctly

### ISSUE THREAD

**Issue by behinddwalls** [go-git/go-git#632]
`repository.CreateBranch` only adds the branch to `.git/config` but doesn't create the local ref which causes git to not find it...

```
err := repository.CreateBranch(&config.Branch{
		Name:   name,
		Remote: ".",
		Merge:  plumbing.NewBranchReferenceName(upstream),
	})
w, _ := repository.Worktree()
err = w.Checkout(&git.CheckoutOptions{
		Branch: plumbing.NewBranchReferenceName(name),
	})
```

This results in error `Error: failed to checkout branch: reference not found`. After checking the `.git` folder..it seems only config was updated but no refs were created for new branch

**Comment by zacharysyoung** [comment]
This tripped me up, too.  I just started using this library today, so I may be missing something else, but...

Looking at the example for branching, I think I see the crucial bit is that we need to create a new reference for our branch that points at some existing hash and then pass the new ref to the Storer to set the reference.  From that test:

```go
// Create a new plumbing.HashReference object with the name of the branch
// and the hash from the HEAD. The reference name should be a full reference
// name and not an abbreviated one, as is used on the git cli.
//
// For tags we should use `refs/tags/%s` instead of `refs/heads/%s` used
// for branches.
ref := plumbing.NewHashReference("refs/heads/my-branch", headRef.Hash())

// The created reference is saved in the storage.
err = r.Storer.SetReference(ref)
CheckIfError(err)
```

That test shows itself to be about 6 yrs old and doesn't use CreateBranch(), so the config does not get updated.

I don't know exactly what to do, but this creates a new branch from my current HEAD, for me:

```go
headRef, err := r.Head()
must(err)

branchName := plumbing.NewBranchReferenceName(soLabel)
err = r.CreateBranch(&config.Branch{
	Name:   soLabel,
	Remote: "origin",
	Merge:  branchName,
})
must(err)

ref := plumbing.NewHashReference(branchName, headRef.Hash())
err = r.Storer.SetReference(ref)
must(err)
```

I find the documentation for CreateBranch, "CreateBranch creates a new Branch", misleading.
