### ISSUE TITLE
git remote update

### ISSUE THREAD

**Issue by cooperspencer** [go-git/go-git#636]
Is there a way to run a `git remote update` on a bare repo with go-git?

I have a bunch of repos on a server, cloned as bare for backup reasons, and I would like to keep them up-to-date.

**Comment by flylan** [comment]
`
	repoPath := "/path/to/local/mirror/repo.git"

	r, err := git.PlainOpen(repoPath)
	if err != nil {
		fmt.Println(err)
		return
	}

	remoteRefs, err := r.Remotes()
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, remoteRef := range remoteRefs {
		err := remoteRef.Fetch(&git.FetchOptions{
			Auth: auth,
		})
		if err != nil && err != git.NoErrAlreadyUpToDate {
			fmt.Println(err)
		}
	}

	fmt.Println("git remote update sucess")
`

**Comment by pjbgf** [comment]
Closing as per answer above and lack of activity.
