### ISSUE TITLE
ResolveRevision fails on tag name with at-sign (@)

### ISSUE THREAD

**Issue by magnus-longva-bouvet** [go-git/go-git#640]
This method fails when trying to resolve a tag name which contains an at-sign. 

https://github.com/go-git/go-git/blob/736622fb5d9a058a887667d57c91dc1b58aca6ea/repository.go#L1427

[My fork of git-fixtures/basic](https://github.com/magnus-longva-bouvet/basic/tree/master) has a tag, `this-tag-contains@at-sign`, which points at 6ecf0ef2c2dffb796033e5a02219af86ec6584e5. If I try to resolve this tag, I get an error `Revision invalid : reference must be defined once at the beginning`. Reproduced with `git-go` version 5.4.2 and 5.5.1.

**Comment by magnus-longva-bouvet** [comment]
Seems a duplicate of this https://github.com/go-git/go-git/issues/204

**Comment by pjbgf** [comment]
Closing this in favour of #204.
