### ISSUE TITLE
When accessing cloudlab git server over https invalid pkt-len found

### ISSUE THREAD

**Issue by gcstang** [go-git/go-git#641]
When I'm trying use PlainClone over https on a cloudlab server I'm seeing 'invalid pkt-len found' 
This uses a token for authentication in the form of
https://user:token@host.com

From my command line this works with git just not go-git.

**Comment by blmayer** [comment]
I was getting this same error, the issue here was getting the body gziped so the packp parser failed, so I solved it by uncompressing the gziped body before decoding the upload-pack request. Check if this is your case as well.

**Comment by mleku** [comment]
```go
	var rdr io.Reader
	if rdr, err = gzip.NewReader(r.Body); chk.E(err) {
		http.Error(w, err.Error(), 400)
		return
	}
	if err = upr.Decode(rdr); chk.E(err) {
		http.Error(w, err.Error(), 400)
		return
	}
``` 
fixes the problem
