### ISSUE TITLE
ssh: unable to ignore host key auth callback 

### ISSUE THREAD

**Issue by aymanbagabas** [go-git/go-git#654]
Hi,

The changes introduced in https://github.com/go-git/go-git/commit/c35b8082c863f2106de1c3c95ba9ed21d30f9371 breaks the ability to ignore the client host key check. In our case, we're using `ssh.InsecureIgnoreHostKey()` for integration testing where we don't care about validating the host key. The changes made in the commit deprecate the `HostKeyCallbackHelper` interface and don't provide any workaround.

Implementing a `ssh.AuthMethod` with a custom `HostKeyCallback` won't work either since the associated `ssh.ClientConfig` will be overwritten by [`ssh.SetConfigHostKeyFields()`](https://github.com/go-git/go-git/commit/c35b8082c863f2106de1c3c95ba9ed21d30f9371#diff-4b7927140f2bd6fe4030126982cb323cf2b49656e75e7f235ca1fbf0336aadf4R124-R128) when establishing the connection.

Before these changes were introduced, you could pass a `HostKeyCallbackHelper` to any ssh AuthMethod and it will set the `HostKeyCallback` function to be used to validate the host key.

```go
	pks, _ := ssht.NewPublicKeysFromFile("git", filepath, "")
	pks.HostKeyCallbackHelper = ssht.HostKeyCallbackHelper{
	 	HostKeyCallback: ssh.InsecureIgnoreHostKey(),
	}
	err = r.Push(&git.PushOptions{
		RemoteName: "origin",
		Auth:       pks,
	})
```

I tried wrapping the `PublicKeys` AuthMethod and modifying the `HostKeyCallback`, but it gets [overwritten](https://github.com/go-git/go-git/commit/c35b8082c863f2106de1c3c95ba9ed21d30f9371#diff-4b7927140f2bd6fe4030126982cb323cf2b49656e75e7f235ca1fbf0336aadf4R124-R128) before the connection happens.

```go
type pkAuthMethod struct {
	*ssht.PublicKeys
}

func (p *pkAuthMethod) ClientConfig() (*ssh.ClientConfig, error) {
	cc, err := p.PublicKeys.ClientConfig()
	if err != nil {
		return nil, err
	}
	cc.HostKeyCallback = ssh.InsecureIgnoreHostKey()
	return cc, nil
}

func main() {
	pks, _ := gssh.NewPublicKeysFromFile("git", pkPath, "")
	auth := &pkAuthMethod{pks}
	err = r.Push(&git.PushOptions{
		RemoteName: "origin",
		Auth:       auth,
	})
}
```

Related: https://github.com/go-git/go-git/issues/411
Related: https://github.com/go-git/go-git/issues/431

**Comment by crenshaw-dev** [comment]
Argo CD also relies on the `HostKeyCallback` field. https://github.com/argoproj/argo-cd/pull/11893
