### ISSUE TITLE
Shallow cloning by timestamp?

### ISSUE THREAD

**Issue by ggambetti** [go-git/go-git#656]
Currently `go-git` exposes shallow clones via `CloneOptions.Depth` to specify the number of commits to retrieve. It appears that the underlying plumbing required to support timestamp ranges is implemented (eg: [DeepenSince](https://github.com/go-git/go-git/blob/5dabd83e3712e2554745c736b55df405a0ba4f33/plumbing/protocol/packp/capability/capability.go#L148)), but it is not propagated through for `CloneOptions`. It seems relatively trivial to use the functionality in `remote.go` ([like `Depth`](https://github.com/go-git/go-git/blob/5dabd83e3712e2554745c736b55df405a0ba4f33/remote.go#L1071-L1076)).

Does it seem reasonable that support could be added in a week or two, and if so, would a PR implementing `Since` support be accepted?

**Comment by pjbgf** [comment]
@ggambetti that sounds good, cc me in the PR and I will review it.

**Comment by ggambetti** [comment]
As a heads up to anyone who might be waiting for this: I have deprioritized the work, and am unlikely to do it any time soon (if at all).
