### ISSUE TITLE
go-git checkout failing with reference not found

### ISSUE THREAD

**Issue by brooksyott** [go-git/go-git#664]
I'm just starting to use the go-git library and so far it looks very promising. However, I'm trying to do a basic checkout of an existing branch and it is failing with "reference not found". I have a simple repository, with several branches but one is "main" and another is "testoffmain". Cloning, pulling and fetching the github repo work without issues.

Getting a hash for the branch seems to work fine as well:

  
     repo, err := git.PlainOpen(localGitRepo)
     w, err := repo.Worktree()

     // Clone, Fetch, Pull all work, when I'm on the main branch

    // Returns a valid hash
    headRef, err := repo.Head()
    newHashRef := plumbing.NewHashReference("refs/heads/testoffmain", headRef.Hash())
    hashRef := plumbing.NewHash(newHashRef.String())
    fmt.Printf("HashRef: %s", hashRef.String())   // Successfully displays the hash

    // Returns a valid hash
    revision := "origin/testoffmain"
    revHash, err := repo.ResolveRevision(plumbing.Revision(revision))
    fmt.Printf("HashRef: %s\n", revHash.String())

    // Checkout fails with "reference not found"
    referenceName := plumbing.ReferenceName("refs/heads/testoffmain")
    err = w.Checkout(&git.CheckoutOptions{
        Branch: referenceName,
        Force:  true})
    if err != nil {
        fmt.Printf("%s:  Checkout: Cound not open local repository, Error: %s\n", project.LocalRepo, err)
        return err
    }

I've search around, and oddly can't find this simple usecase, so I'm assuming I'm doing something basic wrong. I'm using github.com/go-git/go-git/v5 v5.5.2

I've tried a variety of options in
`
    referenceName := plumbing.ReferenceName("refs/heads/testoffmain")

   referenceName := plumbing.ReferenceName("testoffmain")
   referenceName := plumbing.ReferenceName("origin/testoffmain")
   referenceName := plumbing.ReferenceName("refs/origin/testoffmain")
   referenceName := plumbing.ReferenceName("refs/remotes/origin/testoffmain")
   referenceName := plumbing.ReferenceName("refs/remotes/testoffmain")
`

As I test, I tried copying .git/refs/remote/origin/testoffmain to .git/refs/head/testoffmain and I can the checkout to work, but then other issues occur.

**Comment by sonicfly** [comment]
I run into the same issue, and with some digging and code reading, seems like the "Branch" argument is very ambiguous: if "Create" is true, the code will checkout the "Hash" value specified to create a branch named by "Branch" argument;
but if "Create" is false, the code will try to checkout the "Hash" value (if presented) or the "Branch" (if "Hash" is not presented").
For your case, it seems like you want to checkout a remote branch to create a new local branch, you have to set "Create" to true for that; but if you local branch exists already, that will give you an branch existing error.
It is a little bit different from the git command line behavior and very confusing.

**Comment by aleksrosz** [comment]
Same issue, questions in https://github.com/go-git/go-git/issues/481 and https://github.com/go-git/go-git/issues/587

For me, something like this works:

```
		r, err := git.PlainOpen("./" + projectName)
		if err != nil {
			fmt.Println(err)
		}

		w, err := r.Worktree()
		if err != nil {
			fmt.Println(err)
		}

		revision := "origin/dev"
		revHash, err := r.ResolveRevision(plumbing.Revision(revision))
		fmt.Printf("HashRef: %s\n", revHash.String())

		//Checkout branch
		err = w.Checkout(&git.CheckoutOptions{
			Hash:   plumbing.NewHash("34f34e72df9a6a789dad275dbd2361358725f9f123d7"),
			Branch: "devtestlocal",
			Force:  false,
			Create: true,
		})
		fmt.Println(err)
	}
```
The problem is that I don't see this branch in my directory:
git branch
* (no branch)
  master

I even can commit changes using this example https://github.com/go-git/go-git/blob/master/_examples/commit/main.go but still using git cli and can't see my branch and any changes on branch "devtestlocal" but it makes everything on HEAD.

**Comment by aleksrosz** [comment]
Fix in https://github.com/go-git/go-git/issues/279
https://github.com/go-git/go-git/issues/241

**Comment by aryan29** [comment]
Is the issue really resolved , I am still facing this issue
