### ISSUE TITLE
Can't build a project on Windows with `go-git:v5.5.2` due to gcc

### ISSUE THREAD

**Issue by mih-kopylov** [go-git/go-git#666]
Environment:
* Windows 10x64
* golang 1.19
* https://jmeubank.github.io/tdm-gcc/ installed
* MinGW mingw32-gcc-g++ installed
* > gcc --version
  > gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0

```
> go install -x .
cd C:\Project
git status --porcelain
cd C:\Project
git -c log.showsignature=false show -s --format=%H:%ct
WORK=C:\Users\MIKHAI~1.KOP\AppData\Local\Temp\go-build3376227082
mkdir -p $WORK\b252\
cd C:\Users\mikhail.kopylov\go\pkg\mod\github.com\pjbgf\sha1cd@v0.2.3\cgo
TERM='dumb' CGO_LDFLAGS='"-g" "-O2"' "C:\\Program Files\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "$WORK\\b252\\" -importpath github.com/pjbgf/sha1cd/cgo -- -I "$WORK\\b252\\" -g -O2 "C:\\Users\\mikhail.kopylov\\go\\pkg\\mod\\github.com\\pjbgf\\sha1cd@v0.2.3\\cgo\\sha1.go" "C:\\Users\\mikhail.kopylov\\go\\pkg\\mod\\github.com\\pjbgf\\sha1cd@v0.2.3\\cgo\\ubc_check.go"
go build github.com/pjbgf/sha1cd/cgo: C:\Program Files\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2
```

It is probably related to #624, but none of the recommendations there help.

A couple questions
1. What am I doing wrong?
2. Can go-git please exclude github.com/pjbgf/sha1cd@v0.2.3 dependency to avoid all these dancings with gcc etc?

**Comment by mih-kopylov** [comment]
Found out #637 that answers question 2, so looking forward to seeing it implemented and merged to master.

Unfortunately it's still not clear what could be wrong with "exit status 2"

**Comment by yangzhen0512** [comment]
I downgrade to v5.4.2 and there is no cgo.

**Comment by mih-kopylov** [comment]
Yeah, I had to do the same.

**Comment by hiddeco** [comment]
Should be solved with https://github.com/go-git/go-git/releases/tag/v5.6.0
