### ISSUE TITLE
config can't parse multi-line values

### ISSUE THREAD

**Issue by MichaelMure** [go-git/go-git#667]
I found out that go-git is unable to parse a config with a multi-line value, like so:
```
[alias]
    myalias = "!f(){ \
        echo hello; \
        };f"
```

This is however explicitely valid as per https://git-scm.com/docs/git-config#_syntax

https://github.com/go-git/gcfg/pull/1 and https://github.com/go-git/gcfg/pull/2 address this issue.

**Comment by pjbgf** [comment]
@MichaelMure do you mind creating a PR with the dependency bump please?
