### ISSUE TITLE
Commit.Patch() has dramatically different performance on two nearly-identical repos

### ISSUE THREAD

**Issue by ed-sulli** [go-git/go-git#67]
# Describe the bug

I have two repos called **ABC** and **ABC-clone** and they are ostensibly equivalent (please see below for a detailed comparison). When I invoke `Commit.Patch()` (https://github.com/go-git/go-git/blob/master/plumbing/object/commit.go#L101-L107) on both repos in a server-side pre-receive hook on GitHub Enterprise using the same arguments, the performance is dramatically slower for **ABC** compared to **ABC-clone**.  During my most recent measurement, the execution of `Commit.Patch()` for **ABC** took `4 seconds 228 milliseconds 541 microseconds`, whereas the execution for **ABC-clone** took only `59 milliseconds 463 microseconds`.

**Does anyone know why go-git might have different performance on my two ostensibly equivalent repos?** This slow performance will unfortunately prohibit me from using go-git for my specific use case.

# Expected behavior

I'd expect go-fit to have similar fast performance for both repos (< 1 second for my particular commit). I would not expect Gitleaks to take > 3 seconds for the **ABC** repo.

# Basic info

 - Env: Pre-receive hook FireJail/chroot sandboxgith for GitHub Enterprise server hosted on Google Cloud
 - Host kernel: Linux 4.9.0-12-amd64
 - Host architecture: x86-64
 - Host OS: Debian GNU/Linux 9.12 (stretch)
 - Go-git Version: v5.0.0

# Additional context

### Are the repos actually the same?
* **Similarity**: when I visit the repos in the browser, they appear to be the same, because they both have 3,163 commits and 330 branches. The repos have the same content (ie. `git show COMMIT_ID` will return the same output for both repos).
* **Difference**: when I investigate the server-side instances of the repos and I execute `echo -e $(du -sh *)` in the `.git` directory, the repos appear quite different. The **ABC** repo (slow) has a server-side .git/objects directory of 1.0 MB whereas the **ABC-clone** repo (fast) has a server-side .git/objects size of 11.5 MB.....so I'm very confused. I would have expected their .git/objects directories to be the same size. See my `du` output below. My hypothesis is that, due to the gradual organic way in which the **ABC** repo was created over the course of a few years, compared to the rapid way in which I cloned it in a few minutes (using a combination of `git remote update`, `git fetch --all`, `git pull --all`, `git branch --track`, `git push --all`, etc.), the **ABC** repo more efficiently re-uses the same objects, whereas the **ABC-clone** repo probably has some duplicate objects that could be garbage collected with something like `git gc`. I'm still digging into this a bit.
* **Difference**: the **ABC** repo (slow) has a few different settings in GitHub Enterprise than the **ABC-clone** repo. Specifically, the **ABC** repo has a few webhooks installed and a few install GitHub Apps, whereas the **ABC-clone** repo has no webhooks and no apps installed. I'm investigating the behavior of the apps currently.

### Are the runtime environments the same, when invoking the `Commit.Patch()` for both repos? Do both invocations have similar CPU, RAM, disk, etc. resources?
Yes. I've done a modest amount of benchmarking, and all my tests indicate that both invocations have similar resources.
* IMPORTANT: notably `git show COMMIT_ID` runs just as fast server-side in both repos when I timed it for the same commit id!!!
* I used another test to very very roughly benchmark multiplication and division operations to ensure that CPU/ALU resource availability was approximately equivalent

### Output of `du -sh .git/*`
```
ABC (slow)                     ABC-clone (fast)
=================================================
4.0K FETCH_HEAD                -
4.0K HEAD                      4.0K HEAD
6.8M audit_log                 400.0K audit_log
4.0K config                    4.0K config
4.0K description               4.0K description
4.0K dgit-state                4.0K dgit-state
0 dgit-state.flock             0 dgit-state.flock
0 hooks                        0 hooks
20.0K info                     12.0K info
4.0K language-stats.cache.     4.0K language-stats.cache
2.8M logs                      1.3M logs
0 nw-sync.lock                 -
1.0M objects                   11.5M objects
88.0K packed-refs              4.0K packed-refs
4.0K refs                      1.3M refs
-                              0 nw-repack.flock
```

### What commit am I testing with?
The commit that I'm testing with is very small. For privacy, I've obfuscated it heavily, but the key aspects (size of changes, number of files modified, type of files, etc.) are the same.
```
commit c372960a4124f724e5b1c967c2913829f8e1eea1 (origin/some-branch-3)
Author: OMITTED <OMITTED>
Date:   OMITTED

    normal commit message blah blah blah

diff --git a/foo/bar/baz/qux-quux/corge.yaml b/foo/bar/baz/qux-quux/corge.yaml
index cc3fd755..4af4d258 100644
--- a/foo/bar/baz/qux-quux/corge.yaml
+++ b/foo/bar/baz/qux-quux/corge.yaml
@@ -30,7 +30, @@ egress:
      ijk.xyz.foobar.io/prox-body-key: "10"
      ijk.xyz.foobar.io/prox-read-limit: "900"
      ijk.xyz.foobar.io/prox-send-limit: "900"
-     ijk.xyz.foobar.io/prox-src-max-age: "100"
+     ijk.xyz.foobar.io/prox-src-max-age: "90"
   hosts:
     - waldo.fred.com
   tls:
@@ -53,7 +53,7 @@ abc:
   xyz:
     name: abc-xyz
     resources:
-      requests: 40G
+      requests: 200G

 variables: {}
```

**Comment by ed-sulli** [comment]
Upon  further investigation, I've discovered that the key difference between the two repos is the existence of forks.

Originally, the **ABC** repo (slow) had multiple forks and the **ABC-clone** repo (fast) did not have any forks. As soon as I created the first fork for **ABC-clone**, go-git slowed down tremendously for **ABC-clone**, making it just as slow as **ABC**.

Why could adding a fork possibly slow down go-git? It probably relates to how GitHub (Enterprise) stores repo objects and how go-gets accesses them. Prior to creating a fork, **ABC-clone** (server-side) stored most of its objects in `.git/objects/pack/` and **ABC-clone** did not have a `.git/objects/info/alternates` file. As soon as I added a fork to **ABC-clone** via the browser, a `.git/objects/info/alternates` file was automatically created with an entry pointing to `.git/objects/../../network.git`. From that point on, most or all of **ABC-clone**'s objects were stored in `.git/objects/../../network.git/objects/pack/` instead of the previous location (`.git/objects/pack`).

For context on why GitHub uses the `.git/objects/info/alternates` file along with the `network.git` storage, especially for repos that have been forked, please read this truly excellent blog post by the GitHub Systems Team: https://github.blog/2015-09-22-counting-objects/ .

My current hypothesis is that Commit.Patch() is slow when using a forked repo because GetTree() in `plumbing/object/tree.go` does not efficiently access objects if they are are stored in `.git/objects/../../network.git` with a reference in `.git/objects/info/alternates`. However, as I previously mentioned in my original post, the CLI command `git diff COMMIT_1 COMMIT_2` is perfectly fast in my environment. So, we could probably pinpoint the source of `Commit.Patch()`'s slowness by comparing its algorithm to that of the CLI tool `git diff`, specifically examining their strategies for getting the pre and post trees.

**Comment by ed-sulli** [comment]
@darkowlzz -- tagging you here in case you have any thoughts. Based on the commit history, it seems like you'd probably have the sharpest insights on our implementation of git alternates (https://github.com/go-git/go-git/commit/eb74b0e1a0ae20075435aded41bffc522bc3554c).

Do you have any ideas what might be causing the slowness that I described above, particularly when we attempt to get a tree from a forked repo that leverages `.git/objects/info/alternates` to point to a packfile (in `.git/objects/../../network.git`) shared by multiple forks?

**Comment by patrickdevivo** [comment]
I don't know if this deserves a separate issue, but similar to the original comment, I'm experiencing very slow calculation of a Patch (really the Stats, but I see the underlying code path just calls Patch). Informally comparing to the performance of git2go and also parsing the output of shelling `git log` there's a decent difference:

```
BenchmarkGoGitRevWalkStats-16                  1        6523562655 ns/op
BenchmarkGitRevWalkStats-16                       2            515182102 ns/op
BenchmarkGit2GoRevwalkStats-16                 1         1744786109 ns/op
```

Is an example of a benchmark run on my laptop of doing a git log like iteration and pulling out the stats (lines added/removed) of every commit.

I'm happy to open a separate issue if that makes more sense! Would love to know if there's some known performance improvements that can be made. This is an awesome project, and I've just started using it to power this tool: https://github.com/augmentable-dev/gitqlite

Thanks!
