### ISSUE TITLE
Why the ListOptions, CleanOptions, ResetOptions, CheckoutOptions don't have Progress; and the workTree.Checkout don't have context?

### ISSUE THREAD

**Issue by wildfire810** [go-git/go-git#695]
Why the ListOptions, CleanOptions, ResetOptions, CheckoutOptions don't have Progress; and the workTree.Checkout don't have context?
They are very usefull.

**Comment by pjbgf** [comment]
Potentially one to be revisited to consolidate the API for V6 (relates to #910).
