### ISSUE TITLE
Unable to clone a repo

### ISSUE THREAD

**Issue by ebosas** [go-git/go-git#699]
Trying to clone a self-hosted git repo using SSH key auth (code below) produces this error:
```
% go run main.go
2023/03/03 20:39:41 repository not found
exit status 1
```
With tracing set to true produces this error:
```
% GIT_TRACE=true go run main.go
2023/03/03 20:42:14 unknown error: 20:42:14.905654 git.c:460               trace: built-in: git upload-pack <git-url>
exit status 1
```
Meanwhile, cloning the repo works perfectly fine using the command line git.

There might be something different about the self-hosted repos which we're not aware of but given that git CLI has no issues performing any actions with them, we would expect the basic functionality to work with `go-git` as well. Would appreciate any insight, thanks.

The code used for testing:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/go-git/go-billy/v5/memfs"
	gogit "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/transport/ssh"
	"github.com/go-git/go-git/v5/storage/memory"
)

func main() {
	publicKey, err := ssh.NewPublicKeysFromFile("git", "/path/to/ssh/key", "")
	if err != nil {
		log.Fatalf("creating ssh auth method")
	}

	_, err = gogit.Clone(memory.NewStorage(), memfs.New(), &gogit.CloneOptions{
		Auth:          publicKey,
		URL:           "<repo-url>",
		Progress:      os.Stdout,
		ReferenceName: plumbing.ReferenceName("refs/heads/master"),
		SingleBranch:  true,
	})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("clone success")
}
```

**Comment by aleksrosz** [comment]
Hi
Is your issue solved?
How does your repo url looks like?

**Comment by matejrisek** [comment]
I'd also like to understand under what conditions is this error occurring for you, since we've seen this error in certain cases but cannot reproduce it locally.

**Comment by f052d536-fdbc-4f85-ad50-cbbe483b4bc9** [comment]
I'm running into the same issue when using a SSH URL. The same URL can be cloned with git.
