### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by vault-thirteen** [go-git/go-git#734]
Hello there.

I do not want to be rude, but at the same time I need to tell you the truth, so let it be.

I have imported this library and saw the list of dependencies.
> module test/a
> 
> go 1.20
> 
> require github.com/go-git/go-git/v5 v5.6.1
> 
> require (
> 	github.com/Microsoft/go-winio v0.5.2 // indirect
> 	**github.com/ProtonMail/go-crypto v0.0.0-20230217124315-7d5c6f04bbb8 // indirect**
> 	github.com/acomagu/bufpipe v1.0.4 // indirect
> 	github.com/cloudflare/circl v1.1.0 // indirect
> 	github.com/emirpasic/gods v1.18.1 // indirect
> 	github.com/go-git/gcfg v1.5.0 // indirect
> 	github.com/go-git/go-billy/v5 v5.4.1 // indirect
> 	github.com/imdario/mergo v0.3.13 // indirect
> 	**github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99 // indirect**
> 	github.com/kevinburke/ssh_config v1.2.0 // indirect
> 	github.com/pjbgf/sha1cd v0.3.0 // indirect
> 	github.com/sergi/go-diff v1.3.1 // indirect
> 	github.com/skeema/knownhosts v1.1.0 // indirect
> 	github.com/xanzy/ssh-agent v0.3.3 // indirect
> 	golang.org/x/crypto v0.7.0 // indirect
> 	golang.org/x/net v0.8.0 // indirect
> 	golang.org/x/sys v0.6.0 // indirect
> 	gopkg.in/warnings.v0 v0.1.2 // indirect
> )

Two of them made me think of using another library to work with git in Go language.
They are following:

> github.com/ProtonMail/go-crypto **v0.0.0-20230217124315-7d5c6f04bbb8** // indirect
> github.com/jbenet/go-context **v0.0.0-20150711004518-d14ea06fba99** // indirect

The first one seems to be a fork of unknown nature.
The second one seems to be an obsolte or dead project.

Would you mind asking maintainers of those two libraries to add versioning to their creations ?

Thank you very much.

**Comment by pjbgf** [comment]
Closing as the dependencies have been updated as per #748.
