### ISSUE TITLE
Improve IPv6 handling for host names

### ISSUE THREAD

**Issue by pjbgf** [go-git/go-git#740]
IPv6 host names are not being properly handled, which results in unhelpful error messages depending on the format used. Examples:

- `git@[::ffff:8c52:7903]:go-git/go-git.git` results in `dial tcp: address [:22: missing ']' in address`
- `git@::ffff:8c52:7903:go-git/go-git.git` results in `dial tcp: lookup git@: no such host`

This issue could be potentially tackled in two ways:
- (short-term) Adding error message highlighting that IPv6 is not supported for host names.
- (long-term) Add full support for IPv6 as host names.

**Comment by crazybolillo** [comment]
I was able to reproduce this with the following test (in `remote_test.go`):

```go
func (s *RemoteSuite) TestFetchIPV6Endpoint(c *C) {
	r := NewRemote(nil, &config.RemoteConfig{Name: "foo", URLs: []string{"http://[2001:db8::]"}})
	err := r.Fetch(&FetchOptions{RemoteName: "foo"})
	c.Assert(err, IsNil)
}
```

The error is returned by `res, err := s.client.Do(req.WithContext(ctx))` on `plumbing/transport/http/common.go:55`:

As far as my understanding goes the `http.session` object must be setup correctly to use tcp6 (in the case of https at least), still looking into it.
