### ISSUE TITLE
fetch from one in-memory repo into another

### ISSUE THREAD

**Issue by petar** [go-git/go-git#746]
At the moment it seems not possible to `Fetch` from one in-memory repo to another, because the `Fetch` method expects a remote address and an in-memory repo doesn't have one.

This feature enables some meaningful use cases. For instance, say you want to fetch multiple branches from different remote repos into a single local repo in parallel. Since fetching into a single repo cannot be done in parallel, a natural strategy would be to create multiple in-memory repos and fetch into them in parallel. Then fetch from all in-memory repos in sequence into a final repo.

**Comment by pjbgf** [comment]
@petar I am under the impression this could be done using the Go version of the `file` transport - as per [this other thread](https://github.com/go-git/go-git/issues/838#issuecomment-1793441813). Main difference is that you would have a hierarchy of in memory fs for this to work.

**Comment by pjbgf** [comment]
@petar I am not sure the performance benefit of running those clones in parallel can counter the increased amount of data to be transferred (unless you are talking about shallow clones).

Anyways, I gave this a quick go and it seems to be possible: 

```go
var wg sync.WaitGroup

// /
// /target
// /src
//
//	/go-git
//	/go-billy
func main() {
	rootfs := memfs.New()
	target, _ := rootfs.Chroot("/target")
	src, _ := rootfs.Chroot("/src")
	master, _ := src.Chroot("/go-git-master")
	concurrency, _ := src.Chroot("/go-git-concurrency")

	wg.Add(2)
        // providing a thread safe memfs enables running the below as go routines
	clone(master, "https://github.com/go-git/go-git", "master")
	clone(concurrency, "https://github.com/go-git/go-git", "read-concurrency")
	wg.Wait()

	loader := server.NewFilesystemLoader(rootfs)
	client.InstallProtocol("file", server.NewClient(loader))

	url := "file:///src/go-git-master"

	dot, err := target.Chroot(".git")
	CheckIfError(err)

	Info("git clone %s", url)
	storer := filesystem.NewStorage(dot, cache.NewObjectLRUDefault())
	r, err := git.Clone(storer, target, &git.CloneOptions{
		URL: url,
	})
	CheckIfError(err)

	ref, err := r.Head()
	CheckIfError(err)

	commit, err := r.CommitObject(ref.Hash())
	CheckIfError(err)

	fmt.Println(commit)

	url2 := "file:///src/go-git-concurrency"
	err = r.Fetch(&git.FetchOptions{
		RemoteURL: url2,
		RefSpecs: []config.RefSpec{
			...
		},
	})
	CheckIfError(err)
}

func clone(fs billy.Filesystem, url, branch string) {
	storer := filesystem.NewStorage(fs, cache.NewObjectLRUDefault())

	_, err := git.Clone(storer, nil, &git.CloneOptions{
		URL:           url,
		SingleBranch:  true,
		ReferenceName: plumbing.NewBranchReferenceName(branch),
	})
	wg.Done()

	CheckIfError(err)
	fmt.Printf("Clone %q from %q: DONE\n", branch, url)
}
```

There are two issues: a) we would need to provide a thread-safe `memfs` as the current one would panic intermittently due to the parallel access and b) the fetching is hitting a object not found error I could not get to the bottom of. This may be related to other existing issue and not be specific to this use case.

**Comment by pjbgf** [comment]
The concurrency issues alluded above are being tracking as part of other issues.

Closing this one as the example above seems to cover the main point to the issue. Happy to reopen it if I missed something.
