### ISSUE TITLE
How to find the commit referenced by a tag in a remote repository?

### ISSUE THREAD

**Issue by andrewpollock** [go-git/go-git#749]
I have a related question/problem to #87 but with a remote repository (i.e. from `NewRemote`)

The tags returned from `List` resolve to the hashes of the tags, not the underlying commits, and `ResolveRevision` isn't an option on a remote repository.

For example, examining https://github.com/aide/aide, with:

```
.
.
.
5ee3529c3014b4238231885b1403faa3e1affb5c        refs/tags/v0.18.1
de5bb24b9b24df7598161a1ce19dc2ce15afa9c6        refs/tags/v0.18.1^{}
.
.
.
```

The references returned from `List` only include the one reference for the `v0.18.1` tag, and `5ee3529c3014b4238231885b1403faa3e1affb5c` is the hash of the tag itself, not the underlying commit `de5bb24b9b24df7598161a1ce19dc2ce15afa9c6`

https://github.com/google/osv.dev/blob/bf67aafde6fa58618e02a016a505b4a8116f6ca2/vulnfeeds/git/repository.go#L60 is where I'm using the library currently.

**Comment by andrewpollock** [comment]
I think in Git parlance, I'm trying to get the peeled tag

**Comment by andrewpollock** [comment]
I can see that the [`AdvRefs` struct](https://github.com/go-git/go-git/blob/0a1c5ab118998a22ef88d8e6c42970197d77413c/plumbing/protocol/packp/advrefs.go#L17) has a `Peeled` field, but it looks like all of the related methods only operate on the `References` field...

**Comment by pjbgf** [comment]
@andrewpollock I am not sure you can do that simply with ls remote. But you could shallow clone a repo, get its tags and then resolve them:

```go
func main() {
	url := "https://github.com/go-git/go-git"

	storer := memory.NewStorage()
	fs := memfs.New()

	r, err := git.Clone(storer, fs, &git.CloneOptions{
		URL:   url,
		Depth: 1,
	})
	if err != nil {
		log.Fatal(err)
	}

	refs, err := r.Tags()
	if err != nil {
		log.Fatal(err)
	}

	err = refs.ForEach(func(ref *plumbing.Reference) error {
		commitId, err := r.ResolveRevision(plumbing.Revision(ref.Name()))
		if err != nil {
			return nil
		}

		log.Printf("%s: REF ID: %s (COMMIT ID: %s)\n", ref.Name(), ref.Hash(), commitId)
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by andrewpollock** [comment]
>  I am not sure you can do that simply with ls remote

You can, because the output I quoted is from `ls-remote`. The peeled tag has the suffix characters.

Cloning of any sort is a non-starter due to the quantity of repos I'm dealing with

**Comment by pjbgf** [comment]
@andrewpollock you are absolutely right. I dug in a bit further and noticed that the peel refs are part of the initial pack exchange, but we don't provide a way for users to consume it.

I still need to work out the API (which I will in the next few days or so), do you mind giving it a go and confirming this resolves your use case? I amended the existing example based on the issue you linked: https://github.com/go-git/go-git/pull/750/

**Comment by andrewpollock** [comment]
> do you mind giving it a go and confirming this resolves your use case?

Absolutely! You solve my problem, I commit (pun intended) to using it :-)
