### ISSUE TITLE
Does go-git support "insteadOf" replacements for repo urls (in gitconfig)

### ISSUE THREAD

**Issue by kostyay** [go-git/go-git#76]
I can't seem to find any reference to this in the code.
Does go-git know how to handle configurations such as `git config --global url.ssh://git@github.com/.insteadOf https://github.com/`?

Thanks in advance.

**Comment by mcuadros** [comment]
It's not supported. But it could be an easy one.

**Comment by kostyay** [comment]
Let me know what you think
https://github.com/go-git/go-git/pull/79

**Comment by gcstang** [comment]
@kostyay is there an example on how to use this with git.PlainClone ?
