### ISSUE TITLE
please explain how go-git is "extensible" ?

### ISSUE THREAD

**Issue by jan4984** [go-git/go-git#777]

**Comment by carepollo** [comment]
I  want to know too

**Comment by luisnquin** [comment]
Me too

**Comment by pjbgf** [comment]
The `go-git`'s extensibility features that I am aware of:
- Filesystem abstraction is based on `go-billy`, new filesystem types can be supported by implementing the [Filesystem interface](https://github.com/go-git/go-billy/blob/326c59f064021b821a55371d57794fbfb86d4cb3/fs.go#L52).
- Dot git storers are represented by their own [Storer interface](https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/storage/storer.go#L16).
- Hash implementations can be extended by implenting `crypto.Hash` via [hash.RegisterHash](https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/plumbing/hash/hash.go#L30).
- The various Git transport schemes supported (`http`, `https`, `ssh`, `git`, `file`) can be extended by implementing the [transport.Transport interface](https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/plumbing/transport/common.go#L48) and configured via [client.InstallProtocol](https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/plumbing/transport/client/client.go#L25).
- Cache implementation can be extended by implementing the [cache.Object interface](https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/plumbing/cache/common.go#L17).

There may be other things I am not aware of, after all I am not versed in the entire code base. There are also some [internal interfaces](https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/plumbing/transport/internal/common/common.go#L35) that could be made public in the future, to expand `go-git`'s extensibility.
