### ISSUE TITLE
Too hard to use

### ISSUE THREAD

**Issue by yangyile1990** [go-git/go-git#788]
please give some example of how to:

git checkout main
git pull
git checkout -b newbranch
git add .
git commit -m 'msg'
git push

**Comment by aleksrosz** [comment]
Hi
Have you checked examples in https://github.com/go-git/go-git/tree/master/_examples ?

**Comment by pjbgf** [comment]
The examples pointed out by @aleksrosz and test code are the key source of information on how to use `go-git` at present.
Anyone is more than welcome to propose improvements on documentation or examples via PRs.

Merge is currently not supported, as per [COMPATIBILITY.md](https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md).
