### ISSUE TITLE
Question: branch.ForEach can not  get all branches,only get master.

### ISSUE THREAD

**Issue by Cool-breezeee** [go-git/go-git#790]

**Comment by Cool-breezeee** [comment]
target: i want to use commit-id to find branch.
doing:
1. i use git.clone to get the repository
2. use repository's branches function to get the storer.ReferenceIter = branches
3. !!!(question) branches.ForEach ,find all branches,code : commitIter, err := repo.Log(&git.LogOptions{From: ref.Hash()}),but i only find master branch
4. use branch find commit history list ,match the commit i want ,then i konw the branch.

the third part have question ,i can not use branch.ForEach to get all the branch,only get master.

**Comment by pjbgf** [comment]
@Cool-breezeee Probably you are fetching only the remote `master` branch ref, I think you may be able to resolve this by setting a wildcard refspec. As per: https://github.com/go-git/go-git/blob/35f7e6770361a2c16c9b6c44acdc38ae04c75bd3/remote_test.go#L72
