### ISSUE TITLE
Question: is it possible to create a new repository and push to remote without creating the remote repository on github webpage first?

### ISSUE THREAD

**Issue by hatshepsut-working** [go-git/go-git#791]
I am asking this is because I have this requirement might need code to automatically create new repositories remotely, but I don't see examples in document describing this. Could anyone help?

**Comment by crazybolillo** [comment]
Probably should look into the Github API:

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository

Gitlab also has one

**Comment by pjbgf** [comment]
To talk with the GitHub control plane, to create a repository, you can use: https://github.com/fluxcd/go-git-providers/
