### ISSUE TITLE
Cannot clone a repository of zipped setup files

### ISSUE THREAD

**Issue by tahatsahin** [go-git/go-git#794]
Hello,

First of all, thank you for this package!

I am experiencing a problem while cloning a repository. 

When I try to clone a repository with using git.PlainClone it is working properly. However, while cloning one of my companies repos, git outputs as it is cloned. I am putting the output below.

> Enumerating objects: 70, done.
> Counting objects: 100% (70/70), done.
> Compressing objects: 100% (68/68), done.
> Total 70 (delta 14), reused 0 (delta 0)
> Installer repository cloned successfully.

When I check the destination path, I see that all the folders are cloned. Normally we are storing big zipped files in our repository (mostly zipped internal setup files), after clone is finished, I move into a folder and I see that the zip files are there and they are 1kB (normally 1GB). 

At first I thought this is a repo/LFS issue but when I try to clone the same repository by using Git Bash with
``git clone {repo_url}`` it clones successfully.

We have 2 other LFS repositories, which don't have such big files (5-10MB). I tried to clone them using go-git, and they are cloned successfully. 

My second thought was, it is a buffer size problem and I wanted to change buffer size, however I don't think there is a clone option for that. (at least I couldn't find one)

I am leaving my code below.

````

var wg2 sync.WaitGroup
wg2.Add(1)
go cloneInstallersRepo(installersRepo, repoPath, auth, &wg2)

func cloneInstallersRepo(installersRepo string, path string, auth *http.BasicAuth, wg *sync.WaitGroup) {
	defer wg.Done()
	fmt.Println("Cloning installers repository...")

	installersDir := path + "/INSTALLERS"
	// Create a directory for installers
	err := os.Mkdir(installersDir, 0755)
	if err != nil {
		fmt.Printf("failed to create directory %s: %s", installersDir, err)
		return
	}

	// Clone the installers repository
	_, err = git.PlainClone(installersDir, false, &git.CloneOptions{
		URL:      installersRepo,
		Auth:     auth,
		Progress: os.Stdout,
	})
	if err != nil {
		fmt.Printf("failed to clone installers repository: %s", err)
		return
	}

	fmt.Println("Installers repository cloned successfully.")
}

````
Any help is appreciated.

Thank you!

**Comment by AriehSchneier** [comment]
Is there a public repo where you can reproduce this issue?

**Comment by tahatsahin** [comment]
Let me find and come back to you. 
Thanks for the reply.
