### ISSUE TITLE
worktree.Add() is very slow

### ISSUE THREAD

**Issue by gdamore** [go-git/go-git#8]
I have a commit that has about 2 hundred files in it.  Adding files is really slow -- each call to add takes a substantial portion of a second (typically 200-500 msec)  -- my repo is large. 

There was a similar issue filed against the src-d repo -- claiming that Add() calls Status() each time, which makes this an O(N^2) algorithm.

**Comment by ovaldi** [comment]
Hello, any update on this issue?

**Comment by Purushotham233** [comment]
Facing the same issue with v5.2.0.

Repo has ~15K files.
Using memory storage.
