### ISSUE TITLE
Is it possible to disable logging?

### ISSUE THREAD

**Issue by kutluhanmetin** [go-git/go-git#805]
For example, when I use `git.PlainClone` function, it logs
```
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Compressing objects: 100% (7/7), done.
Total 13 (delta 0), reused 10 (delta 0), pack-reused 0
```
these lines. Is there a configuration to disable it? I don't want it to write any output.

**Comment by AriehSchneier** [comment]
Both `CloneOptions` and `FetchOptions` have a `Progress` parameter, are you setting that? Try leaving it as `nil`.
