### ISSUE TITLE
[Q] Filter commits by author.

### ISSUE THREAD

**Issue by FL3SH** [go-git/go-git#81]
Hi, 
How can I filter commits by the author?

I looked into `Log`, but `LogOptions` doesn't contain filed author. 
I would like to archive similar functionality to `git log --author='<author>'`

Thanks in advance.

**Comment by mcuadros** [comment]
There is not a specif function for this. The best option is just to filter the output of the `Log`, there is no performance benefit on implementing inside of go-git, since the commit should be decoded to read the author.

**Comment by FL3SH** [comment]
Thank you
