### ISSUE TITLE
BUG: go-git clone is incomplete

### ISSUE THREAD

**Issue by SunYonge** [go-git/go-git#817]
In addition, sometimes my network is relatively poor, which will cause errors when I use go-git (incomplete warehouse pull), prompting error: reference not found, or some files indicate that they have not been cloned, only if I completely delete the local warehouse generated by using go-git, and execute go-git clone again, the clone can proceed normally. How can I solve this problem?
Our project has to use go-git/v5, but these two problems have been bothering me for a long time, help me, homie.

**Comment by flylan** [comment]
To my knowledge, go git is not like native git. After executing commands such as git clone or git pull, it automatically performs integrity verification on the data. The integrity verification logic needs to be implemented by myself. I am also a novice to go git and look forward to someone else providing code for go git to verify warehouse integrity
