### ISSUE TITLE
Worktree Checkout behavior is different from git

### ISSUE THREAD

**Issue by fsmiamoto** [go-git/go-git#83]
From what I've noticed, the `Checkout` method on `Worktree` behaves differently than standard git.

For example, given an untracked file in the working directory of some branch tree, calling `Checkout` with the default options, to another branch, would remove that file, which would not happen with the standard `git checkout other-branch`.

Using the `Keep` option wouldn't help much, as files that were added and committed would remain in the working directory after a checkout.

I suppose this has to do with the current implementation where the `Checkout` acts somehow like `git reset`.

Is this expected or is it something to look into?
Thanks!

**Comment by mcuadros** [comment]
go-git should behave always as the original git

**Comment by pupizoid** [comment]
Also i've noticed the lack of ability to specify concrete files to checkout like in original git with `--`

**Comment by custa** [comment]
> Also i've noticed the lack of ability to specify concrete files to checkout like in original git with `--`

I need this function, is it other way to do that?

**Comment by steffakasid** [comment]
I have the same issue. I'm checking out into a bare repo and use `git --git-dir=$HOME/.git --work-tree=$HOME checkout`. With vanilla git this works but when using go-git. It would remove my complete $HOME.
