### ISSUE TITLE
Repository.CreateBranch fails if a remote branch exists with the same name

### ISSUE THREAD

**Issue by mykter** [go-git/go-git#85]
I tried to create a local branch based on a remote branch by doing this:
```go
err = repo.CreateBranch(&gitconfig.Branch{Name: b, Remote: "origin", Merge: plumbing.NewBranchReferenceName(b)})
```
However it returns ErrBranchExists even though the local branch doesn't exist. It looks like it is comparing based on name alone, not whether it is local or remote.

I instead got it to work following `_example/branch`:
```go
targetRef, err := repo.Reference(plumbing.NewRemoteReferenceName("origin", b), true)
if err != nil {
	t.Fatalf("Couldn't get reference for remote branch: %v", err)
}
ref := plumbing.NewHashReference(plumbing.ReferenceName("refs/heads/"+b), targetRef.Hash())
err = repo.Storer.SetReference(ref)
```

Have I misunderstood something, or is it a bug that CreateBranch doesn't differentiate between local and remote branches?

**Comment by yorchperaza** [comment]
This issue is still pending, exist planes to board? @mcuadros
