### ISSUE TITLE
`go-git` doesn't obey `.gitignore`- ignores `node_modules/` line.

### ISSUE THREAD

**Issue by ayjayt** [go-git/go-git#859]
It (go-git) doesn't obey `.gitignore` - it doesn't obey the `node_modules/` line when pulling status from a worktree. `git status` on cli does obey that line. But go-git treats `node_modules/` like it's not ignored.

I tried adding
```
node_modules
node_modules/*
node_modules/**
```

to `.gitignore` as well. Still shows up in `worktree.Status()`.

Eventually added it to `.git/info/exclude` as well. Didn't work.

note: has something to do maybe with `.git` subdirectories in `node_modules` maybe?

**Comment by FlorianLoch** [comment]
I am experiencing the same/a similar issue. `go-git` does not ignore files in `node_modules` -not only resulting in the indication of a dirty workspace while `git` claims it to be clean and also in degraded performance because if has to traverse the possible huge file tree below `node_modules`.

**Comment by rodolfodalbuquerque** [comment]
I'm experiencing the same thing with .terraform directory... any workarounds?

**Comment by FlorianLoch** [comment]
Not that I'd be aware of.
Sorry.

Actually, it is a little disappointing that it seems like this issue didn't get any attention so far...

**Comment by dbergamin** [comment]
I believe the issue occurs when there are .gitignores in subdirectories. If you're using this as part of a build, I worked around it by cleaning them up in shell before running my Go code:
```
find node_modules -name .gitignore -delete
```

**Comment by pjbgf** [comment]
Closing as duplicate as per above.

@dbergamin thanks for helping keeping the project tidy. :bow:
