### ISSUE TITLE
How to find the commit referenced by a tag?

### ISSUE THREAD

**Issue by linlycode** [go-git/go-git#87]
A tag is a `*plumbing.Reference`, the hash points to the tag itself, not the commit, how do I find the commit referenced by the tag?

Also, using *git* I can find the commit hash by `git rev-list -n 1 TAG`, but go-git doesn't seem have corresponding API

**Comment by ilius** [comment]
I think you should use `ResolveReference` from [plumbing/storer/reference.go](https://github.com/go-git/go-git/blob/master/plumbing/storer/reference.go#L216)

**Comment by linlycode** [comment]
> I think you should use `ResolveReference` from [plumbing/storer/reference.go](https://github.com/go-git/go-git/blob/master/plumbing/storer/reference.go#L216)
> 
> ```
> storer.ResolveReference(store, plumbing.NewTagReferenceName(tagName))
> ```

No, it doesn't work, `ResolveReference` resolves a `SymbolicReference` to a `HashReference`, not to the referenced object

**Comment by rh-codebase** [comment]
This worked for me if I'm understanding what you want:
// For a tag named: v1.2.0, append ^{}
tagr := plumbing.Revision("v1.2.0^{}")
commitHash, _ := repo.ResolveRevision(tagr)

This is analogous to:
git rev-parse <tag>   which returns the hash of the annotated tag 
git rev-parse <tag>^{} which returns the hash of the commit associated with the tag.

**Comment by magnusbaeck** [comment]
Call Repository.TagObject to obtain an *object.Tag, then find the target commit (or whatever the tag points to) in the Target field.
