### ISSUE TITLE
using go-git v5, trying to r.Push() repository, authorization failed (basic-auth)

### ISSUE THREAD

**Issue by kacey-lunacare** [go-git/go-git#886]
```golang
	repository, err := git.PlainClone(dir, false, &git.CloneOptions{
		URL:      repoUrl,
		Progress: os.Stdout,
		Auth:     &auth})
	if err != nil {
		log.Error().Err(err).Msg("Failed to clone github repository")
	}
...
...
...
	err = repository.Push(&git.PushOptions{
		RemoteName: "origin",
		Auth:       &auth,
	})

```

This clones the repository fine, but I am not able to push after adding a few files. I can confirm by `cd` into the directory and running things like `git log` I see the files and the commit in the log. 

```
{"level":"info","time":"2023-10-22T22:25:30Z","message":"Pushing commit to repo"}
{"level":"error","error":"authorization failed","time":"2023-10-22T22:25:30Z","message":"Failed to push to repo"}

```

The repo is using https, I am using an access token with the authentication. I thought I might not have the right permissions so I tried granting all permissions and using the classic access token, and the fine grained access token and neither work :( 

Is there any chance anyone has insight as to what is happening, or do you guys know how I could log out more details to make the error more interesting?

**Comment by AriehSchneier** [comment]
Are you trying to push to a protected branch?

**Comment by kacey-lunacare** [comment]
I just realized that even though I thought I had write permissions and the various curl's to github api seemed to indicate I had permission, the default permission for members in our github org was set to 'read' not 'write', so I did in fact, not have permission to write. 

Sorry about that, thanks for looking into it! I'm going to go ahead and close this issue, wooops.
