### ISSUE TITLE
Move over issues with GitHub API

### ISSUE THREAD

**Issue by bufdev** [go-git/go-git#9]
Thanks for continuing to maintain this, it's appreciated.

Are there any plans to (at least selectively) move issues over from src-d/go-git using the GitHub API, and potentially notify PR authors to move their PRs to here? For example https://github.com/src-d/go-git/pull/1273 (a PR, not an issue, but related) is something I put up a while ago.

**Comment by mcuadros** [comment]
I moved some PR's by hand, and I merged it. For this one fill free to re-submit here.

About the issues... definitely yes. I need to write a script as I did with the release or figure out how to move it.  Help is more than appreciated. 

Thanks!

**Comment by bufdev** [comment]
OK sounds good. Should this issue be kept open to track this?

I submitted https://github.com/go-git/go-git/pull/10 that copies https://github.com/src-d/go-git/pull/1273 over

**Comment by JalonSolov** [comment]
This might be useful, if you're not anti-Python (as I am):  https://github.com/ahadik/git_mover

Of course, it is fairly simple Python, just using the GitHub REST api.

If you are as Python averse as I am, maybe https://github.com/google/grumpy will do the job.  :-)

**Comment by tebrizetayi** [comment]
I would like to contribute this project. Could you help me?

**Comment by bufdev** [comment]
Any status update on this?
