### ISSUE TITLE
feature request: support sparse checkout

### ISSUE THREAD

**Issue by missedone** [go-git/go-git#90]
https://github.blog/2020-01-13-highlights-from-git-2-25/
git supports sparse checkout.
in my case, i'd like to clone (checkout) a subfolder out of a large git repo
for now it seems can not be done with go-git.

thanks

**Comment by copernico** [comment]
+1

**Comment by c4milo** [comment]
this will be a great addition 🙌

**Comment by cdffroro** [comment]
i want to know if it supports sparse checkout now?

**Comment by GridexX** [comment]
We really need this feature, please it will help us a lot :+1:

**Comment by yordis** [comment]
Hey folks, I am trying to contribute to ArgoCD (and potentially FluxCD) by adding sparse checkout: https://github.com/argoproj/argo-cd/pull/14272

But it seems it is not supported. Any opportunity to make the issue a priority?

**Comment by yordis** [comment]
I removed the usage of the package btw!

**Comment by emirot** [comment]
@yordis @antonosmond 

What does not work? 

It only checkout one directory in my test: https://github.com/emirot/test-go-git/tree/main

**Comment by jberger-dynatrace** [comment]
We would appreciate this feature as well!

**Comment by object88** [comment]
I also am having trouble using `SparseCheckoutDirectories` (with go-git v5.11.0).  My case may be _slightly_ strange, though.  I want to get a sparse checkout from a _particular_ commit.  My code, in brief:
```
        # sha -> 40 character SHA
        # path -> subfolder in my repo, ala "src/app/config"
        # repo -> git form of my repo, ala "git@github.com:myorg/myrepo.git"

	tempDir, _ := os.MkdirTemp("", "source-*")
	fs := osfs.New(tempDir)
	dot, _ := fs.Chroot(".git")
	s := filesystem.NewStorage(dot, cache.NewObjectLRUDefault())

	refspec := config.RefSpec(fmt.Sprintf("+%s:refs/remotes/origin/%s", sha, sha))
	r, _ := gogit.Init(s, fs)
	r.CreateRemote(&config.RemoteConfig{
		Fetch: []config.RefSpec{refspec},
		Name:  "origin",
		URLs:  []string{repo},
	})
	w, _ := r.Worktree()

	r.Fetch(&gogit.FetchOptions{
		Depth:           1,
		InsecureSkipTLS: false,
		Tags:            gogit.NoTags,
	})

	w.Checkout(&gogit.CheckoutOptions{
		Hash:                      plumbing.NewHash(sha),
		SparseCheckoutDirectories: []string{path},
	})
```

While the sample code above does not show error checking, it is present in my actual code, and no errors are coming back.

I have also tried setting `path` as just "src" (instead of "src/app/cfg") to match the [test mentioned above](https://github.com/emirot/test-go-git/blob/main/main.go), but same behavior.  Also same if I add a `Force: true` to the `CheckoutOptions`.

**Comment by wilstdu** [comment]
> @yordis @antonosmond
> 
> What did not work?
> 
> It looks to be working in my simple test: https://github.com/emirot/test-go-git/tree/main

@emirot for you this works, because your example doesn't have `NoCheckout: true`, in git.CloneOptions of git.PlainClone

**Comment by wandergeek** [comment]
Would also love this feature!

**Comment by kushagra-saxena-exa** [comment]
I can see the PR opened. is it planned in next release?

**Comment by JJHWAN** [comment]
is [PR](https://github.com/go-git/go-git/issues/90) being reviewed?

**Comment by exu** [comment]
Anyu chance for it to be released? Looks like last release was in March
