### ISSUE TITLE
Add Merge Functionality

### ISSUE THREAD

**Issue by patgmiller** [go-git/go-git#905]
I'd like to help add merge functionality. I didn't find any existing issues, but there does appear to be a stale pull request #442. This can be starting point. 

I'll work to finish initial goal of PR #442 and expect that will provide good context and additional direction to move forward with. 

- [ ] Add merge default behavior (ff)
- [ ] what's next?

**Comment by pjbgf** [comment]
@patgmiller the comments in https://github.com/go-git/go-git/pull/442#issuecomment-1539110695 still applies. So feel free to propose a new PR to that effect.
