### ISSUE TITLE
is there an easy way to do git checkout?

### ISSUE THREAD

**Issue by stephencheng** [go-git/go-git#94]
In go-git, there are quite different ways to checkout:
1.  rev with SHA
2. tag name
3. branch name

And with my test, there are bugs in the examples to deal with above checkout.

What I would like to achieve is to checkout a generic name, this name could be one of above, in essence, it is exactly what: git checkout does

Just wondering if this could be wrapped up with one function instead of dealing with different func calls like above.

Thanks

**Comment by nodece** [comment]
It's a great feature, I need the feature, too.

same issues: #132

**Comment by stephencheng** [comment]
@nodece @mcuadros FYI

I hit hard bump using go-git when try to test the different checkout, there are bugs even the example code can not pass. For my current project, I had alternative way to route the checkout to a shell call :(

Check it out how is it done if you are interested: https://github.com/upcmd/up

**Comment by rbuck-som** [comment]
> @nodece @mcuadros FYI
> 
> I hit hard bump using go-git when try to test the different checkout, there are bugs even the example code can not pass. For my current project, I had alternative way to route the checkout to a shell call :(
> 
> Check it out how is it done if you are interested: https://github.com/upcmd/up

Problem with that approach, there's then no point of using go-git. If you have to shell out to use real Git, what is the point to this library. Zero point.
