### ISSUE TITLE
Checkout removes untracked files

### ISSUE THREAD

**Issue by sclark-dev** [go-git/go-git#970]
In Git, running checkout does not affect untracked files. Meanwhile go-git does the equivalent of a reset. All untracked files are lost.

Is this intentional? More importantly, is there a workaround for this?

**Comment by sclark-dev** [comment]
I've looked into more information about this, and it turns out this has been an issue for years.

https://github.com/src-d/go-git/issues/1026#issue-382413262

If this cannot be fixed, it should at least be documented to save people some time.

**Comment by Chroq** [comment]
I had this issue, you can use **Keep:true** in your worktree checkout option struct :

```go
err := worktree.Checkout(&git.CheckoutOptions{
		Branch: plumbing.NewBranchReferenceName(branchName),
		Keep:   true,
	})
```

**Comment by fcharlie** [comment]
The crux of the issue seemingly stems from go-git's lack of a merge function. In line with the core principles of git checkout/switch, if there have been no modifications to the worktree and index upon checkout, a direct reset of both is sufficient. Conversely, the matter becomes significantly intricate. This scenario warrants the detection of file conflicts, which might necessitate a complex three-way merge to resolve.

Employing Keep could potentially result in an overwhelming tally of modifications. In contrast, SoftReset deftly bypasses alterations to the index and workspace. Irrespective of the magnitude of the gap between branches, expectations remain unfulfilled.

**Comment by pjbgf** [comment]
Closing as per @Chroq's reply.

**Comment by kimdre** [comment]
Same for me. When specifying `Keep: true` in the CheckoutOptions, the checkout does not work and nothing changes.

**Comment by pjbgf** [comment]
For future reference, this is already fixed on `v6@main` as per https://github.com/go-git/go-git/pull/1564. However, [this](https://github.com/go-git/go-git/pull/1564/changes/aa09c632f192bba78b2e37526ffee00070269845) is yet to be back-ported to the [v5 release branch](https://github.com/go-git/go-git/tree/releases/v5.x). If you need this fix please create a PR and tag me for a review.
