### ISSUE TITLE
An error occurred when cloning a large repo.

### ISSUE THREAD

**Issue by moqsien** [go-git/go-git#982]
ERROR:  **unexpected EOF**

When cloing a very large repo,  **unexpected EOF** occurs.

Any ideas?

**Comment by iainjreid** [comment]
@moqsien I've just encountered the same problem when cloning a large repository over just over 5000 commits. Did you find a solution to this problem?

**Comment by pjbgf** [comment]
@iainjreid please share a code snippet to enable folks to reproduce the issue.
