### ISSUE TITLE
Add option to skip git status check when adding a file

### ISSUE THREAD

**Issue by moranCohen26** [go-git/go-git#993]
I noticed that in large repository Status() takes too long time (5 sec in my case). In scale this is something that would be nice to improve to get a better performance, more so if you already know that which files you modified and want to add to stage.
My suggestion is to add "skipStatus" option to AddWithOptions to gain a better performances. 
I will apply only if Path option is given and All option is not given. Anyway from my tests there should be no impact if you are trying to add a non modified file, behavior will be the same like you are not using the "skipStatus" flag.

**Comment by moranCohen26** [comment]
Please see my [PR](https://github.com/go-git/go-git/pull/994) as suggested solution for this

**Comment by moranCohen26** [comment]
@pjbgf will appreciate your response, if anything missing in my issue or PR please let me know :pray:

**Comment by pjbgf** [comment]
Closing as per #994.
