### ISSUE TITLE
How to list all the repositories belong to a user?

### ISSUE THREAD

**Issue by yaochenkun** [go-git/go-git#999]
I find all the apis of go-git but not found the way to listing all the repositories belong to a user.

**Comment by AriehSchneier** [comment]
Do you mean on github? If so that is not in the git protocol (and therefore wouldn't be in go-git), you want to look at the github apis...
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user
or via cli:
https://cli.github.com/manual/gh_repo_list

**Comment by pjbgf** [comment]
Apart from the points Arieh raised, there is also a Go library for talking with GitHub's API: https://github.com/google/go-github.

**Comment by pjbgf** [comment]
Closing as not directly related to go-git.
